-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_generic_mlp_head45_e3_lut_b0_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_generic_mlp_head45_e3_lut_b0_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101100111010100100111110000", 1 => "00111100001010010110011010110100", 2 => "00111101100110101000100101000010", 3 => "00111101001110111000011110100111", 
    4 => "00111100101110000101101111100000", 5 => "10111010001011111011100101101101", 6 => "10111100011001011100101010100101", 7 => "00111101001011101001001011111001", 
    8 => "00111101010110110000110001110011", 9 => "10111101000101101000101101010111", 10 => "10111100001001001001111001010000", 11 => "10111101001001101011111001100101", 
    12 => "00111101001010110111101010110001", 13 => "10111100110001010001011111011010", 14 => "10111101010000100110111001010011", 15 => "00111101000110100110110100011111", 
    16 => "00111101100000101001111011101010", 17 => "00111100100001011001100100000100", 18 => "00111101001000010101010010110010", 19 => "10111100101101110001100000010011", 
    20 => "00111100000011100011111101101011", 21 => "00111011110111111000100110111010", 22 => "10111011110111100110010000001110", 23 => "10111011101001100011010101111000", 
    24 => "00111110000000010010111010100010", 25 => "00111101001010110001111111000000", 26 => "00111101001011000001111010110000", 27 => "00111100100001010110111001101101", 
    28 => "00111101000001011000010000000111", 29 => "00111101100011100111011100011110", 30 => "00111101100010000101001110110000", 31 => "00111101010010000000101001111010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

