-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_generic_mlp_head45_Pipeline_VITIS_LOOP_736_3_p_ZL9e3_lut_w1_9_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_generic_mlp_head45_Pipeline_VITIS_LOOP_736_3_p_ZL9e3_lut_w1_9_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111100110011001111010001101100", 1 => "00111110010110100110001101111011", 2 => "10111100101110100111001110101100", 3 => "10111101111100100101101101010110", 
    4 => "10111101110111010111001010001011", 5 => "10111101000111111111101111000111", 6 => "00111101110011101110101101101110", 7 => "10111110001100100000110011010101", 
    8 => "10111101100000100000011110111110", 9 => "10111101101011001101010001110110", 10 => "10111101010110000011110101001100", 11 => "00111101010100101010101010011001", 
    12 => "00111100101100010111100010011000", 13 => "00111101001111101010011101101011", 14 => "10111100001011100001000110010010", 15 => "10111101101110011010100100010100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

