// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module graph_moe_graph_moe_Pipeline_VITIS_LOOP_243_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        max_logit,
        max_logit_21850,
        max_logit_22046,
        max_logit_21954,
        max_logit_1_out,
        max_logit_1_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] max_logit;
input  [31:0] max_logit_21850;
input  [31:0] max_logit_22046;
input  [31:0] max_logit_21954;
output  [31:0] max_logit_1_out;
output   max_logit_1_out_ap_vld;

reg ap_idle;
reg max_logit_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln243_fu_106_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln243_reg_272;
wire   [31:0] max_logit_2_fu_136_p3;
reg   [31:0] max_logit_2_reg_276;
wire   [31:0] max_logit_3_fu_242_p3;
reg   [31:0] max_logit_3_reg_283;
reg   [31:0] max_logit_1_fu_50;
reg   [31:0] ap_sig_allocacmp_max_logit_1_load_1;
wire    ap_block_pp0_stage0;
wire    ap_loop_init;
reg   [2:0] e_1_fu_54;
wire   [2:0] add_ln243_fu_144_p2;
reg   [2:0] ap_sig_allocacmp_e;
wire    ap_block_pp0_stage0_01001;
wire   [1:0] trunc_ln245_fu_112_p1;
wire   [0:0] icmp_ln245_fu_116_p2;
wire   [0:0] icmp_ln245_1_fu_130_p2;
wire   [31:0] select_ln245_fu_122_p3;
wire   [31:0] bitcast_ln245_fu_159_p1;
wire   [31:0] bitcast_ln245_1_fu_176_p1;
wire   [7:0] tmp_fu_162_p4;
wire   [22:0] trunc_ln245_1_fu_172_p1;
wire   [0:0] icmp_ln245_3_fu_200_p2;
wire   [0:0] icmp_ln245_2_fu_194_p2;
wire   [7:0] tmp_5_fu_180_p4;
wire   [22:0] trunc_ln245_2_fu_190_p1;
wire   [0:0] icmp_ln245_5_fu_218_p2;
wire   [0:0] icmp_ln245_4_fu_212_p2;
wire   [0:0] tmp_6_fu_89_p2;
wire   [0:0] or_ln245_fu_206_p2;
wire   [0:0] and_ln245_fu_230_p2;
wire   [0:0] or_ln245_1_fu_224_p2;
wire   [0:0] and_ln245_1_fu_236_p2;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 max_logit_1_fu_50 = 32'd0;
#0 e_1_fu_54 = 3'd0;
#0 ap_done_reg = 1'b0;
end

graph_moe_fcmp_32ns_32ns_1_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_1_no_dsp_1_U8(
    .din0(max_logit_2_reg_276),
    .din1(ap_sig_allocacmp_max_logit_1_load_1),
    .opcode(5'd2),
    .dout(tmp_6_fu_89_p2)
);

graph_moe_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln243_fu_106_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            e_1_fu_54 <= add_ln243_fu_144_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            e_1_fu_54 <= 3'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            max_logit_1_fu_50 <= max_logit;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            max_logit_1_fu_50 <= max_logit_3_reg_283;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln243_reg_272 <= icmp_ln243_fu_106_p2;
        max_logit_2_reg_276 <= max_logit_2_fu_136_p3;
        max_logit_3_reg_283 <= max_logit_3_fu_242_p3;
    end
end

always @ (*) begin
    if (((icmp_ln243_fu_106_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_e = 3'd1;
    end else begin
        ap_sig_allocacmp_e = e_1_fu_54;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_sig_allocacmp_max_logit_1_load_1 = max_logit_3_reg_283;
    end else begin
        ap_sig_allocacmp_max_logit_1_load_1 = max_logit_1_fu_50;
    end
end

always @ (*) begin
    if (((icmp_ln243_reg_272 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        max_logit_1_out_ap_vld = 1'b1;
    end else begin
        max_logit_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln243_fu_144_p2 = (ap_sig_allocacmp_e + 3'd1);

assign and_ln245_1_fu_236_p2 = (or_ln245_1_fu_224_p2 & and_ln245_fu_230_p2);

assign and_ln245_fu_230_p2 = (tmp_6_fu_89_p2 & or_ln245_fu_206_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign bitcast_ln245_1_fu_176_p1 = ap_sig_allocacmp_max_logit_1_load_1;

assign bitcast_ln245_fu_159_p1 = max_logit_2_reg_276;

assign icmp_ln243_fu_106_p2 = ((ap_sig_allocacmp_e == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln245_1_fu_130_p2 = ((trunc_ln245_fu_112_p1 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln245_2_fu_194_p2 = ((tmp_fu_162_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln245_3_fu_200_p2 = ((trunc_ln245_1_fu_172_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln245_4_fu_212_p2 = ((tmp_5_fu_180_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln245_5_fu_218_p2 = ((trunc_ln245_2_fu_190_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln245_fu_116_p2 = ((trunc_ln245_fu_112_p1 == 2'd1) ? 1'b1 : 1'b0);

assign max_logit_1_out = max_logit_1_fu_50;

assign max_logit_2_fu_136_p3 = ((icmp_ln245_1_fu_130_p2[0:0] == 1'b1) ? max_logit_21954 : select_ln245_fu_122_p3);

assign max_logit_3_fu_242_p3 = ((and_ln245_1_fu_236_p2[0:0] == 1'b1) ? max_logit_2_reg_276 : ap_sig_allocacmp_max_logit_1_load_1);

assign or_ln245_1_fu_224_p2 = (icmp_ln245_5_fu_218_p2 | icmp_ln245_4_fu_212_p2);

assign or_ln245_fu_206_p2 = (icmp_ln245_3_fu_200_p2 | icmp_ln245_2_fu_194_p2);

assign select_ln245_fu_122_p3 = ((icmp_ln245_fu_116_p2[0:0] == 1'b1) ? max_logit_21850 : max_logit_22046);

assign tmp_5_fu_180_p4 = {{bitcast_ln245_1_fu_176_p1[30:23]}};

assign tmp_fu_162_p4 = {{bitcast_ln245_fu_159_p1[30:23]}};

assign trunc_ln245_1_fu_172_p1 = bitcast_ln245_fu_159_p1[22:0];

assign trunc_ln245_2_fu_190_p1 = bitcast_ln245_1_fu_176_p1[22:0];

assign trunc_ln245_fu_112_p1 = ap_sig_allocacmp_e[1:0];

endmodule //graph_moe_graph_moe_Pipeline_VITIS_LOOP_243_3
