// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pseudo_moe_pseudo_moe_Pipeline_VITIS_LOOP_121_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        exp_values_3_08,
        exp_values_2_07,
        exp_values_1_06,
        exp_values_0_05,
        logits_0_1_reload,
        logits_1_1_reload,
        logits_2_1_reload,
        logits_3_1_reload,
        max_logit_reload,
        exp_values_3_1_out,
        exp_values_3_1_out_ap_vld,
        exp_values_2_1_out,
        exp_values_2_1_out_ap_vld,
        exp_values_1_1_out,
        exp_values_1_1_out_ap_vld,
        exp_values_0_1_out,
        exp_values_0_1_out_ap_vld,
        exp_sum_out,
        exp_sum_out_ap_vld,
        grp_fu_1310_p_din0,
        grp_fu_1310_p_din1,
        grp_fu_1310_p_opcode,
        grp_fu_1310_p_dout0,
        grp_fu_1310_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] exp_values_3_08;
input  [31:0] exp_values_2_07;
input  [31:0] exp_values_1_06;
input  [31:0] exp_values_0_05;
input  [31:0] logits_0_1_reload;
input  [31:0] logits_1_1_reload;
input  [31:0] logits_2_1_reload;
input  [31:0] logits_3_1_reload;
input  [31:0] max_logit_reload;
output  [31:0] exp_values_3_1_out;
output   exp_values_3_1_out_ap_vld;
output  [31:0] exp_values_2_1_out;
output   exp_values_2_1_out_ap_vld;
output  [31:0] exp_values_1_1_out;
output   exp_values_1_1_out_ap_vld;
output  [31:0] exp_values_0_1_out;
output   exp_values_0_1_out_ap_vld;
output  [31:0] exp_sum_out;
output   exp_sum_out_ap_vld;
output  [31:0] grp_fu_1310_p_din0;
output  [31:0] grp_fu_1310_p_din1;
output  [0:0] grp_fu_1310_p_opcode;
input  [31:0] grp_fu_1310_p_dout0;
output   grp_fu_1310_p_ce;

reg ap_idle;
reg exp_values_3_1_out_ap_vld;
reg exp_values_2_1_out_ap_vld;
reg exp_values_1_1_out_ap_vld;
reg exp_values_0_1_out_ap_vld;
reg exp_sum_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln121_fu_228_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln121_reg_361;
reg   [0:0] icmp_ln121_reg_361_pp0_iter1_reg;
reg   [0:0] icmp_ln121_reg_361_pp0_iter2_reg;
reg   [0:0] icmp_ln121_reg_361_pp0_iter3_reg;
reg   [0:0] icmp_ln121_reg_361_pp0_iter4_reg;
reg   [0:0] icmp_ln121_reg_361_pp0_iter5_reg;
wire   [1:0] trunc_ln122_fu_240_p1;
reg   [1:0] trunc_ln122_reg_365;
reg   [1:0] trunc_ln122_reg_365_pp0_iter1_reg;
reg   [1:0] trunc_ln122_reg_365_pp0_iter2_reg;
reg   [1:0] trunc_ln122_reg_365_pp0_iter3_reg;
reg   [1:0] trunc_ln122_reg_365_pp0_iter4_reg;
wire   [31:0] tmp_fu_244_p6;
reg   [31:0] sub_reg_374;
wire   [31:0] grp_fu_190_p2;
reg   [31:0] exp_values_1_reg_379;
reg   [31:0] exp_sum_fu_68;
wire   [31:0] grp_fu_186_p2;
reg   [31:0] ap_sig_allocacmp_exp_sum_load;
wire    ap_block_pp0_stage0;
wire    ap_loop_init;
reg   [2:0] e_1_fu_72;
wire   [2:0] add_ln121_fu_234_p2;
reg   [2:0] ap_sig_allocacmp_e;
reg   [31:0] exp_values_0_1_fu_76;
reg   [31:0] exp_values_1_1_fu_80;
reg   [31:0] exp_values_2_1_fu_84;
reg   [31:0] exp_values_3_1_fu_88;
wire    ap_block_pp0_stage0_01001;
wire   [1:0] tmp_fu_244_p5;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 exp_sum_fu_68 = 32'd0;
#0 e_1_fu_72 = 3'd0;
#0 exp_values_0_1_fu_76 = 32'd0;
#0 exp_values_1_1_fu_80 = 32'd0;
#0 exp_values_2_1_fu_84 = 32'd0;
#0 exp_values_3_1_fu_88 = 32'd0;
#0 ap_done_reg = 1'b0;
end

pseudo_moe_fadd_32ns_32ns_32_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_2_full_dsp_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ap_sig_allocacmp_exp_sum_load),
    .din1(exp_values_1_reg_379),
    .ce(1'b1),
    .dout(grp_fu_186_p2)
);

pseudo_moe_fexp_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fexp_32ns_32ns_32_4_full_dsp_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(sub_reg_374),
    .ce(1'b1),
    .dout(grp_fu_190_p2)
);

pseudo_moe_mux_4_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_4_2_32_1_1_U23(
    .din0(logits_0_1_reload),
    .din1(logits_1_1_reload),
    .din2(logits_2_1_reload),
    .din3(logits_3_1_reload),
    .din4(tmp_fu_244_p5),
    .dout(tmp_fu_244_p6)
);

pseudo_moe_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln121_fu_228_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            e_1_fu_72 <= add_ln121_fu_234_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            e_1_fu_72 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            exp_sum_fu_68 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter7 == 1'b1)) begin
            exp_sum_fu_68 <= grp_fu_186_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            exp_values_0_1_fu_76 <= exp_values_0_05;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln122_reg_365_pp0_iter4_reg == 2'd0))) begin
            exp_values_0_1_fu_76 <= grp_fu_190_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            exp_values_1_1_fu_80 <= exp_values_1_06;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln122_reg_365_pp0_iter4_reg == 2'd1))) begin
            exp_values_1_1_fu_80 <= grp_fu_190_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            exp_values_2_1_fu_84 <= exp_values_2_07;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln122_reg_365_pp0_iter4_reg == 2'd2))) begin
            exp_values_2_1_fu_84 <= grp_fu_190_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            exp_values_3_1_fu_88 <= exp_values_3_08;
        end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln122_reg_365_pp0_iter4_reg == 2'd3))) begin
            exp_values_3_1_fu_88 <= grp_fu_190_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln121_reg_361 <= icmp_ln121_fu_228_p2;
        icmp_ln121_reg_361_pp0_iter1_reg <= icmp_ln121_reg_361;
        sub_reg_374 <= grp_fu_1310_p_dout0;
        trunc_ln122_reg_365 <= trunc_ln122_fu_240_p1;
        trunc_ln122_reg_365_pp0_iter1_reg <= trunc_ln122_reg_365;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        exp_values_1_reg_379 <= grp_fu_190_p2;
        icmp_ln121_reg_361_pp0_iter2_reg <= icmp_ln121_reg_361_pp0_iter1_reg;
        icmp_ln121_reg_361_pp0_iter3_reg <= icmp_ln121_reg_361_pp0_iter2_reg;
        icmp_ln121_reg_361_pp0_iter4_reg <= icmp_ln121_reg_361_pp0_iter3_reg;
        icmp_ln121_reg_361_pp0_iter5_reg <= icmp_ln121_reg_361_pp0_iter4_reg;
        trunc_ln122_reg_365_pp0_iter2_reg <= trunc_ln122_reg_365_pp0_iter1_reg;
        trunc_ln122_reg_365_pp0_iter3_reg <= trunc_ln122_reg_365_pp0_iter2_reg;
        trunc_ln122_reg_365_pp0_iter4_reg <= trunc_ln122_reg_365_pp0_iter3_reg;
    end
end

always @ (*) begin
    if (((icmp_ln121_fu_228_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_e = 3'd0;
    end else begin
        ap_sig_allocacmp_e = e_1_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_sig_allocacmp_exp_sum_load = grp_fu_186_p2;
    end else begin
        ap_sig_allocacmp_exp_sum_load = exp_sum_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln121_reg_361_pp0_iter5_reg == 1'd1))) begin
        exp_sum_out_ap_vld = 1'b1;
    end else begin
        exp_sum_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln121_reg_361_pp0_iter5_reg == 1'd1))) begin
        exp_values_0_1_out_ap_vld = 1'b1;
    end else begin
        exp_values_0_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln121_reg_361_pp0_iter5_reg == 1'd1))) begin
        exp_values_1_1_out_ap_vld = 1'b1;
    end else begin
        exp_values_1_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln121_reg_361_pp0_iter5_reg == 1'd1))) begin
        exp_values_2_1_out_ap_vld = 1'b1;
    end else begin
        exp_values_2_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln121_reg_361_pp0_iter5_reg == 1'd1))) begin
        exp_values_3_1_out_ap_vld = 1'b1;
    end else begin
        exp_values_3_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln121_fu_234_p2 = (ap_sig_allocacmp_e + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign exp_sum_out = exp_sum_fu_68;

assign exp_values_0_1_out = exp_values_0_1_fu_76;

assign exp_values_1_1_out = exp_values_1_1_fu_80;

assign exp_values_2_1_out = exp_values_2_1_fu_84;

assign exp_values_3_1_out = exp_values_3_1_fu_88;

assign grp_fu_1310_p_ce = 1'b1;

assign grp_fu_1310_p_din0 = tmp_fu_244_p6;

assign grp_fu_1310_p_din1 = max_logit_reload;

assign grp_fu_1310_p_opcode = 2'd1;

assign icmp_ln121_fu_228_p2 = ((ap_sig_allocacmp_e == 3'd4) ? 1'b1 : 1'b0);

assign tmp_fu_244_p5 = ap_sig_allocacmp_e[1:0];

assign trunc_ln122_fu_240_p1 = ap_sig_allocacmp_e[1:0];

endmodule //pseudo_moe_pseudo_moe_Pipeline_VITIS_LOOP_121_4
