-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_mlp_head482_Pipeline_VITIS_LOOP_586_3_p_ZL9e1_lut_w1_24_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_mlp_head482_Pipeline_VITIS_LOOP_586_3_p_ZL9e1_lut_w1_24_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101111110101101100111101100", 1 => "10111100101111000101100001111100", 2 => "10111100110000110100001010000001", 3 => "10111101100000101100110110000101", 
    4 => "00111110100101101100111100010000", 5 => "00111101101010011111010111000001", 6 => "10111101001011111011001101101001", 7 => "00111110010001001111110010010000", 
    8 => "10111100010001100000110100110011", 9 => "10111100001010101101110001101100", 10 => "00111101110011010011100000101011", 11 => "00111100001000110001111000001010", 
    12 => "10111011100011100101011011001111", 13 => "10111101000000011101110101001001", 14 => "10111011100010110101010010101001", 15 => "00111100100100010000001000111000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

