-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_mlp_head446_Pipeline_VITIS_LOOP_586_3_p_ZL9e0_lut_w1_2_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_mlp_head446_Pipeline_VITIS_LOOP_586_3_p_ZL9e0_lut_w1_2_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101100011111000001000110100", 1 => "10111010001010100100001110011010", 2 => "10111011101100001010010001100001", 3 => "00111100010100101101000011000001", 
    4 => "10111100111011000110101110110011", 5 => "10111011111101001001110011000001", 6 => "00111101011000001010001001001011", 7 => "00111100011100110010000001110110", 
    8 => "10111100111110110101001110011000", 9 => "00111011011110010001110010011001", 10 => "10111100001110101001100100011100", 11 => "00111100110100101011101100110100", 
    12 => "00111101000001100110001100011001", 13 => "00111001101010011111000001100001", 14 => "10111011011110011000100101100010", 15 => "10111100101001000100110010001101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

