// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="output_moe_output_moe,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu13p_CIV-figd2104-3-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.140000,HLS_SYN_LAT=94675,HLS_SYN_TPT=none,HLS_SYN_MEM=181,HLS_SYN_DSP=0,HLS_SYN_FF=52013,HLS_SYN_LUT=38935,HLS_VERSION=2023_2}" *)

module output_moe (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        output_0,
        output_0_ap_vld,
        output_1,
        output_1_ap_vld,
        output_2,
        output_2_ap_vld,
        output_3,
        output_3_ap_vld,
        output_4,
        output_4_ap_vld,
        gates_0_i,
        gates_0_o,
        gates_0_o_ap_vld,
        gates_1_i,
        gates_1_o,
        gates_1_o_ap_vld,
        gates_2_i,
        gates_2_o,
        gates_2_o_ap_vld,
        gates_3_i,
        gates_3_o,
        gates_3_o_ap_vld
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] input_r_address0;
output   input_r_ce0;
input  [31:0] input_r_q0;
output  [31:0] output_0;
output   output_0_ap_vld;
output  [31:0] output_1;
output   output_1_ap_vld;
output  [31:0] output_2;
output   output_2_ap_vld;
output  [31:0] output_3;
output   output_3_ap_vld;
output  [31:0] output_4;
output   output_4_ap_vld;
input  [31:0] gates_0_i;
output  [31:0] gates_0_o;
output   gates_0_o_ap_vld;
input  [31:0] gates_1_i;
output  [31:0] gates_1_o;
output   gates_1_o_ap_vld;
input  [31:0] gates_2_i;
output  [31:0] gates_2_o;
output   gates_2_o_ap_vld;
input  [31:0] gates_3_i;
output  [31:0] gates_3_o;
output   gates_3_o_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[6:0] input_r_address0;
reg input_r_ce0;
reg[31:0] gates_0_o;
reg gates_0_o_ap_vld;
reg[31:0] gates_1_o;
reg gates_1_o_ap_vld;
reg[31:0] gates_2_o;
reg gates_2_o_ap_vld;
reg[31:0] gates_3_o;
reg gates_3_o_ap_vld;

(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [1:0] trunc_ln1075_fu_4496_p1;
reg   [1:0] trunc_ln1075_reg_4710;
wire    ap_CS_fsm_state2;
wire   [2:0] add_ln1075_fu_4506_p2;
reg   [2:0] add_ln1075_reg_4717;
wire   [8:0] tmp_6_fu_4512_p3;
reg   [8:0] tmp_6_reg_4722;
wire   [31:0] acc_fu_4561_p3;
reg   [31:0] acc_reg_4727;
wire   [31:0] grp_fu_4483_p2;
reg   [31:0] inv_exp_sum_reg_4762;
wire    ap_CS_fsm_state13;
reg   [2:0] expert_output_address0;
reg    expert_output_ce0;
reg    expert_output_we0;
wire   [31:0] expert_output_q0;
reg   [2:0] expert_output_1_address0;
reg    expert_output_1_ce0;
reg    expert_output_1_we0;
wire   [31:0] expert_output_1_q0;
reg   [2:0] expert_output_2_address0;
reg    expert_output_2_ce0;
reg    expert_output_2_we0;
wire   [31:0] expert_output_2_q0;
reg   [2:0] expert_output_3_address0;
reg    expert_output_3_ce0;
reg    expert_output_3_we0;
wire   [31:0] expert_output_3_q0;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_ap_start;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_ap_done;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_ap_idle;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_ap_ready;
wire   [6:0] grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_input_r_address0;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_input_r_ce0;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_acc_1_out;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_acc_1_out_ap_vld;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_grp_fu_4779_p_din0;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_grp_fu_4779_p_din1;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_grp_fu_4779_p_ce;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_grp_fu_4783_p_din0;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_grp_fu_4783_p_din1;
wire   [0:0] grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_grp_fu_4783_p_opcode;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_grp_fu_4783_p_ce;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1092_3_fu_2287_ap_start;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1092_3_fu_2287_ap_done;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1092_3_fu_2287_ap_idle;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1092_3_fu_2287_ap_ready;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1092_3_fu_2287_max_logit_out;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1092_3_fu_2287_max_logit_out_ap_vld;
wire    grp_expert_engine_fu_2296_ap_start;
wire    grp_expert_engine_fu_2296_ap_done;
wire    grp_expert_engine_fu_2296_ap_idle;
wire    grp_expert_engine_fu_2296_ap_ready;
wire   [6:0] grp_expert_engine_fu_2296_input_r_address0;
wire    grp_expert_engine_fu_2296_input_r_ce0;
wire   [2:0] grp_expert_engine_fu_2296_expert_output_0_address0;
wire    grp_expert_engine_fu_2296_expert_output_0_ce0;
wire    grp_expert_engine_fu_2296_expert_output_0_we0;
wire   [31:0] grp_expert_engine_fu_2296_expert_output_0_d0;
wire   [2:0] grp_expert_engine_fu_2296_expert_output_1_address0;
wire    grp_expert_engine_fu_2296_expert_output_1_ce0;
wire    grp_expert_engine_fu_2296_expert_output_1_we0;
wire   [31:0] grp_expert_engine_fu_2296_expert_output_1_d0;
wire   [2:0] grp_expert_engine_fu_2296_expert_output_2_address0;
wire    grp_expert_engine_fu_2296_expert_output_2_ce0;
wire    grp_expert_engine_fu_2296_expert_output_2_we0;
wire   [31:0] grp_expert_engine_fu_2296_expert_output_2_d0;
wire   [2:0] grp_expert_engine_fu_2296_expert_output_3_address0;
wire    grp_expert_engine_fu_2296_expert_output_3_ce0;
wire    grp_expert_engine_fu_2296_expert_output_3_we0;
wire   [31:0] grp_expert_engine_fu_2296_expert_output_3_d0;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_ap_start;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_ap_done;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_ap_idle;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_ap_ready;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_0;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_0_ap_vld;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_3;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_3_ap_vld;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_2;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_2_ap_vld;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_1;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_1_ap_vld;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_exp_sum_out;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_exp_sum_out_ap_vld;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_grp_fu_4783_p_din0;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_grp_fu_4783_p_din1;
wire   [0:0] grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_grp_fu_4783_p_opcode;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_grp_fu_4783_p_ce;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_grp_fu_4787_p_din0;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_grp_fu_4787_p_din1;
wire   [1:0] grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_grp_fu_4787_p_opcode;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_grp_fu_4787_p_ce;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_ap_start;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_ap_done;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_ap_idle;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_ap_ready;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_0_o;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_0_o_ap_vld;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_3_o;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_3_o_ap_vld;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_2_o;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_2_o_ap_vld;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_1_o;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_1_o_ap_vld;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_mux_case_3927_phi_out;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_mux_case_3927_phi_out_ap_vld;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_mux_case_2824_phi_out;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_mux_case_2824_phi_out_ap_vld;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_mux_case_1721_phi_out;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_mux_case_1721_phi_out_ap_vld;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_mux_case_0518_phi_out;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_mux_case_0518_phi_out_ap_vld;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_grp_fu_4779_p_din0;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_grp_fu_4779_p_din1;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_grp_fu_4779_p_ce;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_ap_start;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_ap_done;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_ap_idle;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_ap_ready;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_0;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_0_ap_vld;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_4;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_4_ap_vld;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_3;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_3_ap_vld;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_2;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_2_ap_vld;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_1;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_1_ap_vld;
wire   [2:0] grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_expert_output_address0;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_expert_output_ce0;
wire   [2:0] grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_expert_output_1_address0;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_expert_output_1_ce0;
wire   [2:0] grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_expert_output_2_address0;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_expert_output_2_ce0;
wire   [2:0] grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_expert_output_3_address0;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_expert_output_3_ce0;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4783_p_din0;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4783_p_din1;
wire   [0:0] grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4783_p_opcode;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4783_p_ce;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4787_p_din0;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4787_p_din1;
wire   [1:0] grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4787_p_opcode;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4787_p_ce;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4779_p_din0;
wire   [31:0] grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4779_p_din1;
wire    grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4779_p_ce;
reg    grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_ap_start_reg;
wire   [0:0] icmp_ln1075_fu_4500_p2;
wire    ap_CS_fsm_state3;
reg    grp_output_moe_Pipeline_VITIS_LOOP_1092_3_fu_2287_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_expert_engine_fu_2296_ap_start_reg;
reg    grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg    grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_ap_start_reg;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
reg    grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_ap_start_reg;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
reg   [2:0] e_fu_2212;
wire    ap_CS_fsm_state4;
reg   [31:0] empty_fu_2216;
reg   [31:0] mux_case_11_fu_2220;
reg   [31:0] mux_case_25_fu_2224;
reg   [31:0] mux_case_310_fu_2228;
wire    ap_CS_fsm_state8;
wire   [0:0] icmp_ln9_fu_4521_p2;
wire   [0:0] icmp_ln9_2_fu_4541_p2;
wire   [0:0] icmp_ln9_1_fu_4535_p2;
wire   [0:0] empty_20_fu_4555_p2;
wire   [31:0] select_ln9_1_i_fu_4547_p3;
wire   [31:0] select_ln9_fu_4527_p3;
wire   [31:0] grp_fu_4779_p2;
reg   [31:0] grp_fu_4779_p0;
reg   [31:0] grp_fu_4779_p1;
reg    grp_fu_4779_ce;
wire   [31:0] grp_fu_4783_p2;
reg   [31:0] grp_fu_4783_p0;
reg   [31:0] grp_fu_4783_p1;
reg   [1:0] grp_fu_4783_opcode;
reg    grp_fu_4783_ce;
wire   [31:0] grp_fu_4787_p2;
reg   [31:0] grp_fu_4787_p0;
reg   [31:0] grp_fu_4787_p1;
reg    grp_fu_4787_ce;
reg   [16:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_block_state5_on_subcall_done;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
#0 grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_ap_start_reg = 1'b0;
#0 grp_output_moe_Pipeline_VITIS_LOOP_1092_3_fu_2287_ap_start_reg = 1'b0;
#0 grp_expert_engine_fu_2296_ap_start_reg = 1'b0;
#0 grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_ap_start_reg = 1'b0;
#0 grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_ap_start_reg = 1'b0;
#0 grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_ap_start_reg = 1'b0;
#0 e_fu_2212 = 3'd0;
#0 empty_fu_2216 = 32'd0;
#0 mux_case_11_fu_2220 = 32'd0;
#0 mux_case_25_fu_2224 = 32'd0;
#0 mux_case_310_fu_2228 = 32'd0;
end

output_moe_expert_output_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
expert_output_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(expert_output_address0),
    .ce0(expert_output_ce0),
    .we0(expert_output_we0),
    .d0(grp_expert_engine_fu_2296_expert_output_0_d0),
    .q0(expert_output_q0)
);

output_moe_expert_output_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
expert_output_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(expert_output_1_address0),
    .ce0(expert_output_1_ce0),
    .we0(expert_output_1_we0),
    .d0(grp_expert_engine_fu_2296_expert_output_1_d0),
    .q0(expert_output_1_q0)
);

output_moe_expert_output_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
expert_output_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(expert_output_2_address0),
    .ce0(expert_output_2_ce0),
    .we0(expert_output_2_we0),
    .d0(grp_expert_engine_fu_2296_expert_output_2_d0),
    .q0(expert_output_2_q0)
);

output_moe_expert_output_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
expert_output_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(expert_output_3_address0),
    .ce0(expert_output_3_ce0),
    .we0(expert_output_3_we0),
    .d0(grp_expert_engine_fu_2296_expert_output_3_d0),
    .q0(expert_output_3_q0)
);

output_moe_output_moe_Pipeline_VITIS_LOOP_1079_2 grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_ap_start),
    .ap_done(grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_ap_done),
    .ap_idle(grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_ap_idle),
    .ap_ready(grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_ap_ready),
    .acc(acc_reg_4727),
    .zext_ln1080(tmp_6_reg_4722),
    .input_r_address0(grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_input_r_address0),
    .input_r_ce0(grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_input_r_ce0),
    .input_r_q0(input_r_q0),
    .acc_1_out(grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_acc_1_out),
    .acc_1_out_ap_vld(grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_acc_1_out_ap_vld),
    .grp_fu_4779_p_din0(grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_grp_fu_4779_p_din0),
    .grp_fu_4779_p_din1(grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_grp_fu_4779_p_din1),
    .grp_fu_4779_p_dout0(grp_fu_4779_p2),
    .grp_fu_4779_p_ce(grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_grp_fu_4779_p_ce),
    .grp_fu_4783_p_din0(grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_grp_fu_4783_p_din0),
    .grp_fu_4783_p_din1(grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_grp_fu_4783_p_din1),
    .grp_fu_4783_p_opcode(grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_grp_fu_4783_p_opcode),
    .grp_fu_4783_p_dout0(grp_fu_4783_p2),
    .grp_fu_4783_p_ce(grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_grp_fu_4783_p_ce)
);

output_moe_output_moe_Pipeline_VITIS_LOOP_1092_3 grp_output_moe_Pipeline_VITIS_LOOP_1092_3_fu_2287(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_output_moe_Pipeline_VITIS_LOOP_1092_3_fu_2287_ap_start),
    .ap_done(grp_output_moe_Pipeline_VITIS_LOOP_1092_3_fu_2287_ap_done),
    .ap_idle(grp_output_moe_Pipeline_VITIS_LOOP_1092_3_fu_2287_ap_idle),
    .ap_ready(grp_output_moe_Pipeline_VITIS_LOOP_1092_3_fu_2287_ap_ready),
    .empty(empty_fu_2216),
    .mux_case_11(mux_case_11_fu_2220),
    .mux_case_25(mux_case_25_fu_2224),
    .mux_case_310(mux_case_310_fu_2228),
    .max_logit_out(grp_output_moe_Pipeline_VITIS_LOOP_1092_3_fu_2287_max_logit_out),
    .max_logit_out_ap_vld(grp_output_moe_Pipeline_VITIS_LOOP_1092_3_fu_2287_max_logit_out_ap_vld)
);

output_moe_expert_engine grp_expert_engine_fu_2296(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_expert_engine_fu_2296_ap_start),
    .ap_done(grp_expert_engine_fu_2296_ap_done),
    .ap_idle(grp_expert_engine_fu_2296_ap_idle),
    .ap_ready(grp_expert_engine_fu_2296_ap_ready),
    .input_r_address0(grp_expert_engine_fu_2296_input_r_address0),
    .input_r_ce0(grp_expert_engine_fu_2296_input_r_ce0),
    .input_r_q0(input_r_q0),
    .expert_output_0_address0(grp_expert_engine_fu_2296_expert_output_0_address0),
    .expert_output_0_ce0(grp_expert_engine_fu_2296_expert_output_0_ce0),
    .expert_output_0_we0(grp_expert_engine_fu_2296_expert_output_0_we0),
    .expert_output_0_d0(grp_expert_engine_fu_2296_expert_output_0_d0),
    .expert_output_1_address0(grp_expert_engine_fu_2296_expert_output_1_address0),
    .expert_output_1_ce0(grp_expert_engine_fu_2296_expert_output_1_ce0),
    .expert_output_1_we0(grp_expert_engine_fu_2296_expert_output_1_we0),
    .expert_output_1_d0(grp_expert_engine_fu_2296_expert_output_1_d0),
    .expert_output_2_address0(grp_expert_engine_fu_2296_expert_output_2_address0),
    .expert_output_2_ce0(grp_expert_engine_fu_2296_expert_output_2_ce0),
    .expert_output_2_we0(grp_expert_engine_fu_2296_expert_output_2_we0),
    .expert_output_2_d0(grp_expert_engine_fu_2296_expert_output_2_d0),
    .expert_output_3_address0(grp_expert_engine_fu_2296_expert_output_3_address0),
    .expert_output_3_ce0(grp_expert_engine_fu_2296_expert_output_3_ce0),
    .expert_output_3_we0(grp_expert_engine_fu_2296_expert_output_3_we0),
    .expert_output_3_d0(grp_expert_engine_fu_2296_expert_output_3_d0)
);

output_moe_output_moe_Pipeline_VITIS_LOOP_1099_4 grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_ap_start),
    .ap_done(grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_ap_done),
    .ap_idle(grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_ap_idle),
    .ap_ready(grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_ap_ready),
    .gates_0(grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_0),
    .gates_0_ap_vld(grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_0_ap_vld),
    .gates_3(grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_3),
    .gates_3_ap_vld(grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_3_ap_vld),
    .gates_2(grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_2),
    .gates_2_ap_vld(grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_2_ap_vld),
    .gates_1(grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_1),
    .gates_1_ap_vld(grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_1_ap_vld),
    .empty(empty_fu_2216),
    .mux_case_11(mux_case_11_fu_2220),
    .mux_case_25(mux_case_25_fu_2224),
    .mux_case_310(mux_case_310_fu_2228),
    .max_logit_reload(grp_output_moe_Pipeline_VITIS_LOOP_1092_3_fu_2287_max_logit_out),
    .exp_sum_out(grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_exp_sum_out),
    .exp_sum_out_ap_vld(grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_exp_sum_out_ap_vld),
    .grp_fu_4783_p_din0(grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_grp_fu_4783_p_din0),
    .grp_fu_4783_p_din1(grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_grp_fu_4783_p_din1),
    .grp_fu_4783_p_opcode(grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_grp_fu_4783_p_opcode),
    .grp_fu_4783_p_dout0(grp_fu_4783_p2),
    .grp_fu_4783_p_ce(grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_grp_fu_4783_p_ce),
    .grp_fu_4787_p_din0(grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_grp_fu_4787_p_din0),
    .grp_fu_4787_p_din1(grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_grp_fu_4787_p_din1),
    .grp_fu_4787_p_opcode(grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_grp_fu_4787_p_opcode),
    .grp_fu_4787_p_dout0(grp_fu_4787_p2),
    .grp_fu_4787_p_ce(grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_grp_fu_4787_p_ce)
);

output_moe_output_moe_Pipeline_VITIS_LOOP_1108_5 grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_ap_start),
    .ap_done(grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_ap_done),
    .ap_idle(grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_ap_idle),
    .ap_ready(grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_ap_ready),
    .gates_0_i(gates_0_i),
    .gates_0_o(grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_0_o),
    .gates_0_o_ap_vld(grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_0_o_ap_vld),
    .gates_3_i(gates_3_i),
    .gates_3_o(grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_3_o),
    .gates_3_o_ap_vld(grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_3_o_ap_vld),
    .gates_2_i(gates_2_i),
    .gates_2_o(grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_2_o),
    .gates_2_o_ap_vld(grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_2_o_ap_vld),
    .gates_1_i(gates_1_i),
    .gates_1_o(grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_1_o),
    .gates_1_o_ap_vld(grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_1_o_ap_vld),
    .inv_exp_sum(inv_exp_sum_reg_4762),
    .mux_case_3927_phi_out(grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_mux_case_3927_phi_out),
    .mux_case_3927_phi_out_ap_vld(grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_mux_case_3927_phi_out_ap_vld),
    .mux_case_2824_phi_out(grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_mux_case_2824_phi_out),
    .mux_case_2824_phi_out_ap_vld(grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_mux_case_2824_phi_out_ap_vld),
    .mux_case_1721_phi_out(grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_mux_case_1721_phi_out),
    .mux_case_1721_phi_out_ap_vld(grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_mux_case_1721_phi_out_ap_vld),
    .mux_case_0518_phi_out(grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_mux_case_0518_phi_out),
    .mux_case_0518_phi_out_ap_vld(grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_mux_case_0518_phi_out_ap_vld),
    .grp_fu_4779_p_din0(grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_grp_fu_4779_p_din0),
    .grp_fu_4779_p_din1(grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_grp_fu_4779_p_din1),
    .grp_fu_4779_p_dout0(grp_fu_4779_p2),
    .grp_fu_4779_p_ce(grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_grp_fu_4779_p_ce)
);

output_moe_output_moe_Pipeline_VITIS_LOOP_1122_6 grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_ap_start),
    .ap_done(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_ap_done),
    .ap_idle(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_ap_idle),
    .ap_ready(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_ap_ready),
    .output_0(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_0),
    .output_0_ap_vld(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_0_ap_vld),
    .output_4(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_4),
    .output_4_ap_vld(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_4_ap_vld),
    .output_3(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_3),
    .output_3_ap_vld(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_3_ap_vld),
    .output_2(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_2),
    .output_2_ap_vld(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_2_ap_vld),
    .output_1(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_1),
    .output_1_ap_vld(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_1_ap_vld),
    .expert_output_address0(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_expert_output_address0),
    .expert_output_ce0(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_expert_output_ce0),
    .expert_output_q0(expert_output_q0),
    .expert_output_1_address0(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_expert_output_1_address0),
    .expert_output_1_ce0(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_expert_output_1_ce0),
    .expert_output_1_q0(expert_output_1_q0),
    .expert_output_2_address0(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_expert_output_2_address0),
    .expert_output_2_ce0(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_expert_output_2_ce0),
    .expert_output_2_q0(expert_output_2_q0),
    .expert_output_3_address0(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_expert_output_3_address0),
    .expert_output_3_ce0(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_expert_output_3_ce0),
    .expert_output_3_q0(expert_output_3_q0),
    .mux_case_0518_phi_reload(grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_mux_case_0518_phi_out),
    .mux_case_1721_phi_reload(grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_mux_case_1721_phi_out),
    .mux_case_2824_phi_reload(grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_mux_case_2824_phi_out),
    .mux_case_3927_phi_reload(grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_mux_case_3927_phi_out),
    .grp_fu_4783_p_din0(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4783_p_din0),
    .grp_fu_4783_p_din1(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4783_p_din1),
    .grp_fu_4783_p_opcode(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4783_p_opcode),
    .grp_fu_4783_p_dout0(grp_fu_4783_p2),
    .grp_fu_4783_p_ce(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4783_p_ce),
    .grp_fu_4787_p_din0(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4787_p_din0),
    .grp_fu_4787_p_din1(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4787_p_din1),
    .grp_fu_4787_p_opcode(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4787_p_opcode),
    .grp_fu_4787_p_dout0(grp_fu_4787_p2),
    .grp_fu_4787_p_ce(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4787_p_ce),
    .grp_fu_4779_p_din0(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4779_p_din0),
    .grp_fu_4779_p_din1(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4779_p_din1),
    .grp_fu_4779_p_dout0(grp_fu_4779_p2),
    .grp_fu_4779_p_ce(grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4779_p_ce)
);

output_moe_fdiv_32ns_32ns_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_6_no_dsp_1_U1466(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd1065353216),
    .din1(grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_exp_sum_out),
    .ce(1'b1),
    .dout(grp_fu_4483_p2)
);

output_moe_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U1467(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_4779_p0),
    .din1(grp_fu_4779_p1),
    .ce(grp_fu_4779_ce),
    .dout(grp_fu_4779_p2)
);

output_moe_faddfsub_32ns_32ns_32_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
faddfsub_32ns_32ns_32_2_full_dsp_1_U1468(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_4783_p0),
    .din1(grp_fu_4783_p1),
    .opcode(grp_fu_4783_opcode),
    .ce(grp_fu_4783_ce),
    .dout(grp_fu_4783_p2)
);

output_moe_fadd_32ns_32ns_32_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_2_full_dsp_1_U1469(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_4787_p0),
    .din1(grp_fu_4787_p1),
    .ce(grp_fu_4787_ce),
    .dout(grp_fu_4787_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_expert_engine_fu_2296_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln1075_fu_4500_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_expert_engine_fu_2296_ap_start_reg <= 1'b1;
        end else if ((grp_expert_engine_fu_2296_ap_ready == 1'b1)) begin
            grp_expert_engine_fu_2296_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln1075_fu_4500_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_ap_start_reg <= 1'b1;
        end else if ((grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_ap_ready == 1'b1)) begin
            grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_output_moe_Pipeline_VITIS_LOOP_1092_3_fu_2287_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln1075_fu_4500_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_output_moe_Pipeline_VITIS_LOOP_1092_3_fu_2287_ap_start_reg <= 1'b1;
        end else if ((grp_output_moe_Pipeline_VITIS_LOOP_1092_3_fu_2287_ap_ready == 1'b1)) begin
            grp_output_moe_Pipeline_VITIS_LOOP_1092_3_fu_2287_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_ap_start_reg <= 1'b1;
        end else if ((grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_ap_ready == 1'b1)) begin
            grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_ap_start_reg <= 1'b1;
        end else if ((grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_ap_ready == 1'b1)) begin
            grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_ap_start_reg <= 1'b1;
        end else if ((grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_ap_ready == 1'b1)) begin
            grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        e_fu_2212 <= 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        e_fu_2212 <= add_ln1075_reg_4717;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        acc_reg_4727[1 : 0] <= acc_fu_4561_p3[1 : 0];
acc_reg_4727[6 : 3] <= acc_fu_4561_p3[6 : 3];
acc_reg_4727[11 : 8] <= acc_fu_4561_p3[11 : 8];
acc_reg_4727[24 : 13] <= acc_fu_4561_p3[24 : 13];
        add_ln1075_reg_4717 <= add_ln1075_fu_4506_p2;
        tmp_6_reg_4722[8 : 7] <= tmp_6_fu_4512_p3[8 : 7];
        trunc_ln1075_reg_4710 <= trunc_ln1075_fu_4496_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln1075_reg_4710 == 2'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        empty_fu_2216 <= grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_acc_1_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        inv_exp_sum_reg_4762 <= grp_fu_4483_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln1075_reg_4710 == 2'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        mux_case_11_fu_2220 <= grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_acc_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln1075_reg_4710 == 2'd2) & (1'b1 == ap_CS_fsm_state4))) begin
        mux_case_25_fu_2224 <= grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_acc_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln1075_reg_4710 == 2'd3) & (1'b1 == ap_CS_fsm_state4))) begin
        mux_case_310_fu_2228 <= grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_acc_1_out;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_ap_done == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state5_on_subcall_done)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        expert_output_1_address0 = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_expert_output_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        expert_output_1_address0 = grp_expert_engine_fu_2296_expert_output_1_address0;
    end else begin
        expert_output_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        expert_output_1_ce0 = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_expert_output_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        expert_output_1_ce0 = grp_expert_engine_fu_2296_expert_output_1_ce0;
    end else begin
        expert_output_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        expert_output_1_we0 = grp_expert_engine_fu_2296_expert_output_1_we0;
    end else begin
        expert_output_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        expert_output_2_address0 = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_expert_output_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        expert_output_2_address0 = grp_expert_engine_fu_2296_expert_output_2_address0;
    end else begin
        expert_output_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        expert_output_2_ce0 = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_expert_output_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        expert_output_2_ce0 = grp_expert_engine_fu_2296_expert_output_2_ce0;
    end else begin
        expert_output_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        expert_output_2_we0 = grp_expert_engine_fu_2296_expert_output_2_we0;
    end else begin
        expert_output_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        expert_output_3_address0 = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_expert_output_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        expert_output_3_address0 = grp_expert_engine_fu_2296_expert_output_3_address0;
    end else begin
        expert_output_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        expert_output_3_ce0 = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_expert_output_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        expert_output_3_ce0 = grp_expert_engine_fu_2296_expert_output_3_ce0;
    end else begin
        expert_output_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        expert_output_3_we0 = grp_expert_engine_fu_2296_expert_output_3_we0;
    end else begin
        expert_output_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        expert_output_address0 = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_expert_output_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        expert_output_address0 = grp_expert_engine_fu_2296_expert_output_0_address0;
    end else begin
        expert_output_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        expert_output_ce0 = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_expert_output_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        expert_output_ce0 = grp_expert_engine_fu_2296_expert_output_0_ce0;
    end else begin
        expert_output_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        expert_output_we0 = grp_expert_engine_fu_2296_expert_output_0_we0;
    end else begin
        expert_output_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        gates_0_o = grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_0_o;
    end else if (((1'b1 == ap_CS_fsm_state7) & (grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_0_ap_vld == 1'b1))) begin
        gates_0_o = grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_0;
    end else begin
        gates_0_o = gates_0_i;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        gates_0_o_ap_vld = grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_0_o_ap_vld;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        gates_0_o_ap_vld = grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_0_ap_vld;
    end else begin
        gates_0_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        gates_1_o = grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_1_o;
    end else if (((grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        gates_1_o = grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_1;
    end else begin
        gates_1_o = gates_1_i;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        gates_1_o_ap_vld = grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_1_o_ap_vld;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        gates_1_o_ap_vld = grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_1_ap_vld;
    end else begin
        gates_1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        gates_2_o = grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_2_o;
    end else if (((grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        gates_2_o = grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_2;
    end else begin
        gates_2_o = gates_2_i;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        gates_2_o_ap_vld = grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_2_o_ap_vld;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        gates_2_o_ap_vld = grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_2_ap_vld;
    end else begin
        gates_2_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        gates_3_o = grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_3_o;
    end else if (((1'b1 == ap_CS_fsm_state7) & (grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_3_ap_vld == 1'b1))) begin
        gates_3_o = grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_3;
    end else begin
        gates_3_o = gates_3_i;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        gates_3_o_ap_vld = grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_gates_3_o_ap_vld;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        gates_3_o_ap_vld = grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_gates_3_ap_vld;
    end else begin
        gates_3_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_4779_ce = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4779_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_4779_ce = grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_grp_fu_4779_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_4779_ce = grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_grp_fu_4779_p_ce;
    end else begin
        grp_fu_4779_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_4779_p0 = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4779_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_4779_p0 = grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_grp_fu_4779_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_4779_p0 = grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_grp_fu_4779_p_din0;
    end else begin
        grp_fu_4779_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_4779_p1 = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4779_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_4779_p1 = grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_grp_fu_4779_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_4779_p1 = grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_grp_fu_4779_p_din1;
    end else begin
        grp_fu_4779_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_4783_ce = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4783_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_4783_ce = grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_grp_fu_4783_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_4783_ce = grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_grp_fu_4783_p_ce;
    end else begin
        grp_fu_4783_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_4783_opcode = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4783_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_4783_opcode = grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_grp_fu_4783_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_4783_opcode = grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_grp_fu_4783_p_opcode;
    end else begin
        grp_fu_4783_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_4783_p0 = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4783_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_4783_p0 = grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_grp_fu_4783_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_4783_p0 = grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_grp_fu_4783_p_din0;
    end else begin
        grp_fu_4783_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_4783_p1 = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4783_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_4783_p1 = grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_grp_fu_4783_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_4783_p1 = grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_grp_fu_4783_p_din1;
    end else begin
        grp_fu_4783_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_4787_ce = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4787_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_4787_ce = grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_grp_fu_4787_p_ce;
    end else begin
        grp_fu_4787_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_4787_p0 = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4787_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_4787_p0 = grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_grp_fu_4787_p_din0;
    end else begin
        grp_fu_4787_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_4787_p1 = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_grp_fu_4787_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_4787_p1 = grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_grp_fu_4787_p_din1;
    end else begin
        grp_fu_4787_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_r_address0 = grp_expert_engine_fu_2296_input_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_r_address0 = grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_input_r_address0;
    end else begin
        input_r_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_r_ce0 = grp_expert_engine_fu_2296_input_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_r_ce0 = grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_input_r_ce0;
    end else begin
        input_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln1075_fu_4500_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_fu_4561_p3 = ((empty_20_fu_4555_p2[0:0] == 1'b1) ? select_ln9_1_i_fu_4547_p3 : select_ln9_fu_4527_p3);

assign add_ln1075_fu_4506_p2 = (e_fu_2212 + 3'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_block_state5_on_subcall_done = ((grp_expert_engine_fu_2296_ap_done == 1'b0) | (grp_output_moe_Pipeline_VITIS_LOOP_1092_3_fu_2287_ap_done == 1'b0));
end

assign empty_20_fu_4555_p2 = (icmp_ln9_2_fu_4541_p2 | icmp_ln9_1_fu_4535_p2);

assign grp_expert_engine_fu_2296_ap_start = grp_expert_engine_fu_2296_ap_start_reg;

assign grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_ap_start = grp_output_moe_Pipeline_VITIS_LOOP_1079_2_fu_2276_ap_start_reg;

assign grp_output_moe_Pipeline_VITIS_LOOP_1092_3_fu_2287_ap_start = grp_output_moe_Pipeline_VITIS_LOOP_1092_3_fu_2287_ap_start_reg;

assign grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_ap_start = grp_output_moe_Pipeline_VITIS_LOOP_1099_4_fu_4426_ap_start_reg;

assign grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_ap_start = grp_output_moe_Pipeline_VITIS_LOOP_1108_5_fu_4444_ap_start_reg;

assign grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_ap_start = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_ap_start_reg;

assign icmp_ln1075_fu_4500_p2 = ((e_fu_2212 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln9_1_fu_4535_p2 = ((trunc_ln1075_fu_4496_p1 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln9_2_fu_4541_p2 = ((trunc_ln1075_fu_4496_p1 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_4521_p2 = ((trunc_ln1075_fu_4496_p1 == 2'd0) ? 1'b1 : 1'b0);

assign output_0 = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_0;

assign output_0_ap_vld = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_0_ap_vld;

assign output_1 = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_1;

assign output_1_ap_vld = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_1_ap_vld;

assign output_2 = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_2;

assign output_2_ap_vld = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_2_ap_vld;

assign output_3 = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_3;

assign output_3_ap_vld = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_3_ap_vld;

assign output_4 = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_4;

assign output_4_ap_vld = grp_output_moe_Pipeline_VITIS_LOOP_1122_6_fu_4461_output_4_ap_vld;

assign select_ln9_1_i_fu_4547_p3 = ((icmp_ln9_2_fu_4541_p2[0:0] == 1'b1) ? 32'd3176596864 : 32'd3175738019);

assign select_ln9_fu_4527_p3 = ((icmp_ln9_fu_4521_p2[0:0] == 1'b1) ? 32'd3181912217 : 32'd3155545537);

assign tmp_6_fu_4512_p3 = {{trunc_ln1075_fu_4496_p1}, {7'd0}};

assign trunc_ln1075_fu_4496_p1 = e_fu_2212[1:0];

always @ (posedge ap_clk) begin
    tmp_6_reg_4722[6:0] <= 7'b0000000;
    acc_reg_4727[2] <= 1'b0;
    acc_reg_4727[7:7] <= 1'b1;
    acc_reg_4727[12:12] <= 1'b0;
    acc_reg_4727[31:25] <= 7'b1011110;
end

endmodule //output_moe
