-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_generic_mlp_head37_Pipeline_VITIS_LOOP_736_3_p_ZL9e2_dsp_w1_28_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_generic_mlp_head37_Pipeline_VITIS_LOOP_736_3_p_ZL9e2_dsp_w1_28_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101000001001100010111011000", 1 => "00111101100011100110010011000001", 2 => "10111101010011001000100100110001", 3 => "00111101001101001111010101011101", 
    4 => "10111110001110001011001011110000", 5 => "10111110100101000110100110101100", 6 => "00111101111111110110100001100010", 7 => "00111101100000110011100111010101", 
    8 => "00111101011000000110011001101000", 9 => "00111110100011110100110110010111", 10 => "00111101110010001101000011100001", 11 => "10111100101100100001001000000011", 
    12 => "00111110000111010111001010001100", 13 => "00111110110000000100100110010110", 14 => "10111100100000111110011100101110", 15 => "10111100110001000100000100101001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

