-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_generic_mlp_head38_Pipeline_VITIS_LOOP_736_3_p_ZL10e2_bram_w1_10_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_generic_mlp_head38_Pipeline_VITIS_LOOP_736_3_p_ZL10e2_bram_w1_10_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10110111001010010001010010100100", 1 => "10111001100000111011000010111110", 2 => "00111001111001010010001001111010", 3 => "00110111000011011001000101110000", 
    4 => "10111001110100011011011111111110", 5 => "10111001111000011011101111011100", 6 => "00111011000011010110101010001000", 7 => "10111000110001110011001001011011", 
    8 => "00111011100010011100110010110001", 9 => "10111010000010001110110010001001", 10 => "00110111000101011111100011010000", 11 => "00111000101100010110000010111001", 
    12 => "10110011011001101110111111100000", 13 => "00111010000010011010101100111000", 14 => "00111010111000011100111111011010", 15 => "00110111011101000011110110001000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

