-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_generic_mlp_head29_Pipeline_VITIS_LOOP_736_3_p_ZL10e0_perf_w1_16_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_generic_mlp_head29_Pipeline_VITIS_LOOP_736_3_p_ZL10e0_perf_w1_16_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101010100101001000000101111", 1 => "10111100011101101100111011001111", 2 => "10111110100111101101100111010011", 3 => "00111110000001101101100100000101", 
    4 => "10111101111010101110010010110011", 5 => "00111101001100000111011001000000", 6 => "00111100110000100100010110000011", 7 => "10111110000000011000110011100111", 
    8 => "00111100011010000000111011101100", 9 => "10111100100001110011010010010001", 10 => "00111101111011001101110011000111", 11 => "00111100110101011010001011011010", 
    12 => "00111101000111001101010011001101", 13 => "00111110011010111010001111101101", 14 => "10111110010000011101100010011010", 15 => "00111110101101011111010100101001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

