-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_generic_mlp_head41_Pipeline_VITIS_LOOP_736_3_p_ZL8e1_ff_w1_28_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_generic_mlp_head41_Pipeline_VITIS_LOOP_736_3_p_ZL8e1_ff_w1_28_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111100111011010111100011010101", 1 => "10111011111100100011001001101111", 2 => "00111100001001011011000111001101", 3 => "10111001110010000101110010000111", 
    4 => "10111011001001001011010001000001", 5 => "00111010101001111100111011010110", 6 => "10111010011110000101110001100010", 7 => "00111011100101100011011110110100", 
    8 => "10111001111000000110010111000011", 9 => "00111011000010100010100010011011", 10 => "00111100101110000000010011001001", 11 => "10111000010110001100000100011111", 
    12 => "00111100101010011010001001000100", 13 => "10111000010101111101011111011000", 14 => "10111001101111011001101001101000", 15 => "10111011110101110011100010100100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

