-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_generic_mlp_head32_Pipeline_VITIS_LOOP_736_3_p_ZL9e0_dsp_w1_12_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_generic_mlp_head32_Pipeline_VITIS_LOOP_736_3_p_ZL9e0_dsp_w1_12_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111100011000000000001101001000", 1 => "00111011110101110101010101011001", 2 => "10111011111000011011000101000100", 3 => "00111100011000100100111001100101", 
    4 => "10111100011101001110100100011101", 5 => "10111011000000110100110110010101", 6 => "00111011010101011111110110100010", 7 => "00111001000001001110111101000101", 
    8 => "00111100001010100101101100010011", 9 => "00111100000100011110100011010010", 10 => "00111011001010001101100110110100", 11 => "10111100000001101000110010101000", 
    12 => "00111011011000001111000110101011", 13 => "00111100110000001010011111011010", 14 => "00111011101101001110100011010110", 15 => "00111100001010011000010000001101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

