-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_generic_mlp_head33_Pipeline_VITIS_LOOP_736_3_p_ZL10e0_bram_w1_14_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_generic_mlp_head33_Pipeline_VITIS_LOOP_736_3_p_ZL10e0_bram_w1_14_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00110101110000001000101111111001", 1 => "10101111001011111100110011111011", 2 => "00101111011001101011100110101010", 3 => "00110101011110101011111101111100", 
    4 => "00110110111011001011111010101111", 5 => "10101100110111111101010011101101", 6 => "10011100101100110101111011001110", 7 => "00111000101001000110111110011111", 
    8 => "10111001111000111001101111101001", 9 => "00110111000001111110101110010001", 10 => "10110011111001010011011010100000", 11 => "10100111001101110111001111011010", 
    12 => "00101010111000110000101111110000", 13 => "10111001111111001011101101011011", 14 => "00111001000111101100110100110000", 15 => "00110111000000100110010101001011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

