// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module pseudo_moe_compute_expert_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_29_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem4_AWVALID,
        m_axi_gmem4_AWREADY,
        m_axi_gmem4_AWADDR,
        m_axi_gmem4_AWID,
        m_axi_gmem4_AWLEN,
        m_axi_gmem4_AWSIZE,
        m_axi_gmem4_AWBURST,
        m_axi_gmem4_AWLOCK,
        m_axi_gmem4_AWCACHE,
        m_axi_gmem4_AWPROT,
        m_axi_gmem4_AWQOS,
        m_axi_gmem4_AWREGION,
        m_axi_gmem4_AWUSER,
        m_axi_gmem4_WVALID,
        m_axi_gmem4_WREADY,
        m_axi_gmem4_WDATA,
        m_axi_gmem4_WSTRB,
        m_axi_gmem4_WLAST,
        m_axi_gmem4_WID,
        m_axi_gmem4_WUSER,
        m_axi_gmem4_ARVALID,
        m_axi_gmem4_ARREADY,
        m_axi_gmem4_ARADDR,
        m_axi_gmem4_ARID,
        m_axi_gmem4_ARLEN,
        m_axi_gmem4_ARSIZE,
        m_axi_gmem4_ARBURST,
        m_axi_gmem4_ARLOCK,
        m_axi_gmem4_ARCACHE,
        m_axi_gmem4_ARPROT,
        m_axi_gmem4_ARQOS,
        m_axi_gmem4_ARREGION,
        m_axi_gmem4_ARUSER,
        m_axi_gmem4_RVALID,
        m_axi_gmem4_RREADY,
        m_axi_gmem4_RDATA,
        m_axi_gmem4_RLAST,
        m_axi_gmem4_RID,
        m_axi_gmem4_RFIFONUM,
        m_axi_gmem4_RUSER,
        m_axi_gmem4_RRESP,
        m_axi_gmem4_BVALID,
        m_axi_gmem4_BREADY,
        m_axi_gmem4_BRESP,
        m_axi_gmem4_BID,
        m_axi_gmem4_BUSER,
        sext_ln19,
        zext_ln35_8,
        x_0_address0,
        x_0_ce0,
        x_0_q0,
        zext_ln35_7,
        x_1_address0,
        x_1_ce0,
        x_1_q0,
        zext_ln35_6,
        x_2_address0,
        x_2_ce0,
        x_2_q0,
        zext_ln35_5,
        x_3_address0,
        x_3_ce0,
        x_3_q0,
        zext_ln35_4,
        x_4_address0,
        x_4_ce0,
        x_4_q0,
        zext_ln35_3,
        x_5_address0,
        x_5_ce0,
        x_5_q0,
        zext_ln35_2,
        x_6_address0,
        x_6_ce0,
        x_6_q0,
        zext_ln35_1,
        x_7_address0,
        x_7_ce0,
        x_7_q0,
        w_0_address0,
        w_0_ce0,
        w_0_q0,
        w_1_address0,
        w_1_ce0,
        w_1_q0,
        w_2_address0,
        w_2_ce0,
        w_2_q0,
        w_3_address0,
        w_3_ce0,
        w_3_q0,
        w_4_address0,
        w_4_ce0,
        w_4_q0,
        w_5_address0,
        w_5_ce0,
        w_5_q0,
        w_6_address0,
        w_6_ce0,
        w_6_q0,
        w_7_address0,
        w_7_ce0,
        w_7_q0,
        result_address0,
        result_ce0,
        result_we0,
        result_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem4_AWVALID;
input   m_axi_gmem4_AWREADY;
output  [63:0] m_axi_gmem4_AWADDR;
output  [0:0] m_axi_gmem4_AWID;
output  [31:0] m_axi_gmem4_AWLEN;
output  [2:0] m_axi_gmem4_AWSIZE;
output  [1:0] m_axi_gmem4_AWBURST;
output  [1:0] m_axi_gmem4_AWLOCK;
output  [3:0] m_axi_gmem4_AWCACHE;
output  [2:0] m_axi_gmem4_AWPROT;
output  [3:0] m_axi_gmem4_AWQOS;
output  [3:0] m_axi_gmem4_AWREGION;
output  [0:0] m_axi_gmem4_AWUSER;
output   m_axi_gmem4_WVALID;
input   m_axi_gmem4_WREADY;
output  [31:0] m_axi_gmem4_WDATA;
output  [3:0] m_axi_gmem4_WSTRB;
output   m_axi_gmem4_WLAST;
output  [0:0] m_axi_gmem4_WID;
output  [0:0] m_axi_gmem4_WUSER;
output   m_axi_gmem4_ARVALID;
input   m_axi_gmem4_ARREADY;
output  [63:0] m_axi_gmem4_ARADDR;
output  [0:0] m_axi_gmem4_ARID;
output  [31:0] m_axi_gmem4_ARLEN;
output  [2:0] m_axi_gmem4_ARSIZE;
output  [1:0] m_axi_gmem4_ARBURST;
output  [1:0] m_axi_gmem4_ARLOCK;
output  [3:0] m_axi_gmem4_ARCACHE;
output  [2:0] m_axi_gmem4_ARPROT;
output  [3:0] m_axi_gmem4_ARQOS;
output  [3:0] m_axi_gmem4_ARREGION;
output  [0:0] m_axi_gmem4_ARUSER;
input   m_axi_gmem4_RVALID;
output   m_axi_gmem4_RREADY;
input  [31:0] m_axi_gmem4_RDATA;
input   m_axi_gmem4_RLAST;
input  [0:0] m_axi_gmem4_RID;
input  [8:0] m_axi_gmem4_RFIFONUM;
input  [0:0] m_axi_gmem4_RUSER;
input  [1:0] m_axi_gmem4_RRESP;
input   m_axi_gmem4_BVALID;
output   m_axi_gmem4_BREADY;
input  [1:0] m_axi_gmem4_BRESP;
input  [0:0] m_axi_gmem4_BID;
input  [0:0] m_axi_gmem4_BUSER;
input  [61:0] sext_ln19;
input  [6:0] zext_ln35_8;
output  [6:0] x_0_address0;
output   x_0_ce0;
input  [31:0] x_0_q0;
input  [6:0] zext_ln35_7;
output  [6:0] x_1_address0;
output   x_1_ce0;
input  [31:0] x_1_q0;
input  [6:0] zext_ln35_6;
output  [6:0] x_2_address0;
output   x_2_ce0;
input  [31:0] x_2_q0;
input  [6:0] zext_ln35_5;
output  [6:0] x_3_address0;
output   x_3_ce0;
input  [31:0] x_3_q0;
input  [6:0] zext_ln35_4;
output  [6:0] x_4_address0;
output   x_4_ce0;
input  [31:0] x_4_q0;
input  [6:0] zext_ln35_3;
output  [6:0] x_5_address0;
output   x_5_ce0;
input  [31:0] x_5_q0;
input  [6:0] zext_ln35_2;
output  [6:0] x_6_address0;
output   x_6_ce0;
input  [31:0] x_6_q0;
input  [6:0] zext_ln35_1;
output  [6:0] x_7_address0;
output   x_7_ce0;
input  [31:0] x_7_q0;
output  [8:0] w_0_address0;
output   w_0_ce0;
input  [31:0] w_0_q0;
output  [8:0] w_1_address0;
output   w_1_ce0;
input  [31:0] w_1_q0;
output  [8:0] w_2_address0;
output   w_2_ce0;
input  [31:0] w_2_q0;
output  [8:0] w_3_address0;
output   w_3_ce0;
input  [31:0] w_3_q0;
output  [8:0] w_4_address0;
output   w_4_ce0;
input  [31:0] w_4_q0;
output  [8:0] w_5_address0;
output   w_5_ce0;
input  [31:0] w_5_q0;
output  [8:0] w_6_address0;
output   w_6_ce0;
input  [31:0] w_6_q0;
output  [8:0] w_7_address0;
output   w_7_ce0;
input  [31:0] w_7_q0;
output  [5:0] result_address0;
output   result_ce0;
output   result_we0;
output  [31:0] result_d0;

reg ap_idle;
reg m_axi_gmem4_RREADY;
reg x_0_ce0;
reg x_1_ce0;
reg x_2_ce0;
reg x_3_ce0;
reg x_4_ce0;
reg x_5_ce0;
reg x_6_ce0;
reg x_7_ce0;
reg w_0_ce0;
reg w_1_ce0;
reg w_2_ce0;
reg w_3_ce0;
reg w_4_ce0;
reg w_5_ce0;
reg w_6_ce0;
reg w_7_ce0;
reg result_ce0;
reg result_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln29_1_reg_1092;
reg   [0:0] icmp_ln29_1_reg_1092_pp0_iter3_reg;
reg    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln19_fu_603_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem4_blk_n_R;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln29_fu_627_p2;
reg   [0:0] icmp_ln29_reg_1024;
reg   [0:0] icmp_ln29_reg_1024_pp0_iter1_reg;
reg   [0:0] icmp_ln29_reg_1024_pp0_iter2_reg;
reg   [0:0] icmp_ln29_reg_1024_pp0_iter3_reg;
reg   [0:0] icmp_ln29_reg_1024_pp0_iter4_reg;
reg   [0:0] icmp_ln29_reg_1024_pp0_iter5_reg;
reg   [0:0] icmp_ln29_reg_1024_pp0_iter6_reg;
reg   [0:0] icmp_ln29_reg_1024_pp0_iter7_reg;
reg   [0:0] icmp_ln29_reg_1024_pp0_iter8_reg;
reg   [0:0] icmp_ln29_reg_1024_pp0_iter9_reg;
reg   [0:0] icmp_ln29_reg_1024_pp0_iter10_reg;
reg   [0:0] icmp_ln29_reg_1024_pp0_iter11_reg;
reg   [0:0] icmp_ln29_reg_1024_pp0_iter12_reg;
reg   [0:0] icmp_ln29_reg_1024_pp0_iter13_reg;
reg   [0:0] icmp_ln29_reg_1024_pp0_iter14_reg;
reg   [0:0] icmp_ln29_reg_1024_pp0_iter15_reg;
reg   [0:0] icmp_ln29_reg_1024_pp0_iter16_reg;
wire   [63:0] zext_ln35_fu_768_p1;
reg   [63:0] zext_ln35_reg_1076;
reg   [63:0] zext_ln35_reg_1076_pp0_iter1_reg;
reg   [63:0] zext_ln35_reg_1076_pp0_iter2_reg;
reg   [63:0] zext_ln35_reg_1076_pp0_iter3_reg;
reg   [63:0] zext_ln35_reg_1076_pp0_iter4_reg;
reg   [63:0] zext_ln35_reg_1076_pp0_iter5_reg;
reg   [63:0] zext_ln35_reg_1076_pp0_iter6_reg;
reg   [63:0] zext_ln35_reg_1076_pp0_iter7_reg;
reg   [63:0] zext_ln35_reg_1076_pp0_iter8_reg;
reg   [63:0] zext_ln35_reg_1076_pp0_iter9_reg;
reg   [63:0] zext_ln35_reg_1076_pp0_iter10_reg;
reg   [63:0] zext_ln35_reg_1076_pp0_iter11_reg;
reg   [63:0] zext_ln35_reg_1076_pp0_iter12_reg;
reg   [63:0] zext_ln35_reg_1076_pp0_iter13_reg;
wire   [0:0] icmp_ln29_1_fu_779_p2;
reg   [0:0] icmp_ln29_1_reg_1092_pp0_iter1_reg;
reg   [0:0] icmp_ln29_1_reg_1092_pp0_iter2_reg;
reg   [0:0] icmp_ln29_1_reg_1092_pp0_iter4_reg;
reg   [0:0] icmp_ln29_1_reg_1092_pp0_iter5_reg;
reg   [0:0] icmp_ln29_1_reg_1092_pp0_iter6_reg;
reg   [0:0] icmp_ln29_1_reg_1092_pp0_iter7_reg;
reg   [0:0] icmp_ln29_1_reg_1092_pp0_iter8_reg;
reg   [0:0] icmp_ln29_1_reg_1092_pp0_iter9_reg;
reg   [0:0] icmp_ln29_1_reg_1092_pp0_iter10_reg;
reg   [0:0] icmp_ln29_1_reg_1092_pp0_iter11_reg;
reg   [0:0] icmp_ln29_1_reg_1092_pp0_iter12_reg;
reg   [0:0] icmp_ln29_1_reg_1092_pp0_iter13_reg;
reg   [0:0] icmp_ln29_1_reg_1092_pp0_iter14_reg;
reg   [0:0] icmp_ln29_1_reg_1092_pp0_iter15_reg;
reg   [0:0] icmp_ln29_1_reg_1092_pp0_iter16_reg;
reg   [0:0] icmp_ln29_1_reg_1092_pp0_iter17_reg;
reg   [0:0] icmp_ln29_1_reg_1092_pp0_iter18_reg;
reg   [0:0] icmp_ln29_1_reg_1092_pp0_iter19_reg;
reg   [5:0] result_addr_reg_1096;
reg   [5:0] result_addr_reg_1096_pp0_iter1_reg;
reg   [5:0] result_addr_reg_1096_pp0_iter2_reg;
reg   [5:0] result_addr_reg_1096_pp0_iter3_reg;
reg   [5:0] result_addr_reg_1096_pp0_iter4_reg;
reg   [5:0] result_addr_reg_1096_pp0_iter5_reg;
reg   [5:0] result_addr_reg_1096_pp0_iter6_reg;
reg   [5:0] result_addr_reg_1096_pp0_iter7_reg;
reg   [5:0] result_addr_reg_1096_pp0_iter8_reg;
reg   [5:0] result_addr_reg_1096_pp0_iter9_reg;
reg   [5:0] result_addr_reg_1096_pp0_iter10_reg;
reg   [5:0] result_addr_reg_1096_pp0_iter11_reg;
reg   [5:0] result_addr_reg_1096_pp0_iter12_reg;
reg   [5:0] result_addr_reg_1096_pp0_iter13_reg;
reg   [5:0] result_addr_reg_1096_pp0_iter14_reg;
reg   [5:0] result_addr_reg_1096_pp0_iter15_reg;
reg   [5:0] result_addr_reg_1096_pp0_iter16_reg;
reg   [5:0] result_addr_reg_1096_pp0_iter17_reg;
reg   [5:0] result_addr_reg_1096_pp0_iter18_reg;
reg   [5:0] result_addr_reg_1096_pp0_iter19_reg;
reg   [31:0] x_1_load_reg_1111;
reg   [31:0] x_1_load_reg_1111_pp0_iter2_reg;
reg   [31:0] x_2_load_reg_1116;
reg   [31:0] x_2_load_reg_1116_pp0_iter2_reg;
reg   [31:0] x_2_load_reg_1116_pp0_iter3_reg;
reg   [31:0] x_2_load_reg_1116_pp0_iter4_reg;
reg   [31:0] x_3_load_reg_1121;
reg   [31:0] x_3_load_reg_1121_pp0_iter2_reg;
reg   [31:0] x_3_load_reg_1121_pp0_iter3_reg;
reg   [31:0] x_3_load_reg_1121_pp0_iter4_reg;
reg   [31:0] x_3_load_reg_1121_pp0_iter5_reg;
reg   [31:0] x_3_load_reg_1121_pp0_iter6_reg;
reg   [31:0] x_4_load_reg_1126;
reg   [31:0] x_4_load_reg_1126_pp0_iter2_reg;
reg   [31:0] x_4_load_reg_1126_pp0_iter3_reg;
reg   [31:0] x_4_load_reg_1126_pp0_iter4_reg;
reg   [31:0] x_4_load_reg_1126_pp0_iter5_reg;
reg   [31:0] x_4_load_reg_1126_pp0_iter6_reg;
reg   [31:0] x_4_load_reg_1126_pp0_iter7_reg;
reg   [31:0] x_4_load_reg_1126_pp0_iter8_reg;
reg   [31:0] x_5_load_reg_1131;
reg   [31:0] x_5_load_reg_1131_pp0_iter2_reg;
reg   [31:0] x_5_load_reg_1131_pp0_iter3_reg;
reg   [31:0] x_5_load_reg_1131_pp0_iter4_reg;
reg   [31:0] x_5_load_reg_1131_pp0_iter5_reg;
reg   [31:0] x_5_load_reg_1131_pp0_iter6_reg;
reg   [31:0] x_5_load_reg_1131_pp0_iter7_reg;
reg   [31:0] x_5_load_reg_1131_pp0_iter8_reg;
reg   [31:0] x_5_load_reg_1131_pp0_iter9_reg;
reg   [31:0] x_5_load_reg_1131_pp0_iter10_reg;
reg   [31:0] x_6_load_reg_1136;
reg   [31:0] x_6_load_reg_1136_pp0_iter2_reg;
reg   [31:0] x_6_load_reg_1136_pp0_iter3_reg;
reg   [31:0] x_6_load_reg_1136_pp0_iter4_reg;
reg   [31:0] x_6_load_reg_1136_pp0_iter5_reg;
reg   [31:0] x_6_load_reg_1136_pp0_iter6_reg;
reg   [31:0] x_6_load_reg_1136_pp0_iter7_reg;
reg   [31:0] x_6_load_reg_1136_pp0_iter8_reg;
reg   [31:0] x_6_load_reg_1136_pp0_iter9_reg;
reg   [31:0] x_6_load_reg_1136_pp0_iter10_reg;
reg   [31:0] x_6_load_reg_1136_pp0_iter11_reg;
reg   [31:0] x_6_load_reg_1136_pp0_iter12_reg;
reg   [31:0] x_7_load_reg_1141;
reg   [31:0] x_7_load_reg_1141_pp0_iter2_reg;
reg   [31:0] x_7_load_reg_1141_pp0_iter3_reg;
reg   [31:0] x_7_load_reg_1141_pp0_iter4_reg;
reg   [31:0] x_7_load_reg_1141_pp0_iter5_reg;
reg   [31:0] x_7_load_reg_1141_pp0_iter6_reg;
reg   [31:0] x_7_load_reg_1141_pp0_iter7_reg;
reg   [31:0] x_7_load_reg_1141_pp0_iter8_reg;
reg   [31:0] x_7_load_reg_1141_pp0_iter9_reg;
reg   [31:0] x_7_load_reg_1141_pp0_iter10_reg;
reg   [31:0] x_7_load_reg_1141_pp0_iter11_reg;
reg   [31:0] x_7_load_reg_1141_pp0_iter12_reg;
reg   [31:0] x_7_load_reg_1141_pp0_iter13_reg;
reg   [31:0] x_7_load_reg_1141_pp0_iter14_reg;
wire   [31:0] grp_fu_500_p2;
reg   [31:0] mul_reg_1146;
wire   [31:0] grp_fu_435_p2;
reg   [31:0] add_reg_1166;
wire   [31:0] grp_fu_506_p2;
reg   [31:0] mul20_1_reg_1171;
reg   [31:0] gmem4_addr_read_reg_1181;
wire   [31:0] grp_fu_439_p2;
reg   [31:0] add23_1_reg_1201;
wire   [31:0] grp_fu_511_p2;
reg   [31:0] mul20_2_reg_1206;
wire   [31:0] grp_fu_443_p2;
reg   [31:0] acc_65_reg_1216;
wire   [31:0] grp_fu_447_p2;
reg   [31:0] add23_2_reg_1231;
wire   [31:0] grp_fu_516_p2;
reg   [31:0] mul20_3_reg_1236;
wire   [31:0] grp_fu_451_p2;
reg   [31:0] acc_66_reg_1246;
wire   [31:0] grp_fu_455_p2;
reg   [31:0] add23_3_reg_1261;
wire   [31:0] grp_fu_521_p2;
reg   [31:0] mul20_4_reg_1266;
wire   [31:0] grp_fu_459_p2;
reg   [31:0] acc_67_reg_1276;
wire   [31:0] grp_fu_463_p2;
reg   [31:0] add23_4_reg_1291;
wire   [31:0] grp_fu_526_p2;
reg   [31:0] mul20_5_reg_1296;
wire   [31:0] grp_fu_467_p2;
reg   [31:0] acc_68_reg_1306;
wire   [31:0] grp_fu_471_p2;
reg   [31:0] add23_5_reg_1321;
wire   [31:0] grp_fu_531_p2;
reg   [31:0] mul20_6_reg_1326;
wire   [31:0] grp_fu_475_p2;
reg   [31:0] acc_69_reg_1336;
wire   [31:0] grp_fu_479_p2;
reg   [31:0] add23_6_reg_1351;
wire   [31:0] grp_fu_536_p2;
reg   [31:0] mul20_7_reg_1356;
wire   [31:0] grp_fu_483_p2;
reg   [31:0] acc_70_reg_1361;
wire   [31:0] grp_fu_487_p2;
reg   [31:0] add23_7_reg_1371;
wire   [31:0] grp_fu_491_p2;
reg   [31:0] acc_71_reg_1376;
wire   [63:0] zext_ln35_10_fu_676_p1;
wire   [63:0] zext_ln35_11_fu_687_p1;
wire   [63:0] zext_ln35_12_fu_698_p1;
wire   [63:0] zext_ln35_13_fu_709_p1;
wire   [63:0] zext_ln35_14_fu_720_p1;
wire   [63:0] zext_ln35_15_fu_731_p1;
wire   [63:0] zext_ln35_16_fu_742_p1;
wire   [63:0] zext_ln35_17_fu_753_p1;
wire   [63:0] zext_ln19_fu_649_p1;
reg   [31:0] empty_fu_112;
reg   [31:0] ap_sig_allocacmp_p_load31;
wire    ap_loop_init;
reg   [31:0] empty_69_fu_116;
reg   [31:0] ap_sig_allocacmp_p_load30;
reg   [31:0] empty_70_fu_120;
reg   [31:0] ap_sig_allocacmp_p_load29;
reg   [31:0] empty_71_fu_124;
reg   [31:0] ap_sig_allocacmp_p_load28;
reg   [31:0] empty_72_fu_128;
reg   [31:0] ap_sig_allocacmp_p_load27;
reg   [31:0] empty_73_fu_132;
reg   [31:0] ap_sig_allocacmp_p_load26;
reg   [31:0] empty_74_fu_136;
reg   [31:0] ap_sig_allocacmp_p_load25;
reg   [31:0] empty_75_fu_140;
reg   [31:0] ap_sig_allocacmp_p_load;
reg   [3:0] g_fu_144;
wire   [3:0] add_ln29_fu_773_p2;
reg   [3:0] ap_sig_allocacmp_g_load;
reg   [6:0] o_fu_148;
wire   [6:0] select_ln19_9_fu_641_p3;
reg   [6:0] ap_sig_allocacmp_o_load;
reg   [9:0] indvar_flatten_fu_152;
wire   [9:0] add_ln19_1_fu_609_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten_load;
wire   [31:0] grp_fu_495_p2;
wire   [31:0] grp_fu_435_p0;
wire   [31:0] grp_fu_439_p0;
wire   [31:0] grp_fu_443_p0;
wire   [31:0] grp_fu_447_p0;
wire   [31:0] grp_fu_455_p0;
wire   [31:0] grp_fu_463_p0;
wire   [31:0] grp_fu_471_p0;
wire   [31:0] grp_fu_479_p0;
wire   [31:0] grp_fu_487_p0;
wire   [6:0] add_ln19_fu_621_p2;
wire   [5:0] empty_76_fu_654_p1;
wire   [3:0] select_ln19_fu_633_p3;
wire   [6:0] zext_ln35_9_fu_666_p1;
wire   [6:0] add_ln35_1_fu_670_p2;
wire   [6:0] add_ln35_2_fu_681_p2;
wire   [6:0] add_ln35_3_fu_692_p2;
wire   [6:0] add_ln35_4_fu_703_p2;
wire   [6:0] add_ln35_5_fu_714_p2;
wire   [6:0] add_ln35_6_fu_725_p2;
wire   [6:0] add_ln35_7_fu_736_p2;
wire   [6:0] add_ln35_8_fu_747_p2;
wire   [8:0] zext_ln29_fu_758_p1;
wire   [8:0] p_udiv_fu_658_p3;
wire   [8:0] add_ln35_fu_762_p2;
reg    grp_fu_435_ce;
reg    grp_fu_439_ce;
reg    grp_fu_443_ce;
reg    grp_fu_447_ce;
reg    grp_fu_451_ce;
reg    grp_fu_455_ce;
reg    grp_fu_459_ce;
reg    grp_fu_463_ce;
reg    grp_fu_467_ce;
reg    grp_fu_471_ce;
reg    grp_fu_475_ce;
reg    grp_fu_479_ce;
reg    grp_fu_483_ce;
reg    grp_fu_487_ce;
reg    grp_fu_491_ce;
reg    grp_fu_495_ce;
reg    grp_fu_500_ce;
reg    grp_fu_506_ce;
reg    grp_fu_511_ce;
reg    grp_fu_516_ce;
reg    grp_fu_521_ce;
reg    grp_fu_526_ce;
reg    grp_fu_531_ce;
reg    grp_fu_536_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 empty_fu_112 = 32'd0;
#0 empty_69_fu_116 = 32'd0;
#0 empty_70_fu_120 = 32'd0;
#0 empty_71_fu_124 = 32'd0;
#0 empty_72_fu_128 = 32'd0;
#0 empty_73_fu_132 = 32'd0;
#0 empty_74_fu_136 = 32'd0;
#0 empty_75_fu_140 = 32'd0;
#0 g_fu_144 = 4'd0;
#0 o_fu_148 = 7'd0;
#0 indvar_flatten_fu_152 = 10'd0;
#0 ap_done_reg = 1'b0;
end

pseudo_moe_fadd_32ns_32ns_32_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_2_full_dsp_1_U124(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_435_p0),
    .din1(mul_reg_1146),
    .ce(grp_fu_435_ce),
    .dout(grp_fu_435_p2)
);

pseudo_moe_fadd_32ns_32ns_32_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_2_full_dsp_1_U125(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_439_p0),
    .din1(mul20_1_reg_1171),
    .ce(grp_fu_439_ce),
    .dout(grp_fu_439_p2)
);

pseudo_moe_fadd_32ns_32ns_32_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_2_full_dsp_1_U126(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_443_p0),
    .din1(add_reg_1166),
    .ce(grp_fu_443_ce),
    .dout(grp_fu_443_p2)
);

pseudo_moe_fadd_32ns_32ns_32_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_2_full_dsp_1_U127(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_447_p0),
    .din1(mul20_2_reg_1206),
    .ce(grp_fu_447_ce),
    .dout(grp_fu_447_p2)
);

pseudo_moe_fadd_32ns_32ns_32_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_2_full_dsp_1_U128(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(acc_65_reg_1216),
    .din1(add23_1_reg_1201),
    .ce(grp_fu_451_ce),
    .dout(grp_fu_451_p2)
);

pseudo_moe_fadd_32ns_32ns_32_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_2_full_dsp_1_U129(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_455_p0),
    .din1(mul20_3_reg_1236),
    .ce(grp_fu_455_ce),
    .dout(grp_fu_455_p2)
);

pseudo_moe_fadd_32ns_32ns_32_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_2_full_dsp_1_U130(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(acc_66_reg_1246),
    .din1(add23_2_reg_1231),
    .ce(grp_fu_459_ce),
    .dout(grp_fu_459_p2)
);

pseudo_moe_fadd_32ns_32ns_32_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_2_full_dsp_1_U131(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_463_p0),
    .din1(mul20_4_reg_1266),
    .ce(grp_fu_463_ce),
    .dout(grp_fu_463_p2)
);

pseudo_moe_fadd_32ns_32ns_32_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_2_full_dsp_1_U132(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(acc_67_reg_1276),
    .din1(add23_3_reg_1261),
    .ce(grp_fu_467_ce),
    .dout(grp_fu_467_p2)
);

pseudo_moe_fadd_32ns_32ns_32_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_2_full_dsp_1_U133(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_471_p0),
    .din1(mul20_5_reg_1296),
    .ce(grp_fu_471_ce),
    .dout(grp_fu_471_p2)
);

pseudo_moe_fadd_32ns_32ns_32_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_2_full_dsp_1_U134(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(acc_68_reg_1306),
    .din1(add23_4_reg_1291),
    .ce(grp_fu_475_ce),
    .dout(grp_fu_475_p2)
);

pseudo_moe_fadd_32ns_32ns_32_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_2_full_dsp_1_U135(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_479_p0),
    .din1(mul20_6_reg_1326),
    .ce(grp_fu_479_ce),
    .dout(grp_fu_479_p2)
);

pseudo_moe_fadd_32ns_32ns_32_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_2_full_dsp_1_U136(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(acc_69_reg_1336),
    .din1(add23_5_reg_1321),
    .ce(grp_fu_483_ce),
    .dout(grp_fu_483_p2)
);

pseudo_moe_fadd_32ns_32ns_32_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_2_full_dsp_1_U137(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_487_p0),
    .din1(mul20_7_reg_1356),
    .ce(grp_fu_487_ce),
    .dout(grp_fu_487_p2)
);

pseudo_moe_fadd_32ns_32ns_32_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_2_full_dsp_1_U138(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(acc_70_reg_1361),
    .din1(add23_6_reg_1351),
    .ce(grp_fu_491_ce),
    .dout(grp_fu_491_p2)
);

pseudo_moe_fadd_32ns_32ns_32_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_2_full_dsp_1_U139(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(acc_71_reg_1376),
    .din1(add23_7_reg_1371),
    .ce(grp_fu_495_ce),
    .dout(grp_fu_495_p2)
);

pseudo_moe_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U140(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(x_0_q0),
    .din1(w_0_q0),
    .ce(grp_fu_500_ce),
    .dout(grp_fu_500_p2)
);

pseudo_moe_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U141(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(x_1_load_reg_1111_pp0_iter2_reg),
    .din1(w_1_q0),
    .ce(grp_fu_506_ce),
    .dout(grp_fu_506_p2)
);

pseudo_moe_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U142(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(x_2_load_reg_1116_pp0_iter4_reg),
    .din1(w_2_q0),
    .ce(grp_fu_511_ce),
    .dout(grp_fu_511_p2)
);

pseudo_moe_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U143(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(x_3_load_reg_1121_pp0_iter6_reg),
    .din1(w_3_q0),
    .ce(grp_fu_516_ce),
    .dout(grp_fu_516_p2)
);

pseudo_moe_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U144(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(x_4_load_reg_1126_pp0_iter8_reg),
    .din1(w_4_q0),
    .ce(grp_fu_521_ce),
    .dout(grp_fu_521_p2)
);

pseudo_moe_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U145(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(x_5_load_reg_1131_pp0_iter10_reg),
    .din1(w_5_q0),
    .ce(grp_fu_526_ce),
    .dout(grp_fu_526_p2)
);

pseudo_moe_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U146(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(x_6_load_reg_1136_pp0_iter12_reg),
    .din1(w_6_q0),
    .ce(grp_fu_531_ce),
    .dout(grp_fu_531_p2)
);

pseudo_moe_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U147(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(x_7_load_reg_1141_pp0_iter14_reg),
    .din1(w_7_q0),
    .ce(grp_fu_536_ce),
    .dout(grp_fu_536_p2)
);

pseudo_moe_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter19_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_69_fu_116 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
            empty_69_fu_116 <= grp_fu_439_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_70_fu_120 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter8 == 1'b1)) begin
            empty_70_fu_120 <= grp_fu_447_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_71_fu_124 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter10 == 1'b1)) begin
            empty_71_fu_124 <= grp_fu_455_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_72_fu_128 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter12 == 1'b1)) begin
            empty_72_fu_128 <= grp_fu_463_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_73_fu_132 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter14 == 1'b1)) begin
            empty_73_fu_132 <= grp_fu_471_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_74_fu_136 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter16 == 1'b1)) begin
            empty_74_fu_136 <= grp_fu_479_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_75_fu_140 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter18 == 1'b1)) begin
            empty_75_fu_140 <= grp_fu_487_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            empty_fu_112 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            empty_fu_112 <= grp_fu_435_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln19_fu_603_p2 == 1'd0))) begin
            g_fu_144 <= add_ln29_fu_773_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            g_fu_144 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln19_fu_603_p2 == 1'd0))) begin
            indvar_flatten_fu_152 <= add_ln19_1_fu_609_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_152 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln19_fu_603_p2 == 1'd0))) begin
            o_fu_148 <= select_ln19_9_fu_641_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            o_fu_148 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        acc_65_reg_1216 <= grp_fu_443_p2;
        acc_66_reg_1246 <= grp_fu_451_p2;
        acc_67_reg_1276 <= grp_fu_459_p2;
        acc_68_reg_1306 <= grp_fu_467_p2;
        acc_69_reg_1336 <= grp_fu_475_p2;
        acc_70_reg_1361 <= grp_fu_483_p2;
        acc_71_reg_1376 <= grp_fu_491_p2;
        add23_1_reg_1201 <= grp_fu_439_p2;
        add23_2_reg_1231 <= grp_fu_447_p2;
        add23_3_reg_1261 <= grp_fu_455_p2;
        add23_4_reg_1291 <= grp_fu_463_p2;
        add23_5_reg_1321 <= grp_fu_471_p2;
        add23_6_reg_1351 <= grp_fu_479_p2;
        add23_7_reg_1371 <= grp_fu_487_p2;
        add_reg_1166 <= grp_fu_435_p2;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        gmem4_addr_read_reg_1181 <= m_axi_gmem4_RDATA;
        icmp_ln29_1_reg_1092_pp0_iter10_reg <= icmp_ln29_1_reg_1092_pp0_iter9_reg;
        icmp_ln29_1_reg_1092_pp0_iter11_reg <= icmp_ln29_1_reg_1092_pp0_iter10_reg;
        icmp_ln29_1_reg_1092_pp0_iter12_reg <= icmp_ln29_1_reg_1092_pp0_iter11_reg;
        icmp_ln29_1_reg_1092_pp0_iter13_reg <= icmp_ln29_1_reg_1092_pp0_iter12_reg;
        icmp_ln29_1_reg_1092_pp0_iter14_reg <= icmp_ln29_1_reg_1092_pp0_iter13_reg;
        icmp_ln29_1_reg_1092_pp0_iter15_reg <= icmp_ln29_1_reg_1092_pp0_iter14_reg;
        icmp_ln29_1_reg_1092_pp0_iter16_reg <= icmp_ln29_1_reg_1092_pp0_iter15_reg;
        icmp_ln29_1_reg_1092_pp0_iter17_reg <= icmp_ln29_1_reg_1092_pp0_iter16_reg;
        icmp_ln29_1_reg_1092_pp0_iter18_reg <= icmp_ln29_1_reg_1092_pp0_iter17_reg;
        icmp_ln29_1_reg_1092_pp0_iter19_reg <= icmp_ln29_1_reg_1092_pp0_iter18_reg;
        icmp_ln29_1_reg_1092_pp0_iter2_reg <= icmp_ln29_1_reg_1092_pp0_iter1_reg;
        icmp_ln29_1_reg_1092_pp0_iter3_reg <= icmp_ln29_1_reg_1092_pp0_iter2_reg;
        icmp_ln29_1_reg_1092_pp0_iter4_reg <= icmp_ln29_1_reg_1092_pp0_iter3_reg;
        icmp_ln29_1_reg_1092_pp0_iter5_reg <= icmp_ln29_1_reg_1092_pp0_iter4_reg;
        icmp_ln29_1_reg_1092_pp0_iter6_reg <= icmp_ln29_1_reg_1092_pp0_iter5_reg;
        icmp_ln29_1_reg_1092_pp0_iter7_reg <= icmp_ln29_1_reg_1092_pp0_iter6_reg;
        icmp_ln29_1_reg_1092_pp0_iter8_reg <= icmp_ln29_1_reg_1092_pp0_iter7_reg;
        icmp_ln29_1_reg_1092_pp0_iter9_reg <= icmp_ln29_1_reg_1092_pp0_iter8_reg;
        icmp_ln29_reg_1024_pp0_iter10_reg <= icmp_ln29_reg_1024_pp0_iter9_reg;
        icmp_ln29_reg_1024_pp0_iter11_reg <= icmp_ln29_reg_1024_pp0_iter10_reg;
        icmp_ln29_reg_1024_pp0_iter12_reg <= icmp_ln29_reg_1024_pp0_iter11_reg;
        icmp_ln29_reg_1024_pp0_iter13_reg <= icmp_ln29_reg_1024_pp0_iter12_reg;
        icmp_ln29_reg_1024_pp0_iter14_reg <= icmp_ln29_reg_1024_pp0_iter13_reg;
        icmp_ln29_reg_1024_pp0_iter15_reg <= icmp_ln29_reg_1024_pp0_iter14_reg;
        icmp_ln29_reg_1024_pp0_iter16_reg <= icmp_ln29_reg_1024_pp0_iter15_reg;
        icmp_ln29_reg_1024_pp0_iter2_reg <= icmp_ln29_reg_1024_pp0_iter1_reg;
        icmp_ln29_reg_1024_pp0_iter3_reg <= icmp_ln29_reg_1024_pp0_iter2_reg;
        icmp_ln29_reg_1024_pp0_iter4_reg <= icmp_ln29_reg_1024_pp0_iter3_reg;
        icmp_ln29_reg_1024_pp0_iter5_reg <= icmp_ln29_reg_1024_pp0_iter4_reg;
        icmp_ln29_reg_1024_pp0_iter6_reg <= icmp_ln29_reg_1024_pp0_iter5_reg;
        icmp_ln29_reg_1024_pp0_iter7_reg <= icmp_ln29_reg_1024_pp0_iter6_reg;
        icmp_ln29_reg_1024_pp0_iter8_reg <= icmp_ln29_reg_1024_pp0_iter7_reg;
        icmp_ln29_reg_1024_pp0_iter9_reg <= icmp_ln29_reg_1024_pp0_iter8_reg;
        mul20_1_reg_1171 <= grp_fu_506_p2;
        mul20_2_reg_1206 <= grp_fu_511_p2;
        mul20_3_reg_1236 <= grp_fu_516_p2;
        mul20_4_reg_1266 <= grp_fu_521_p2;
        mul20_5_reg_1296 <= grp_fu_526_p2;
        mul20_6_reg_1326 <= grp_fu_531_p2;
        mul20_7_reg_1356 <= grp_fu_536_p2;
        mul_reg_1146 <= grp_fu_500_p2;
        result_addr_reg_1096_pp0_iter10_reg <= result_addr_reg_1096_pp0_iter9_reg;
        result_addr_reg_1096_pp0_iter11_reg <= result_addr_reg_1096_pp0_iter10_reg;
        result_addr_reg_1096_pp0_iter12_reg <= result_addr_reg_1096_pp0_iter11_reg;
        result_addr_reg_1096_pp0_iter13_reg <= result_addr_reg_1096_pp0_iter12_reg;
        result_addr_reg_1096_pp0_iter14_reg <= result_addr_reg_1096_pp0_iter13_reg;
        result_addr_reg_1096_pp0_iter15_reg <= result_addr_reg_1096_pp0_iter14_reg;
        result_addr_reg_1096_pp0_iter16_reg <= result_addr_reg_1096_pp0_iter15_reg;
        result_addr_reg_1096_pp0_iter17_reg <= result_addr_reg_1096_pp0_iter16_reg;
        result_addr_reg_1096_pp0_iter18_reg <= result_addr_reg_1096_pp0_iter17_reg;
        result_addr_reg_1096_pp0_iter19_reg <= result_addr_reg_1096_pp0_iter18_reg;
        result_addr_reg_1096_pp0_iter2_reg <= result_addr_reg_1096_pp0_iter1_reg;
        result_addr_reg_1096_pp0_iter3_reg <= result_addr_reg_1096_pp0_iter2_reg;
        result_addr_reg_1096_pp0_iter4_reg <= result_addr_reg_1096_pp0_iter3_reg;
        result_addr_reg_1096_pp0_iter5_reg <= result_addr_reg_1096_pp0_iter4_reg;
        result_addr_reg_1096_pp0_iter6_reg <= result_addr_reg_1096_pp0_iter5_reg;
        result_addr_reg_1096_pp0_iter7_reg <= result_addr_reg_1096_pp0_iter6_reg;
        result_addr_reg_1096_pp0_iter8_reg <= result_addr_reg_1096_pp0_iter7_reg;
        result_addr_reg_1096_pp0_iter9_reg <= result_addr_reg_1096_pp0_iter8_reg;
        x_1_load_reg_1111_pp0_iter2_reg <= x_1_load_reg_1111;
        x_2_load_reg_1116_pp0_iter2_reg <= x_2_load_reg_1116;
        x_2_load_reg_1116_pp0_iter3_reg <= x_2_load_reg_1116_pp0_iter2_reg;
        x_2_load_reg_1116_pp0_iter4_reg <= x_2_load_reg_1116_pp0_iter3_reg;
        x_3_load_reg_1121_pp0_iter2_reg <= x_3_load_reg_1121;
        x_3_load_reg_1121_pp0_iter3_reg <= x_3_load_reg_1121_pp0_iter2_reg;
        x_3_load_reg_1121_pp0_iter4_reg <= x_3_load_reg_1121_pp0_iter3_reg;
        x_3_load_reg_1121_pp0_iter5_reg <= x_3_load_reg_1121_pp0_iter4_reg;
        x_3_load_reg_1121_pp0_iter6_reg <= x_3_load_reg_1121_pp0_iter5_reg;
        x_4_load_reg_1126_pp0_iter2_reg <= x_4_load_reg_1126;
        x_4_load_reg_1126_pp0_iter3_reg <= x_4_load_reg_1126_pp0_iter2_reg;
        x_4_load_reg_1126_pp0_iter4_reg <= x_4_load_reg_1126_pp0_iter3_reg;
        x_4_load_reg_1126_pp0_iter5_reg <= x_4_load_reg_1126_pp0_iter4_reg;
        x_4_load_reg_1126_pp0_iter6_reg <= x_4_load_reg_1126_pp0_iter5_reg;
        x_4_load_reg_1126_pp0_iter7_reg <= x_4_load_reg_1126_pp0_iter6_reg;
        x_4_load_reg_1126_pp0_iter8_reg <= x_4_load_reg_1126_pp0_iter7_reg;
        x_5_load_reg_1131_pp0_iter10_reg <= x_5_load_reg_1131_pp0_iter9_reg;
        x_5_load_reg_1131_pp0_iter2_reg <= x_5_load_reg_1131;
        x_5_load_reg_1131_pp0_iter3_reg <= x_5_load_reg_1131_pp0_iter2_reg;
        x_5_load_reg_1131_pp0_iter4_reg <= x_5_load_reg_1131_pp0_iter3_reg;
        x_5_load_reg_1131_pp0_iter5_reg <= x_5_load_reg_1131_pp0_iter4_reg;
        x_5_load_reg_1131_pp0_iter6_reg <= x_5_load_reg_1131_pp0_iter5_reg;
        x_5_load_reg_1131_pp0_iter7_reg <= x_5_load_reg_1131_pp0_iter6_reg;
        x_5_load_reg_1131_pp0_iter8_reg <= x_5_load_reg_1131_pp0_iter7_reg;
        x_5_load_reg_1131_pp0_iter9_reg <= x_5_load_reg_1131_pp0_iter8_reg;
        x_6_load_reg_1136_pp0_iter10_reg <= x_6_load_reg_1136_pp0_iter9_reg;
        x_6_load_reg_1136_pp0_iter11_reg <= x_6_load_reg_1136_pp0_iter10_reg;
        x_6_load_reg_1136_pp0_iter12_reg <= x_6_load_reg_1136_pp0_iter11_reg;
        x_6_load_reg_1136_pp0_iter2_reg <= x_6_load_reg_1136;
        x_6_load_reg_1136_pp0_iter3_reg <= x_6_load_reg_1136_pp0_iter2_reg;
        x_6_load_reg_1136_pp0_iter4_reg <= x_6_load_reg_1136_pp0_iter3_reg;
        x_6_load_reg_1136_pp0_iter5_reg <= x_6_load_reg_1136_pp0_iter4_reg;
        x_6_load_reg_1136_pp0_iter6_reg <= x_6_load_reg_1136_pp0_iter5_reg;
        x_6_load_reg_1136_pp0_iter7_reg <= x_6_load_reg_1136_pp0_iter6_reg;
        x_6_load_reg_1136_pp0_iter8_reg <= x_6_load_reg_1136_pp0_iter7_reg;
        x_6_load_reg_1136_pp0_iter9_reg <= x_6_load_reg_1136_pp0_iter8_reg;
        x_7_load_reg_1141_pp0_iter10_reg <= x_7_load_reg_1141_pp0_iter9_reg;
        x_7_load_reg_1141_pp0_iter11_reg <= x_7_load_reg_1141_pp0_iter10_reg;
        x_7_load_reg_1141_pp0_iter12_reg <= x_7_load_reg_1141_pp0_iter11_reg;
        x_7_load_reg_1141_pp0_iter13_reg <= x_7_load_reg_1141_pp0_iter12_reg;
        x_7_load_reg_1141_pp0_iter14_reg <= x_7_load_reg_1141_pp0_iter13_reg;
        x_7_load_reg_1141_pp0_iter2_reg <= x_7_load_reg_1141;
        x_7_load_reg_1141_pp0_iter3_reg <= x_7_load_reg_1141_pp0_iter2_reg;
        x_7_load_reg_1141_pp0_iter4_reg <= x_7_load_reg_1141_pp0_iter3_reg;
        x_7_load_reg_1141_pp0_iter5_reg <= x_7_load_reg_1141_pp0_iter4_reg;
        x_7_load_reg_1141_pp0_iter6_reg <= x_7_load_reg_1141_pp0_iter5_reg;
        x_7_load_reg_1141_pp0_iter7_reg <= x_7_load_reg_1141_pp0_iter6_reg;
        x_7_load_reg_1141_pp0_iter8_reg <= x_7_load_reg_1141_pp0_iter7_reg;
        x_7_load_reg_1141_pp0_iter9_reg <= x_7_load_reg_1141_pp0_iter8_reg;
        zext_ln35_reg_1076_pp0_iter10_reg[8 : 0] <= zext_ln35_reg_1076_pp0_iter9_reg[8 : 0];
        zext_ln35_reg_1076_pp0_iter11_reg[8 : 0] <= zext_ln35_reg_1076_pp0_iter10_reg[8 : 0];
        zext_ln35_reg_1076_pp0_iter12_reg[8 : 0] <= zext_ln35_reg_1076_pp0_iter11_reg[8 : 0];
        zext_ln35_reg_1076_pp0_iter13_reg[8 : 0] <= zext_ln35_reg_1076_pp0_iter12_reg[8 : 0];
        zext_ln35_reg_1076_pp0_iter2_reg[8 : 0] <= zext_ln35_reg_1076_pp0_iter1_reg[8 : 0];
        zext_ln35_reg_1076_pp0_iter3_reg[8 : 0] <= zext_ln35_reg_1076_pp0_iter2_reg[8 : 0];
        zext_ln35_reg_1076_pp0_iter4_reg[8 : 0] <= zext_ln35_reg_1076_pp0_iter3_reg[8 : 0];
        zext_ln35_reg_1076_pp0_iter5_reg[8 : 0] <= zext_ln35_reg_1076_pp0_iter4_reg[8 : 0];
        zext_ln35_reg_1076_pp0_iter6_reg[8 : 0] <= zext_ln35_reg_1076_pp0_iter5_reg[8 : 0];
        zext_ln35_reg_1076_pp0_iter7_reg[8 : 0] <= zext_ln35_reg_1076_pp0_iter6_reg[8 : 0];
        zext_ln35_reg_1076_pp0_iter8_reg[8 : 0] <= zext_ln35_reg_1076_pp0_iter7_reg[8 : 0];
        zext_ln35_reg_1076_pp0_iter9_reg[8 : 0] <= zext_ln35_reg_1076_pp0_iter8_reg[8 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln29_1_reg_1092 <= icmp_ln29_1_fu_779_p2;
        icmp_ln29_1_reg_1092_pp0_iter1_reg <= icmp_ln29_1_reg_1092;
        icmp_ln29_reg_1024 <= icmp_ln29_fu_627_p2;
        icmp_ln29_reg_1024_pp0_iter1_reg <= icmp_ln29_reg_1024;
        result_addr_reg_1096 <= zext_ln19_fu_649_p1;
        result_addr_reg_1096_pp0_iter1_reg <= result_addr_reg_1096;
        x_1_load_reg_1111 <= x_1_q0;
        x_2_load_reg_1116 <= x_2_q0;
        x_3_load_reg_1121 <= x_3_q0;
        x_4_load_reg_1126 <= x_4_q0;
        x_5_load_reg_1131 <= x_5_q0;
        x_6_load_reg_1136 <= x_6_q0;
        x_7_load_reg_1141 <= x_7_q0;
        zext_ln35_reg_1076[8 : 0] <= zext_ln35_fu_768_p1[8 : 0];
        zext_ln35_reg_1076_pp0_iter1_reg[8 : 0] <= zext_ln35_reg_1076[8 : 0];
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln19_fu_603_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter19_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_g_load = 4'd0;
    end else begin
        ap_sig_allocacmp_g_load = g_fu_144;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_152;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_o_load = 7'd0;
    end else begin
        ap_sig_allocacmp_o_load = o_fu_148;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_p_load = grp_fu_487_p2;
    end else begin
        ap_sig_allocacmp_p_load = empty_75_fu_140;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_p_load25 = grp_fu_479_p2;
    end else begin
        ap_sig_allocacmp_p_load25 = empty_74_fu_136;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_p_load26 = grp_fu_471_p2;
    end else begin
        ap_sig_allocacmp_p_load26 = empty_73_fu_132;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_p_load27 = grp_fu_463_p2;
    end else begin
        ap_sig_allocacmp_p_load27 = empty_72_fu_128;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_p_load28 = grp_fu_455_p2;
    end else begin
        ap_sig_allocacmp_p_load28 = empty_71_fu_124;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_p_load29 = grp_fu_447_p2;
    end else begin
        ap_sig_allocacmp_p_load29 = empty_70_fu_120;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_p_load30 = grp_fu_439_p2;
    end else begin
        ap_sig_allocacmp_p_load30 = empty_69_fu_116;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_p_load31 = grp_fu_435_p2;
    end else begin
        ap_sig_allocacmp_p_load31 = empty_fu_112;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln29_1_reg_1092_pp0_iter3_reg == 1'd1))) begin
        gmem4_blk_n_R = m_axi_gmem4_RVALID;
    end else begin
        gmem4_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_435_ce = 1'b1;
    end else begin
        grp_fu_435_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_439_ce = 1'b1;
    end else begin
        grp_fu_439_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_443_ce = 1'b1;
    end else begin
        grp_fu_443_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_447_ce = 1'b1;
    end else begin
        grp_fu_447_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_451_ce = 1'b1;
    end else begin
        grp_fu_451_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_455_ce = 1'b1;
    end else begin
        grp_fu_455_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_459_ce = 1'b1;
    end else begin
        grp_fu_459_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_463_ce = 1'b1;
    end else begin
        grp_fu_463_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_467_ce = 1'b1;
    end else begin
        grp_fu_467_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_471_ce = 1'b1;
    end else begin
        grp_fu_471_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_475_ce = 1'b1;
    end else begin
        grp_fu_475_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_479_ce = 1'b1;
    end else begin
        grp_fu_479_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_483_ce = 1'b1;
    end else begin
        grp_fu_483_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_487_ce = 1'b1;
    end else begin
        grp_fu_487_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_491_ce = 1'b1;
    end else begin
        grp_fu_491_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_495_ce = 1'b1;
    end else begin
        grp_fu_495_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_500_ce = 1'b1;
    end else begin
        grp_fu_500_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_506_ce = 1'b1;
    end else begin
        grp_fu_506_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_511_ce = 1'b1;
    end else begin
        grp_fu_511_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_516_ce = 1'b1;
    end else begin
        grp_fu_516_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_521_ce = 1'b1;
    end else begin
        grp_fu_521_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_526_ce = 1'b1;
    end else begin
        grp_fu_526_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_531_ce = 1'b1;
    end else begin
        grp_fu_531_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_536_ce = 1'b1;
    end else begin
        grp_fu_536_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln29_1_reg_1092_pp0_iter3_reg == 1'd1))) begin
        m_axi_gmem4_RREADY = 1'b1;
    end else begin
        m_axi_gmem4_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        result_ce0 = 1'b1;
    end else begin
        result_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (icmp_ln29_1_reg_1092_pp0_iter19_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        result_we0 = 1'b1;
    end else begin
        result_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w_0_ce0 = 1'b1;
    end else begin
        w_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w_1_ce0 = 1'b1;
    end else begin
        w_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w_2_ce0 = 1'b1;
    end else begin
        w_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w_3_ce0 = 1'b1;
    end else begin
        w_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w_4_ce0 = 1'b1;
    end else begin
        w_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w_5_ce0 = 1'b1;
    end else begin
        w_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w_6_ce0 = 1'b1;
    end else begin
        w_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w_7_ce0 = 1'b1;
    end else begin
        w_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_0_ce0 = 1'b1;
    end else begin
        x_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_1_ce0 = 1'b1;
    end else begin
        x_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_2_ce0 = 1'b1;
    end else begin
        x_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_3_ce0 = 1'b1;
    end else begin
        x_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_4_ce0 = 1'b1;
    end else begin
        x_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_5_ce0 = 1'b1;
    end else begin
        x_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_6_ce0 = 1'b1;
    end else begin
        x_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_7_ce0 = 1'b1;
    end else begin
        x_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln19_1_fu_609_p2 = (ap_sig_allocacmp_indvar_flatten_load + 10'd1);

assign add_ln19_fu_621_p2 = (ap_sig_allocacmp_o_load + 7'd1);

assign add_ln29_fu_773_p2 = (select_ln19_fu_633_p3 + 4'd1);

assign add_ln35_1_fu_670_p2 = (zext_ln35_8 + zext_ln35_9_fu_666_p1);

assign add_ln35_2_fu_681_p2 = (zext_ln35_7 + zext_ln35_9_fu_666_p1);

assign add_ln35_3_fu_692_p2 = (zext_ln35_6 + zext_ln35_9_fu_666_p1);

assign add_ln35_4_fu_703_p2 = (zext_ln35_5 + zext_ln35_9_fu_666_p1);

assign add_ln35_5_fu_714_p2 = (zext_ln35_4 + zext_ln35_9_fu_666_p1);

assign add_ln35_6_fu_725_p2 = (zext_ln35_3 + zext_ln35_9_fu_666_p1);

assign add_ln35_7_fu_736_p2 = (zext_ln35_2 + zext_ln35_9_fu_666_p1);

assign add_ln35_8_fu_747_p2 = (zext_ln35_1 + zext_ln35_9_fu_666_p1);

assign add_ln35_fu_762_p2 = (zext_ln29_fu_758_p1 + p_udiv_fu_658_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = ((icmp_ln29_1_reg_1092_pp0_iter3_reg == 1'd1) & (m_axi_gmem4_RVALID == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign empty_76_fu_654_p1 = select_ln19_9_fu_641_p3[5:0];

assign grp_fu_435_p0 = ((icmp_ln29_reg_1024_pp0_iter2_reg[0:0] == 1'b1) ? 32'd0 : ap_sig_allocacmp_p_load31);

assign grp_fu_439_p0 = ((icmp_ln29_reg_1024_pp0_iter4_reg[0:0] == 1'b1) ? 32'd0 : ap_sig_allocacmp_p_load30);

assign grp_fu_443_p0 = gmem4_addr_read_reg_1181;

assign grp_fu_447_p0 = ((icmp_ln29_reg_1024_pp0_iter6_reg[0:0] == 1'b1) ? 32'd0 : ap_sig_allocacmp_p_load29);

assign grp_fu_455_p0 = ((icmp_ln29_reg_1024_pp0_iter8_reg[0:0] == 1'b1) ? 32'd0 : ap_sig_allocacmp_p_load28);

assign grp_fu_463_p0 = ((icmp_ln29_reg_1024_pp0_iter10_reg[0:0] == 1'b1) ? 32'd0 : ap_sig_allocacmp_p_load27);

assign grp_fu_471_p0 = ((icmp_ln29_reg_1024_pp0_iter12_reg[0:0] == 1'b1) ? 32'd0 : ap_sig_allocacmp_p_load26);

assign grp_fu_479_p0 = ((icmp_ln29_reg_1024_pp0_iter14_reg[0:0] == 1'b1) ? 32'd0 : ap_sig_allocacmp_p_load25);

assign grp_fu_487_p0 = ((icmp_ln29_reg_1024_pp0_iter16_reg[0:0] == 1'b1) ? 32'd0 : ap_sig_allocacmp_p_load);

assign icmp_ln19_fu_603_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 10'd512) ? 1'b1 : 1'b0);

assign icmp_ln29_1_fu_779_p2 = ((add_ln29_fu_773_p2 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln29_fu_627_p2 = ((ap_sig_allocacmp_g_load == 4'd8) ? 1'b1 : 1'b0);

assign m_axi_gmem4_ARADDR = 64'd0;

assign m_axi_gmem4_ARBURST = 2'd0;

assign m_axi_gmem4_ARCACHE = 4'd0;

assign m_axi_gmem4_ARID = 1'd0;

assign m_axi_gmem4_ARLEN = 32'd0;

assign m_axi_gmem4_ARLOCK = 2'd0;

assign m_axi_gmem4_ARPROT = 3'd0;

assign m_axi_gmem4_ARQOS = 4'd0;

assign m_axi_gmem4_ARREGION = 4'd0;

assign m_axi_gmem4_ARSIZE = 3'd0;

assign m_axi_gmem4_ARUSER = 1'd0;

assign m_axi_gmem4_ARVALID = 1'b0;

assign m_axi_gmem4_AWADDR = 64'd0;

assign m_axi_gmem4_AWBURST = 2'd0;

assign m_axi_gmem4_AWCACHE = 4'd0;

assign m_axi_gmem4_AWID = 1'd0;

assign m_axi_gmem4_AWLEN = 32'd0;

assign m_axi_gmem4_AWLOCK = 2'd0;

assign m_axi_gmem4_AWPROT = 3'd0;

assign m_axi_gmem4_AWQOS = 4'd0;

assign m_axi_gmem4_AWREGION = 4'd0;

assign m_axi_gmem4_AWSIZE = 3'd0;

assign m_axi_gmem4_AWUSER = 1'd0;

assign m_axi_gmem4_AWVALID = 1'b0;

assign m_axi_gmem4_BREADY = 1'b0;

assign m_axi_gmem4_WDATA = 32'd0;

assign m_axi_gmem4_WID = 1'd0;

assign m_axi_gmem4_WLAST = 1'b0;

assign m_axi_gmem4_WSTRB = 4'd0;

assign m_axi_gmem4_WUSER = 1'd0;

assign m_axi_gmem4_WVALID = 1'b0;

assign p_udiv_fu_658_p3 = {{empty_76_fu_654_p1}, {3'd0}};

assign result_address0 = result_addr_reg_1096_pp0_iter19_reg;

assign result_d0 = grp_fu_495_p2;

assign select_ln19_9_fu_641_p3 = ((icmp_ln29_fu_627_p2[0:0] == 1'b1) ? add_ln19_fu_621_p2 : ap_sig_allocacmp_o_load);

assign select_ln19_fu_633_p3 = ((icmp_ln29_fu_627_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_g_load);

assign w_0_address0 = zext_ln35_fu_768_p1;

assign w_1_address0 = zext_ln35_reg_1076_pp0_iter1_reg;

assign w_2_address0 = zext_ln35_reg_1076_pp0_iter3_reg;

assign w_3_address0 = zext_ln35_reg_1076_pp0_iter5_reg;

assign w_4_address0 = zext_ln35_reg_1076_pp0_iter7_reg;

assign w_5_address0 = zext_ln35_reg_1076_pp0_iter9_reg;

assign w_6_address0 = zext_ln35_reg_1076_pp0_iter11_reg;

assign w_7_address0 = zext_ln35_reg_1076_pp0_iter13_reg;

assign x_0_address0 = zext_ln35_10_fu_676_p1;

assign x_1_address0 = zext_ln35_11_fu_687_p1;

assign x_2_address0 = zext_ln35_12_fu_698_p1;

assign x_3_address0 = zext_ln35_13_fu_709_p1;

assign x_4_address0 = zext_ln35_14_fu_720_p1;

assign x_5_address0 = zext_ln35_15_fu_731_p1;

assign x_6_address0 = zext_ln35_16_fu_742_p1;

assign x_7_address0 = zext_ln35_17_fu_753_p1;

assign zext_ln19_fu_649_p1 = select_ln19_9_fu_641_p3;

assign zext_ln29_fu_758_p1 = select_ln19_fu_633_p3;

assign zext_ln35_10_fu_676_p1 = add_ln35_1_fu_670_p2;

assign zext_ln35_11_fu_687_p1 = add_ln35_2_fu_681_p2;

assign zext_ln35_12_fu_698_p1 = add_ln35_3_fu_692_p2;

assign zext_ln35_13_fu_709_p1 = add_ln35_4_fu_703_p2;

assign zext_ln35_14_fu_720_p1 = add_ln35_5_fu_714_p2;

assign zext_ln35_15_fu_731_p1 = add_ln35_6_fu_725_p2;

assign zext_ln35_16_fu_742_p1 = add_ln35_7_fu_736_p2;

assign zext_ln35_17_fu_753_p1 = add_ln35_8_fu_747_p2;

assign zext_ln35_9_fu_666_p1 = select_ln19_fu_633_p3;

assign zext_ln35_fu_768_p1 = add_ln35_fu_762_p2;

always @ (posedge ap_clk) begin
    zext_ln35_reg_1076[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln35_reg_1076_pp0_iter1_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln35_reg_1076_pp0_iter2_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln35_reg_1076_pp0_iter3_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln35_reg_1076_pp0_iter4_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln35_reg_1076_pp0_iter5_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln35_reg_1076_pp0_iter6_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln35_reg_1076_pp0_iter7_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln35_reg_1076_pp0_iter8_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln35_reg_1076_pp0_iter9_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln35_reg_1076_pp0_iter10_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln35_reg_1076_pp0_iter11_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln35_reg_1076_pp0_iter12_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln35_reg_1076_pp0_iter13_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
end

endmodule //pseudo_moe_compute_expert_Pipeline_VITIS_LOOP_19_1_VITIS_LOOP_29_3
