-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_generic_mlp_head33_Pipeline_VITIS_LOOP_736_3_p_ZL10e0_bram_w1_4_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_generic_mlp_head33_Pipeline_VITIS_LOOP_736_3_p_ZL10e0_bram_w1_4_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10110001001111000111000110100101", 1 => "10101010111000011000000011010001", 2 => "10101001110111011100010011100100", 3 => "10110010101011100011110011110110", 
    4 => "10110001110010010000011001111011", 5 => "00100111110110011000100111100110", 6 => "10011010000011111010101001111101", 7 => "10110100110011110111010101011100", 
    8 => "00110110011010011101100100010000", 9 => "10110010111111101011001111011110", 10 => "00101111011000011000010110100100", 11 => "10100001100011011010110101100000", 
    12 => "00100100110000001000011000001010", 13 => "00111000000010100101111110000101", 14 => "00111000100100001101010001011011", 15 => "10110011100110100000111010000011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

