-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_generic_mlp_head39_Pipeline_VITIS_LOOP_736_3_p_ZL10e1_perf_w1_12_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_generic_mlp_head39_Pipeline_VITIS_LOOP_736_3_p_ZL10e1_perf_w1_12_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111110001100101100111111000101", 1 => "00111111000111010111010101101101", 2 => "10111101010000010111101000001111", 3 => "00111101100111111100100010101101", 
    4 => "00111101101001111111110111001110", 5 => "00111010110000000001010010010110", 6 => "00111110000011101110101111011100", 7 => "10111110001111100110100010000001", 
    8 => "00111101100111000100111110011010", 9 => "10111101000101010000001001001011", 10 => "10111101111001111011100000100110", 11 => "00111110001100101010111101100110", 
    12 => "00111110100100001010111000010100", 13 => "10111110101011001110011011001000", 14 => "00111101011111100100100011100110", 15 => "10111110100110000100101011001010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

