-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_generic_mlp_head36_Pipeline_VITIS_LOOP_736_3_p_ZL8e2_ff_w1_0_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_generic_mlp_head36_Pipeline_VITIS_LOOP_736_3_p_ZL8e2_ff_w1_0_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101001000101111011101000110", 1 => "00111100101000111110100101111000", 2 => "10111110001011111110100111000111", 3 => "00111011000100011011111000000101", 
    4 => "00111011110000011111111001010000", 5 => "00111100010110000100111110010010", 6 => "00111010100000101001110010010011", 7 => "10111001100101010111100101100100", 
    8 => "00111011100011111100100110011010", 9 => "10111011001010010100010011101000", 10 => "00111100010111001101010111101010", 11 => "00111011010101000000011001000111", 
    12 => "00111110001101100000010101111001", 13 => "00111100010101111100101001110110", 14 => "00111010100011010010010110000101", 15 => "00111011100100001010010000010000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

