-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_mlp_head451_Pipeline_VITIS_LOOP_586_3_p_ZL8e3_ff_w1_4_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_mlp_head451_Pipeline_VITIS_LOOP_586_3_p_ZL8e3_ff_w1_4_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101011100010011001001100101", 1 => "10111101100110110001010110100000", 2 => "00111101010100010001000011011010", 3 => "00111100101011100110100110001100", 
    4 => "00111100100111111110011110011000", 5 => "00111110100110100100011110001101", 6 => "00111011101101011000101101101000", 7 => "10111101100111000000100100111011", 
    8 => "10111101001110000100101001101110", 9 => "10111110100011010011001101110100", 10 => "00111011000111100001100101101000", 11 => "10111011000000100111010110110010", 
    12 => "10111101101011111010011100101011", 13 => "00111100101110010110010001100100", 14 => "10111100010001111111110101010100", 15 => "00111100111011011000010011110001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

