-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_mlp_head453_e3_perf_b0_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_mlp_head453_e3_perf_b0_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111100101010010101011111010110", 1 => "10111010010001001110111100111010", 2 => "00111101101001110001111110111010", 3 => "00111101000000100111001110001110", 
    4 => "00111100110101011001100010100100", 5 => "00111101100011101000001100101000", 6 => "00111101100100101110001101010001", 7 => "10111011101010101110100011001100", 
    8 => "10111100101101100101010010000111", 9 => "10111101100000010110111000100101", 10 => "00111100100100011111110000100111", 11 => "10111101100110100101011010101111", 
    12 => "00111101001100100000100110101111", 13 => "10111101100011110110000110000000", 14 => "10111101101111011001100110010010", 15 => "10111101001101011111111100001001", 
    16 => "10111100110111100101011100000111", 17 => "10111101001100110011010001001010", 18 => "10111101000010011100001000010001", 19 => "10111101000000000001010110010100", 
    20 => "00111101001001010100001110000100", 21 => "10111101001001000101111111111110", 22 => "00111101101101001001101101001011", 23 => "00111100100000000110001011101110", 
    24 => "00111011111000110001100011110000", 25 => "10111101010100100010111100110101", 26 => "00111101011100110000100011001001", 27 => "00111101000011100000001110111100", 
    28 => "10111101100110001010110000010101", 29 => "00111100100110111111111100100011", 30 => "10111101111101000001100011111001", 31 => "00111100010001111001100110111100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

