-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_mlp_head482_Pipeline_VITIS_LOOP_586_3_p_ZL9e1_lut_w1_17_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_mlp_head482_Pipeline_VITIS_LOOP_586_3_p_ZL9e1_lut_w1_17_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101111010100010001100011010", 1 => "00111100101100000100101001000010", 2 => "00111110010110100011010011011000", 3 => "00111010001011010010101000011011", 
    4 => "00111101111110110101111100001010", 5 => "00111101010111110000001011111111", 6 => "10111101000101001101101110010000", 7 => "10111101000011011110011010011010", 
    8 => "00111101111010111110011001010001", 9 => "10111011111100101001010001100011", 10 => "00111110010001001001011111101011", 11 => "10111100010100111101000101100111", 
    12 => "00111110001100100101101000001011", 13 => "10111101010010010011101101111001", 14 => "00111101110001110111010001110111", 15 => "00111101110011010001001000110010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

