-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_mlp_head452_Pipeline_VITIS_LOOP_586_3_p_ZL9e3_lut_w1_2_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_mlp_head452_Pipeline_VITIS_LOOP_586_3_p_ZL9e3_lut_w1_2_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111110100000101111011011111000", 1 => "00111110000110111011100001101001", 2 => "00111100001100111000010001010010", 3 => "10111110001001100001111011111000", 
    4 => "00111110000101101110011001110010", 5 => "00111100001101001010101101100101", 6 => "10111101010010011100111001111111", 7 => "00111110110010001100111111111110", 
    8 => "00111101011111111111000000010111", 9 => "00111100000001010000100000000110", 10 => "10111110011011110101010101111010", 11 => "10111011101111000100011110110110", 
    12 => "00111101101111000111110011100011", 13 => "10111101111111001111000001101010", 14 => "00111101100011110010100001000000", 15 => "00111100010111001000010111000100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

