-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_mlp_head483_Pipeline_VITIS_LOOP_586_3_p_ZL10e1_perf_w1_25_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_mlp_head483_Pipeline_VITIS_LOOP_586_3_p_ZL10e1_perf_w1_25_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111100110110100101011011110010", 1 => "10111100010110101101111010011110", 2 => "00111100011111001100001100100110", 3 => "00111110110101110011110111001001", 
    4 => "00111101110000010110010111000010", 5 => "10111110011000001100000110001110", 6 => "10111101011101001011110001111000", 7 => "00111110010011111111110100111010", 
    8 => "10111101110101000101001110111101", 9 => "00111100111010001101010011000101", 10 => "10111001010111011100001111101110", 11 => "00111101000110101101000000100010", 
    12 => "10111110010001100101010111110010", 13 => "00111100100100001101101001010001", 14 => "10111101100000000001101000111101", 15 => "10111110000000010101000011010111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

