-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_mlp_head445_Pipeline_VITIS_LOOP_586_3_p_ZL8e0_ff_w1_20_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_mlp_head445_Pipeline_VITIS_LOOP_586_3_p_ZL8e0_ff_w1_20_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111011111101001011010111000110", 1 => "10111010011111010111000110001001", 2 => "10111011011100001010011111001010", 3 => "00110011110111000001100000111100", 
    4 => "10111000101101110001110101100110", 5 => "00111010001001000100010101110011", 6 => "00110111010010011001001000100111", 7 => "10110111100000101111010010101011", 
    8 => "10110111100111010000000010110001", 9 => "10111001101011100111011101011100", 10 => "10111001001011100001010010101010", 11 => "10111000100100011000101001001110", 
    12 => "10111010010110011110111010010010", 13 => "00111010101110011001011011011010", 14 => "10110110101111001101011110010111", 15 => "10110101110010110010111011101111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

