-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_expert_engine_p_ZL10e2_bram_w1_15_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_expert_engine_p_ZL10e2_bram_w1_15_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00110111100100111100001010100100", 1 => "00111001111000011011100011111010", 2 => "10111010001101101010001101111010", 3 => "10110111011110101011000110100110", 
    4 => "10111001000110011110100010111001", 5 => "00111010001100000000010010111000", 6 => "10111011100110001001100010011100", 7 => "10111001000000001001110100010100", 
    8 => "10111011111011001101110110000101", 9 => "00111001110101100110110110010110", 10 => "10110111100001001101010011111010", 11 => "10111001000101010100010110100100", 
    12 => "00110011101010001100000111110100", 13 => "10111010111110100100010010001111", 14 => "10111011100010100111110110000011", 15 => "10110111110110011111100101110011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

