-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_expert_engine_p_ZL10e2_perf_w1_9_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_expert_engine_p_ZL10e2_perf_w1_9_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101010011100111011010101001", 1 => "00111110001110110010010100111000", 2 => "10111110000100100000101111011010", 3 => "00111101101111110111011011111000", 
    4 => "10111110000111010000011111111010", 5 => "00111101000001110101011010110100", 6 => "10111111000001010010110001100000", 7 => "10111101111010010010110011001101", 
    8 => "10111101010111101101001000100100", 9 => "00111101011000000101110011100111", 10 => "10111110101100011001100111110011", 11 => "10111100100101001001110001010010", 
    12 => "00111110101000111111011000110110", 13 => "10111101110001100111001011101000", 14 => "00111110111011111110100111011000", 15 => "00111110011101110001011010111000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

