-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_mlp_head482_Pipeline_VITIS_LOOP_586_3_p_ZL9e1_lut_w1_22_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_mlp_head482_Pipeline_VITIS_LOOP_586_3_p_ZL9e1_lut_w1_22_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101011101010001000110001110", 1 => "10111100100010010111011011100111", 2 => "00111100111111000100011100110011", 3 => "00111100110101011101000011010011", 
    4 => "00111101000010011001100100001001", 5 => "00111100000101001110100010001000", 6 => "00111100110101001001111111101010", 7 => "10111100110111100011101111111000", 
    8 => "00111100110011100000001100001001", 9 => "10111100100110100011111011101010", 10 => "00111101000000110101001101011000", 11 => "10111011100001001010101110111000", 
    12 => "00111101100101011011100110100101", 13 => "00111100011000011011100011010000", 14 => "00111101001111110010001001111010", 15 => "00111011110101001101111111110010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

