-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_mlp_head451_Pipeline_VITIS_LOOP_586_3_p_ZL8e3_ff_w1_16_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_mlp_head451_Pipeline_VITIS_LOOP_586_3_p_ZL8e3_ff_w1_16_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101100101011101101011000000", 1 => "10111101111111001001010111001000", 2 => "10111101001001000000011101111101", 3 => "00111100000011110111000110000000", 
    4 => "00111100101001010100111011010010", 5 => "00111101101110000111110010010110", 6 => "00111010101010111100010010000110", 7 => "10111101011111000001011110110111", 
    8 => "00111100101010110000000100010110", 9 => "00111011100001011100011001001000", 10 => "00111100000001010100010010011001", 11 => "10111010101001100011000010010111", 
    12 => "10111110010000111100001000101111", 13 => "00111110010011000011010110010100", 14 => "10111011110100010110101011010011", 15 => "00111101101011110011111011000101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

