-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_mlp_head445_Pipeline_VITIS_LOOP_586_3_p_ZL8e0_ff_w1_7_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_mlp_head445_Pipeline_VITIS_LOOP_586_3_p_ZL8e0_ff_w1_7_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111110100101001000000010011100", 1 => "10111110010110001100010110000111", 2 => "10111110101001011000100000011000", 3 => "00111000010111101100110100010001", 
    4 => "00111011011010011011100001011110", 5 => "10111110000011111100110110000010", 6 => "10111010010011111101111001001010", 7 => "10111000110110101100001000010111", 
    8 => "00111011000010000000110101110100", 9 => "00111100100010010100111000101110", 10 => "00111011110000001100100000000011", 11 => "00111011110001010100011110111011", 
    12 => "10111101001110100101000101100111", 13 => "10111100110001101011111000110110", 14 => "00111001000011010010011110010111", 15 => "00111001110101011111000000011010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

