set SynModuleInfo {
  {SRCNAME output_moe_Pipeline_VITIS_LOOP_998_2 MODELNAME output_moe_Pipeline_VITIS_LOOP_998_2 RTLNAME output_moe_output_moe_Pipeline_VITIS_LOOP_998_2
    SUBMODULES {
      {MODELNAME output_moe_output_moe_Pipeline_VITIS_LOOP_998_2_gate_weight_0_ROM_AUTO_1R RTLNAME output_moe_output_moe_Pipeline_VITIS_LOOP_998_2_gate_weight_0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_flow_control_loop_pipe_sequential_init RTLNAME output_moe_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME output_moe_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME output_moe_Pipeline_VITIS_LOOP_998_21 MODELNAME output_moe_Pipeline_VITIS_LOOP_998_21 RTLNAME output_moe_output_moe_Pipeline_VITIS_LOOP_998_21
    SUBMODULES {
      {MODELNAME output_moe_output_moe_Pipeline_VITIS_LOOP_998_21_gate_weight_1_ROM_AUTO_1R RTLNAME output_moe_output_moe_Pipeline_VITIS_LOOP_998_21_gate_weight_1_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME output_moe_Pipeline_VITIS_LOOP_998_22 MODELNAME output_moe_Pipeline_VITIS_LOOP_998_22 RTLNAME output_moe_output_moe_Pipeline_VITIS_LOOP_998_22
    SUBMODULES {
      {MODELNAME output_moe_output_moe_Pipeline_VITIS_LOOP_998_22_gate_weight_2_ROM_AUTO_1R RTLNAME output_moe_output_moe_Pipeline_VITIS_LOOP_998_22_gate_weight_2_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME output_moe_Pipeline_VITIS_LOOP_998_23 MODELNAME output_moe_Pipeline_VITIS_LOOP_998_23 RTLNAME output_moe_output_moe_Pipeline_VITIS_LOOP_998_23
    SUBMODULES {
      {MODELNAME output_moe_output_moe_Pipeline_VITIS_LOOP_998_23_gate_weight_3_ROM_AUTO_1R RTLNAME output_moe_output_moe_Pipeline_VITIS_LOOP_998_23_gate_weight_3_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_2 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_2 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_2}
  {SRCNAME elu MODELNAME elu RTLNAME output_moe_elu
    SUBMODULES {
      {MODELNAME output_moe_fcmp_32ns_32ns_1_1_no_dsp_1 RTLNAME output_moe_fcmp_32ns_32ns_1_1_no_dsp_1 BINDTYPE op TYPE fcmp IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_fexp_32ns_32ns_32_4_full_dsp_1 RTLNAME output_moe_fexp_32ns_32ns_32_4_full_dsp_1 BINDTYPE op TYPE fexp IMPL fulldsp LATENCY 3 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_243 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_243 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_243}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_244 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_244 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_244}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_245 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_245 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_245}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_246 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_246 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_246}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_247 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_247 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_247}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_248 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_248 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_248}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_249 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_249 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_249}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_250 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_250 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_250}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_251 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_251 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_251}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_252 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_252 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_252}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_253 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_253 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_253}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_254 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_254 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_254}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_255 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_255 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_255}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_256 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_256 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_256}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_257 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_257 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_257}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_258 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_258 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_258}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_259 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_259 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_259}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_260 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_260 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_260}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_261 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_261 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_261}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_262 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_262 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_262}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_263 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_263 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_263}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_264 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_264 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_264}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_265 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_265 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_265}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_266 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_266 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_266}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_267 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_267 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_267}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_268 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_268 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_268}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_269 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_269 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_269}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_270 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_270 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_270}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_271 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_271 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_271}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_272 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_272 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_272}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_273 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_273 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_273}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_274 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_274 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_274}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_275 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_275 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_275}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_276 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_276 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_276}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_277 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_277 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_277}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_278 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_278 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_278}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_279 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_279 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_279}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_280 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_280 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_280}
  {SRCNAME expert_engine_A_Pipeline_VITIS_LOOP_598_281 MODELNAME expert_engine_A_Pipeline_VITIS_LOOP_598_281 RTLNAME output_moe_expert_engine_A_Pipeline_VITIS_LOOP_598_281}
  {SRCNAME expert_engine_A MODELNAME expert_engine_A RTLNAME output_moe_expert_engine_A
    SUBMODULES {
      {MODELNAME output_moe_fadd_32ns_32ns_32_2_full_dsp_1 RTLNAME output_moe_fadd_32ns_32ns_32_2_full_dsp_1 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_A_e0_perf_b0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_A_e0_perf_b0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_A_e0_perf_w0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_A_e0_perf_w0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_A_e0_lut_b0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_A_e0_lut_b0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_A_e0_lut_w0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_A_e0_lut_w0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_A_e0_ff_b0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_A_e0_ff_b0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_A_e0_ff_w0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_A_e0_ff_w0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_A_e0_dsp_b0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_A_e0_dsp_b0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_A_e0_dsp_w0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_A_e0_dsp_w0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_A_e0_bram_b0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_A_e0_bram_b0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_A_e0_bram_w0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_A_e0_bram_w0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_A_e2_perf_b0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_A_e2_perf_b0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_A_e2_perf_w0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_A_e2_perf_w0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_A_e2_lut_b0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_A_e2_lut_b0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_A_e2_lut_w0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_A_e2_lut_w0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_A_e2_ff_b0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_A_e2_ff_b0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_A_e2_ff_w0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_A_e2_ff_w0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_A_e2_dsp_b0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_A_e2_dsp_b0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_A_e2_dsp_w0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_A_e2_dsp_w0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_A_e2_bram_b0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_A_e2_bram_b0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_A_e2_bram_w0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_A_e2_bram_w0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_A_l0_RAM_AUTO_1R1W RTLNAME output_moe_expert_engine_A_l0_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_2 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_2 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_2}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_24 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_24 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_24}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_25 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_25 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_25}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_26 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_26 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_26}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_27 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_27 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_27}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_28 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_28 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_28}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_29 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_29 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_29}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_210 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_210 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_210}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_211 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_211 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_211}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_212 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_212 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_212}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_213 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_213 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_213}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_214 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_214 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_214}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_215 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_215 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_215}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_216 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_216 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_216}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_217 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_217 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_217}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_218 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_218 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_218}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_219 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_219 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_219}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_220 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_220 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_220}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_221 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_221 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_221}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_222 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_222 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_222}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_223 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_223 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_223}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_224 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_224 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_224}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_225 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_225 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_225}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_226 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_226 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_226}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_227 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_227 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_227}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_228 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_228 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_228}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_229 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_229 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_229}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_230 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_230 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_230}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_231 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_231 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_231}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_232 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_232 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_232}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_233 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_233 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_233}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_234 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_234 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_234}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_235 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_235 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_235}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_236 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_236 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_236}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_237 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_237 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_237}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_238 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_238 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_238}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_239 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_239 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_239}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_240 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_240 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_240}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_241 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_241 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_241}
  {SRCNAME expert_engine_B_Pipeline_VITIS_LOOP_598_242 MODELNAME expert_engine_B_Pipeline_VITIS_LOOP_598_242 RTLNAME output_moe_expert_engine_B_Pipeline_VITIS_LOOP_598_242}
  {SRCNAME expert_engine_B MODELNAME expert_engine_B RTLNAME output_moe_expert_engine_B
    SUBMODULES {
      {MODELNAME output_moe_expert_engine_B_e1_perf_b0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_B_e1_perf_b0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_B_e1_perf_w0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_B_e1_perf_w0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_B_e1_lut_b0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_B_e1_lut_b0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_B_e1_lut_w0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_B_e1_lut_w0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_B_e1_ff_b0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_B_e1_ff_b0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_B_e1_ff_w0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_B_e1_ff_w0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_B_e1_dsp_b0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_B_e1_dsp_b0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_B_e1_dsp_w0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_B_e1_dsp_w0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_B_e1_bram_b0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_B_e1_bram_b0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_B_e1_bram_w0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_B_e1_bram_w0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_B_e3_perf_b0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_B_e3_perf_b0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_B_e3_perf_w0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_B_e3_perf_w0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_B_e3_lut_b0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_B_e3_lut_b0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_B_e3_lut_w0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_B_e3_lut_w0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_B_e3_ff_b0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_B_e3_ff_b0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_B_e3_ff_w0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_B_e3_ff_w0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_B_e3_dsp_b0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_B_e3_dsp_b0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_B_e3_dsp_w0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_B_e3_dsp_w0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_B_e3_bram_b0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_B_e3_bram_b0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_expert_engine_B_e3_bram_w0_ROM_AUTO_1R RTLNAME output_moe_expert_engine_B_e3_bram_w0_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME run_parallel_engines_Block_entry2326_proc MODELNAME run_parallel_engines_Block_entry2326_proc RTLNAME output_moe_run_parallel_engines_Block_entry2326_proc}
  {SRCNAME run_parallel_engines_Block_entry2327_proc MODELNAME run_parallel_engines_Block_entry2327_proc RTLNAME output_moe_run_parallel_engines_Block_entry2327_proc}
  {SRCNAME run_parallel_engines MODELNAME run_parallel_engines RTLNAME output_moe_run_parallel_engines
    SUBMODULES {
      {MODELNAME output_moe_fifo_w32_d2_S RTLNAME output_moe_fifo_w32_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME a_out_0_U}
      {MODELNAME output_moe_fifo_w32_d2_S RTLNAME output_moe_fifo_w32_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME a_out_1_U}
      {MODELNAME output_moe_fifo_w32_d2_S RTLNAME output_moe_fifo_w32_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME a_out_0_1_U}
      {MODELNAME output_moe_fifo_w32_d2_S RTLNAME output_moe_fifo_w32_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME a_out_1_1_U}
      {MODELNAME output_moe_fifo_w32_d2_S RTLNAME output_moe_fifo_w32_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME a_out_0_2_U}
      {MODELNAME output_moe_fifo_w32_d2_S RTLNAME output_moe_fifo_w32_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME a_out_1_2_U}
      {MODELNAME output_moe_fifo_w32_d2_S RTLNAME output_moe_fifo_w32_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME a_out_0_3_U}
      {MODELNAME output_moe_fifo_w32_d2_S RTLNAME output_moe_fifo_w32_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME a_out_1_3_U}
      {MODELNAME output_moe_fifo_w32_d2_S RTLNAME output_moe_fifo_w32_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME a_out_0_4_U}
      {MODELNAME output_moe_fifo_w32_d2_S RTLNAME output_moe_fifo_w32_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME a_out_1_4_U}
      {MODELNAME output_moe_fifo_w32_d3_S RTLNAME output_moe_fifo_w32_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME b_out_0_U}
      {MODELNAME output_moe_fifo_w32_d3_S RTLNAME output_moe_fifo_w32_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME b_out_1_U}
      {MODELNAME output_moe_fifo_w32_d3_S RTLNAME output_moe_fifo_w32_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME b_out_0_1_U}
      {MODELNAME output_moe_fifo_w32_d3_S RTLNAME output_moe_fifo_w32_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME b_out_1_1_U}
      {MODELNAME output_moe_fifo_w32_d3_S RTLNAME output_moe_fifo_w32_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME b_out_0_2_U}
      {MODELNAME output_moe_fifo_w32_d3_S RTLNAME output_moe_fifo_w32_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME b_out_1_2_U}
      {MODELNAME output_moe_fifo_w32_d3_S RTLNAME output_moe_fifo_w32_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME b_out_0_3_U}
      {MODELNAME output_moe_fifo_w32_d3_S RTLNAME output_moe_fifo_w32_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME b_out_1_3_U}
      {MODELNAME output_moe_fifo_w32_d3_S RTLNAME output_moe_fifo_w32_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME b_out_0_4_U}
      {MODELNAME output_moe_fifo_w32_d3_S RTLNAME output_moe_fifo_w32_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME b_out_1_4_U}
      {MODELNAME output_moe_fifo_w32_d2_S RTLNAME output_moe_fifo_w32_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME a_out_0_load_loc_channel_U}
      {MODELNAME output_moe_fifo_w32_d2_S RTLNAME output_moe_fifo_w32_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME a_out_1_load_loc_channel_U}
      {MODELNAME output_moe_fifo_w32_d2_S RTLNAME output_moe_fifo_w32_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME a_out_0_1_load_loc_channel_U}
      {MODELNAME output_moe_fifo_w32_d2_S RTLNAME output_moe_fifo_w32_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME a_out_1_1_load_loc_channel_U}
      {MODELNAME output_moe_fifo_w32_d2_S RTLNAME output_moe_fifo_w32_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME a_out_0_2_load_loc_channel_U}
      {MODELNAME output_moe_fifo_w32_d2_S RTLNAME output_moe_fifo_w32_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME a_out_1_2_load_loc_channel_U}
      {MODELNAME output_moe_fifo_w32_d2_S RTLNAME output_moe_fifo_w32_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME a_out_0_3_load_loc_channel_U}
      {MODELNAME output_moe_fifo_w32_d2_S RTLNAME output_moe_fifo_w32_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME a_out_1_3_load_loc_channel_U}
      {MODELNAME output_moe_fifo_w32_d2_S RTLNAME output_moe_fifo_w32_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME a_out_0_4_load_loc_channel_U}
      {MODELNAME output_moe_fifo_w32_d2_S RTLNAME output_moe_fifo_w32_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME a_out_1_4_load_loc_channel_U}
    }
  }
  {SRCNAME output_moe MODELNAME output_moe RTLNAME output_moe IS_TOP 1
    SUBMODULES {
      {MODELNAME output_moe_faddfsub_32ns_32ns_32_2_full_dsp_1 RTLNAME output_moe_faddfsub_32ns_32ns_32_2_full_dsp_1 BINDTYPE op TYPE fsub IMPL fulldsp LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_fmul_32ns_32ns_32_2_max_dsp_1 RTLNAME output_moe_fmul_32ns_32ns_32_2_max_dsp_1 BINDTYPE op TYPE fmul IMPL maxdsp LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME output_moe_fdiv_32ns_32ns_32_6_no_dsp_1 RTLNAME output_moe_fdiv_32ns_32ns_32_6_no_dsp_1 BINDTYPE op TYPE fdiv IMPL fabric LATENCY 5 ALLOW_PRAGMA 1}
    }
  }
}
