#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("input_r_address0", 7, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("input_r_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("input_r_q0", 32, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("input_r_address1", 7, hls_out, 0, "ap_memory", "MemPortADDR2", 1),
	Port_Property("input_r_ce1", 1, hls_out, 0, "ap_memory", "MemPortCE2", 1),
	Port_Property("input_r_q1", 32, hls_in, 0, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("output_0", 32, hls_out, 1, "ap_vld", "out_data", 1),
	Port_Property("output_0_ap_vld", 1, hls_out, 1, "ap_vld", "out_vld", 1),
	Port_Property("output_1", 32, hls_out, 2, "ap_vld", "out_data", 1),
	Port_Property("output_1_ap_vld", 1, hls_out, 2, "ap_vld", "out_vld", 1),
	Port_Property("output_2", 32, hls_out, 3, "ap_vld", "out_data", 1),
	Port_Property("output_2_ap_vld", 1, hls_out, 3, "ap_vld", "out_vld", 1),
	Port_Property("output_3", 32, hls_out, 4, "ap_vld", "out_data", 1),
	Port_Property("output_3_ap_vld", 1, hls_out, 4, "ap_vld", "out_vld", 1),
	Port_Property("output_4", 32, hls_out, 5, "ap_vld", "out_data", 1),
	Port_Property("output_4_ap_vld", 1, hls_out, 5, "ap_vld", "out_vld", 1),
	Port_Property("gates_0_i", 32, hls_in, 6, "ap_ovld", "in_data", 1),
	Port_Property("gates_0_o", 32, hls_out, 6, "ap_ovld", "out_data", 1),
	Port_Property("gates_0_o_ap_vld", 1, hls_out, 6, "ap_ovld", "out_vld", 1),
	Port_Property("gates_1_i", 32, hls_in, 7, "ap_ovld", "in_data", 1),
	Port_Property("gates_1_o", 32, hls_out, 7, "ap_ovld", "out_data", 1),
	Port_Property("gates_1_o_ap_vld", 1, hls_out, 7, "ap_ovld", "out_vld", 1),
	Port_Property("gates_2_i", 32, hls_in, 8, "ap_ovld", "in_data", 1),
	Port_Property("gates_2_o", 32, hls_out, 8, "ap_ovld", "out_data", 1),
	Port_Property("gates_2_o_ap_vld", 1, hls_out, 8, "ap_ovld", "out_vld", 1),
	Port_Property("gates_3_i", 32, hls_in, 9, "ap_ovld", "in_data", 1),
	Port_Property("gates_3_o", 32, hls_out, 9, "ap_ovld", "out_data", 1),
	Port_Property("gates_3_o_ap_vld", 1, hls_out, 9, "ap_ovld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "output_moe";
