-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_expert_engine_p_ZL10e1_perf_w1_22_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_expert_engine_p_ZL10e1_perf_w1_22_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111110011010100101000110110011", 1 => "00111101101010011110111110010010", 2 => "00111110001101011100100111100110", 3 => "00111101110000110101110011110011", 
    4 => "00111110101110000100101110010111", 5 => "00111101110100110101110001010010", 6 => "10111110101001010100100010010011", 7 => "10111100110010010000001111001111", 
    8 => "00111110101000110101000100010001", 9 => "10111110001001110011000001101010", 10 => "10111101010110000110000100000101", 11 => "00111110100000100110001001111110", 
    12 => "10111110100011100010001100100001", 13 => "00111110001110110111001000110000", 14 => "10111101110101000110001011001010", 15 => "00111100010011010000011001000011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

