-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_expert_engine_p_ZL9e3_dsp_w1_18_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_expert_engine_p_ZL9e3_dsp_w1_18_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101001110101110010110100000", 1 => "00111110110111110010111000011110", 2 => "00111101100011001100011000011010", 3 => "10111110001010110100100010001100", 
    4 => "00111101011101001000011111111001", 5 => "00111101100100011100100111111011", 6 => "00111110000010001111100111101100", 7 => "10111110000110111011011111001110", 
    8 => "10111110100110101110101010111100", 9 => "10111110010110000101001100011111", 10 => "10111110000100100110100100010010", 11 => "00111110000101111011010100010110", 
    12 => "10111110101100000001001000111001", 13 => "00111101000100011001111101010100", 14 => "10111110001001010100010111110100", 15 => "10111101100001001010010101001010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

