-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_generic_mlp_head32_Pipeline_VITIS_LOOP_736_3_p_ZL9e0_dsp_w1_21_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_generic_mlp_head32_Pipeline_VITIS_LOOP_736_3_p_ZL9e0_dsp_w1_21_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111100011101010100000000001100", 1 => "10111100100010000000001100110001", 2 => "00111100100100010010111101001110", 3 => "10111101000000110111110110101010", 
    4 => "00111101010010000010011100001011", 5 => "00111100000110000000000101001111", 6 => "00111010101111001001111101000010", 7 => "10111001101000101000001110110100", 
    8 => "10111101000101010101010011011010", 9 => "10111100101001100000000010000110", 10 => "10111100111100011111011111101110", 11 => "10111101110001011001101110110100", 
    12 => "10111100011011011011010100000111", 13 => "10111101011111100110011111100110", 14 => "10111101101100110101101111100001", 15 => "10111100110001110110100110001111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

