-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_generic_mlp_head39_Pipeline_VITIS_LOOP_736_3_p_ZL10e1_perf_w1_27_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_generic_mlp_head39_Pipeline_VITIS_LOOP_736_3_p_ZL10e1_perf_w1_27_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111110011001111001001010010101", 1 => "00111110000100011100111011000111", 2 => "00111110000000010000110000100000", 3 => "10111110001110000000001110010111", 
    4 => "10111110000010111000110101010001", 5 => "10111110011101111010111001001100", 6 => "00111110000111011110110000001111", 7 => "10111101001101100110110101100110", 
    8 => "00111101100011111001011000110011", 9 => "10111101001010111110000110110100", 10 => "10111101000101100100010011001000", 11 => "00111101111111010101101100000000", 
    12 => "10111110010011001111110011011011", 13 => "00111101101100010100101010001100", 14 => "10111110111101000101010111100110", 15 => "10111100011100100001010110111110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

