-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_generic_mlp_head_Pipeline_VITIS_LOOP_736_3_p_ZL10e3_bram_w1_27_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_generic_mlp_head_Pipeline_VITIS_LOOP_736_3_p_ZL10e3_bram_w1_27_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111000110100101100100100011000", 1 => "10111011000000111110100100110100", 2 => "10110011011100101011010000011101", 3 => "10111101101000011101001110101001", 
    4 => "00111011111011000110001011001110", 5 => "10111101001100000000110011110110", 6 => "10111100011110110111001100011100", 7 => "00111001100110100000100111001100", 
    8 => "10111110000111011001000010100001", 9 => "10110110010110111010001001100001", 10 => "00111011000100110010110101000111", 11 => "00110110001011100000001011001101", 
    12 => "00110111100110110010011110011010", 13 => "00110010010100100010111111111010", 14 => "10110101111011100111101001111011", 15 => "00111001100110100000000010000010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

