-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_generic_mlp_head39_Pipeline_VITIS_LOOP_736_3_p_ZL10e1_perf_w1_18_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_generic_mlp_head39_Pipeline_VITIS_LOOP_736_3_p_ZL10e1_perf_w1_18_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101101111000111011111111001", 1 => "00111100111110010000111000001001", 2 => "10111110000001001010101001110000", 3 => "00111110001010010011011101000011", 
    4 => "10111110100111100101001010100100", 5 => "10111011001000000100001011011101", 6 => "10111100100000110101100101100001", 7 => "00111110110010100001100011010011", 
    8 => "00111110101001011010000110000111", 9 => "00111101110011011000111100010000", 10 => "00111100111001000001101101111100", 11 => "00111100011111010011011001000100", 
    12 => "00111101101100000101111101111111", 13 => "10111101010111110001001001000101", 14 => "00111101110001110011011101101001", 15 => "10111110000010000010010010100001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

