// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module output_moe_run_parallel_engines_Block_entry2335_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        out_0_address0,
        out_0_ce0,
        out_0_we0,
        out_0_d0,
        out_0_address1,
        out_0_ce1,
        out_0_we1,
        out_0_d1,
        p_read2,
        out_1_address0,
        out_1_ce0,
        out_1_we0,
        out_1_d0,
        out_1_address1,
        out_1_ce1,
        out_1_we1,
        out_1_d1,
        p_read3,
        out_2_address0,
        out_2_ce0,
        out_2_we0,
        out_2_d0,
        out_2_address1,
        out_2_ce1,
        out_2_we1,
        out_2_d1,
        p_read4,
        out_3_address0,
        out_3_ce0,
        out_3_we0,
        out_3_d0,
        out_3_address1,
        out_3_ce1,
        out_3_we1,
        out_3_d1,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] p_read;
input  [31:0] p_read1;
output  [2:0] out_0_address0;
output   out_0_ce0;
output   out_0_we0;
output  [31:0] out_0_d0;
output  [2:0] out_0_address1;
output   out_0_ce1;
output   out_0_we1;
output  [31:0] out_0_d1;
input  [31:0] p_read2;
output  [2:0] out_1_address0;
output   out_1_ce0;
output   out_1_we0;
output  [31:0] out_1_d0;
output  [2:0] out_1_address1;
output   out_1_ce1;
output   out_1_we1;
output  [31:0] out_1_d1;
input  [31:0] p_read3;
output  [2:0] out_2_address0;
output   out_2_ce0;
output   out_2_we0;
output  [31:0] out_2_d0;
output  [2:0] out_2_address1;
output   out_2_ce1;
output   out_2_we1;
output  [31:0] out_2_d1;
input  [31:0] p_read4;
output  [2:0] out_3_address0;
output   out_3_ce0;
output   out_3_we0;
output  [31:0] out_3_d0;
output  [2:0] out_3_address1;
output   out_3_ce1;
output   out_3_we1;
output  [31:0] out_3_d1;
input  [31:0] p_read5;
input  [31:0] p_read6;
input  [31:0] p_read7;
input  [31:0] p_read8;
input  [31:0] p_read9;
input  [31:0] p_read10;
input  [31:0] p_read11;
input  [31:0] p_read12;
input  [31:0] p_read13;
input  [31:0] p_read14;
input  [31:0] p_read15;
input  [31:0] p_read16;
input  [31:0] p_read17;
input  [31:0] p_read18;
input  [31:0] p_read19;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[2:0] out_0_address0;
reg out_0_ce0;
reg out_0_we0;
reg[31:0] out_0_d0;
reg[2:0] out_0_address1;
reg out_0_ce1;
reg out_0_we1;
reg[31:0] out_0_d1;
reg[2:0] out_1_address0;
reg out_1_ce0;
reg out_1_we0;
reg[31:0] out_1_d0;
reg[2:0] out_1_address1;
reg out_1_ce1;
reg out_1_we1;
reg[31:0] out_1_d1;
reg[2:0] out_2_address0;
reg out_2_ce0;
reg out_2_we0;
reg[31:0] out_2_d0;
reg[2:0] out_2_address1;
reg out_2_ce1;
reg out_2_we1;
reg[31:0] out_2_d1;
reg[2:0] out_3_address0;
reg out_3_ce0;
reg out_3_we0;
reg[31:0] out_3_d0;
reg[2:0] out_3_address1;
reg out_3_ce1;
reg out_3_we1;
reg[31:0] out_3_d1;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    ap_block_state1;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        out_0_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_0_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        out_0_address0 = 64'd0;
    end else begin
        out_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        out_0_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_0_address1 = 64'd1;
    end else begin
        out_0_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1)))) begin
        out_0_ce0 = 1'b1;
    end else begin
        out_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3))) begin
        out_0_ce1 = 1'b1;
    end else begin
        out_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        out_0_d0 = p_read14;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_0_d0 = p_read10;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        out_0_d0 = p_read2;
    end else begin
        out_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        out_0_d1 = p_read18;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_0_d1 = p_read6;
    end else begin
        out_0_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1)))) begin
        out_0_we0 = 1'b1;
    end else begin
        out_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3))) begin
        out_0_we1 = 1'b1;
    end else begin
        out_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        out_1_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_1_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        out_1_address0 = 64'd0;
    end else begin
        out_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        out_1_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_1_address1 = 64'd1;
    end else begin
        out_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1)))) begin
        out_1_ce0 = 1'b1;
    end else begin
        out_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3))) begin
        out_1_ce1 = 1'b1;
    end else begin
        out_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        out_1_d0 = p_read15;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_1_d0 = p_read11;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        out_1_d0 = p_read3;
    end else begin
        out_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        out_1_d1 = p_read;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_1_d1 = p_read7;
    end else begin
        out_1_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1)))) begin
        out_1_we0 = 1'b1;
    end else begin
        out_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3))) begin
        out_1_we1 = 1'b1;
    end else begin
        out_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        out_2_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_2_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        out_2_address0 = 64'd0;
    end else begin
        out_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        out_2_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_2_address1 = 64'd1;
    end else begin
        out_2_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1)))) begin
        out_2_ce0 = 1'b1;
    end else begin
        out_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3))) begin
        out_2_ce1 = 1'b1;
    end else begin
        out_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        out_2_d0 = p_read16;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_2_d0 = p_read12;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        out_2_d0 = p_read4;
    end else begin
        out_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        out_2_d1 = p_read19;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_2_d1 = p_read8;
    end else begin
        out_2_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1)))) begin
        out_2_we0 = 1'b1;
    end else begin
        out_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3))) begin
        out_2_we1 = 1'b1;
    end else begin
        out_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        out_3_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_3_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        out_3_address0 = 64'd0;
    end else begin
        out_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        out_3_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_3_address1 = 64'd1;
    end else begin
        out_3_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1)))) begin
        out_3_ce0 = 1'b1;
    end else begin
        out_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3))) begin
        out_3_ce1 = 1'b1;
    end else begin
        out_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        out_3_d0 = p_read17;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_3_d0 = p_read13;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        out_3_d0 = p_read5;
    end else begin
        out_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        out_3_d1 = p_read1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        out_3_d1 = p_read9;
    end else begin
        out_3_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1)))) begin
        out_3_we0 = 1'b1;
    end else begin
        out_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3))) begin
        out_3_we1 = 1'b1;
    end else begin
        out_3_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

endmodule //output_moe_run_parallel_engines_Block_entry2335_proc
