-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_mlp_head446_Pipeline_VITIS_LOOP_586_3_p_ZL9e0_lut_w1_18_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_mlp_head446_Pipeline_VITIS_LOOP_586_3_p_ZL9e0_lut_w1_18_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101111010110110000100110111", 1 => "00111100100000111010010111110010", 2 => "10111011000100011101000001000010", 3 => "10111100111101111011000001111010", 
    4 => "00111101011001010101010010011110", 5 => "00111100011010100110111110101001", 6 => "10111100001110000101000011010100", 7 => "10111010100000000101001100101000", 
    8 => "00111101101110110010111011101011", 9 => "00111011101001010011011011001111", 10 => "00111100010000110101100000101000", 11 => "10111101000010101010001011010101", 
    12 => "10111101001001111101011111111101", 13 => "10111011111101001010101011110101", 14 => "10111101000011000000110110101000", 15 => "00111100011101101111000111001111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

