-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_mlp_head443_Pipeline_VITIS_LOOP_586_3_p_ZL10e0_bram_w1_23_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_mlp_head443_Pipeline_VITIS_LOOP_586_3_p_ZL10e0_bram_w1_23_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00110001110010011101101010001011", 1 => "10101011101000010000101001110000", 2 => "00101010011110110110100000101101", 3 => "00110011011101111100010011011100", 
    4 => "10110011110000101100000010010011", 5 => "10100111110011100001011000010010", 6 => "10011001100110001100110100110100", 7 => "10110101010111011101001100111100", 
    8 => "00110110000000011100100111100010", 9 => "10110100000010001101001000010100", 10 => "10110000001110110011001110000110", 11 => "10100010011111100100001010110100", 
    12 => "00100111011000110011111111101010", 13 => "00110110010001101010001000010100", 14 => "10110111000100101100000011110000", 15 => "10110011111010011101111101101000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

