-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_mlp_head416_Pipeline_VITIS_LOOP_586_3_p_ZL9e2_lut_w1_23_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_mlp_head416_Pipeline_VITIS_LOOP_586_3_p_ZL9e2_lut_w1_23_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101110110110100100001101001", 1 => "00111110010000110000101001011100", 2 => "10111101011010101001100100101101", 3 => "10111011111100111111111000101110", 
    4 => "10111101000111000000001100110111", 5 => "00111101000000100000110010111100", 6 => "10111100110010011100110110010100", 7 => "00111100111101101100001111010011", 
    8 => "10111100011011111001111001011010", 9 => "10111101000101100001010101111111", 10 => "10111100111110101010000001111100", 11 => "00111110000101100101100111000101", 
    12 => "00111100000000010000001010111101", 13 => "10111101000010001001001010110000", 14 => "10111101110010101101110000100001", 15 => "10111011000111110110000000100010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

