-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_mlp_head479_Pipeline_VITIS_LOOP_586_3_p_ZL10e1_bram_w1_7_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_mlp_head479_Pipeline_VITIS_LOOP_586_3_p_ZL10e1_bram_w1_7_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111001100011000101100001001000", 1 => "00111001001011011100110111010010", 2 => "10111100111101011101110011110011", 3 => "10111101010101111010110110110001", 
    4 => "10111101101010010011110001111000", 5 => "00111100010110111100000100011100", 6 => "00111001110111011010100011101110", 7 => "00111101101100010101110110001010", 
    8 => "10111101001101011101110101111011", 9 => "00111011111000111010010011010011", 10 => "10111101011010111110110000101010", 11 => "10111100001001011011000100000100", 
    12 => "10111010110111011000010001111000", 13 => "00111101101101010101110110001000", 14 => "10111101011101010101100101101001", 15 => "00111100111110010110001101110010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

