-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity output_moe_mlp_head453_Pipeline_VITIS_LOOP_586_3_p_ZL10e3_perf_w1_7_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 16
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of output_moe_mlp_head453_Pipeline_VITIS_LOOP_586_3_p_ZL10e3_perf_w1_7_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111100111010111111101000101111", 1 => "10111110001100100111010101011110", 2 => "10111101011000000111001011010010", 3 => "00111101110110001010011111111111", 
    4 => "10111110000110100101111001110000", 5 => "00111101011000000101001111010011", 6 => "00111100100000010110001101101010", 7 => "10111100101110011010000001011110", 
    8 => "00111110100111001101010001100110", 9 => "00111110000101000010000001010000", 10 => "10111101100110101111000100110111", 11 => "10111100000011010001101101010011", 
    12 => "00111110010010001001000000000001", 13 => "10111101111101011111010000100010", 14 => "10111110100010101001011110000111", 15 => "10111101100110111111111000101000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

