// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module graph_moe_graph_moe_Pipeline_VITIS_LOOP_262_12 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        empty,
        w3_address0,
        w3_ce0,
        w3_q0,
        w3_address1,
        w3_ce1,
        w3_q1,
        b3_address0,
        b3_ce0,
        b3_q0,
        l3_2_address0,
        l3_2_ce0,
        l3_2_we0,
        l3_2_d0,
        l3_address0,
        l3_ce0,
        l3_we0,
        l3_d0,
        tmp_66,
        tmp_67,
        tmp_68,
        tmp_69,
        tmp_70,
        tmp_71,
        tmp_72,
        tmp_73,
        tmp_74,
        tmp_75,
        tmp_76,
        tmp_77,
        tmp_78,
        tmp_79,
        tmp_80,
        tmp_81,
        cond,
        grp_fu_8225_p_din0,
        grp_fu_8225_p_din1,
        grp_fu_8225_p_opcode,
        grp_fu_8225_p_dout0,
        grp_fu_8225_p_ce,
        grp_fu_8229_p_din0,
        grp_fu_8229_p_din1,
        grp_fu_8229_p_opcode,
        grp_fu_8229_p_dout0,
        grp_fu_8229_p_ce,
        grp_fu_8237_p_din0,
        grp_fu_8237_p_din1,
        grp_fu_8237_p_opcode,
        grp_fu_8237_p_dout0,
        grp_fu_8237_p_ce,
        grp_fu_8221_p_din0,
        grp_fu_8221_p_din1,
        grp_fu_8221_p_dout0,
        grp_fu_8221_p_ce,
        grp_fu_8241_p_din0,
        grp_fu_8241_p_din1,
        grp_fu_8241_p_dout0,
        grp_fu_8241_p_ce,
        grp_fu_8233_p_din0,
        grp_fu_8233_p_din1,
        grp_fu_8233_p_dout0,
        grp_fu_8233_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 8'd1;
parameter    ap_ST_fsm_pp0_stage1 = 8'd2;
parameter    ap_ST_fsm_pp0_stage2 = 8'd4;
parameter    ap_ST_fsm_pp0_stage3 = 8'd8;
parameter    ap_ST_fsm_pp0_stage4 = 8'd16;
parameter    ap_ST_fsm_pp0_stage5 = 8'd32;
parameter    ap_ST_fsm_pp0_stage6 = 8'd64;
parameter    ap_ST_fsm_pp0_stage7 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] empty;
output  [11:0] w3_address0;
output   w3_ce0;
input  [31:0] w3_q0;
output  [11:0] w3_address1;
output   w3_ce1;
input  [31:0] w3_q1;
output  [7:0] b3_address0;
output   b3_ce0;
input  [31:0] b3_q0;
output  [2:0] l3_2_address0;
output   l3_2_ce0;
output   l3_2_we0;
output  [31:0] l3_2_d0;
output  [2:0] l3_address0;
output   l3_ce0;
output   l3_we0;
output  [31:0] l3_d0;
input  [31:0] tmp_66;
input  [31:0] tmp_67;
input  [31:0] tmp_68;
input  [31:0] tmp_69;
input  [31:0] tmp_70;
input  [31:0] tmp_71;
input  [31:0] tmp_72;
input  [31:0] tmp_73;
input  [31:0] tmp_74;
input  [31:0] tmp_75;
input  [31:0] tmp_76;
input  [31:0] tmp_77;
input  [31:0] tmp_78;
input  [31:0] tmp_79;
input  [31:0] tmp_80;
input  [31:0] tmp_81;
input  [0:0] cond;
output  [31:0] grp_fu_8225_p_din0;
output  [31:0] grp_fu_8225_p_din1;
output  [0:0] grp_fu_8225_p_opcode;
input  [31:0] grp_fu_8225_p_dout0;
output   grp_fu_8225_p_ce;
output  [31:0] grp_fu_8229_p_din0;
output  [31:0] grp_fu_8229_p_din1;
output  [1:0] grp_fu_8229_p_opcode;
input  [31:0] grp_fu_8229_p_dout0;
output   grp_fu_8229_p_ce;
output  [31:0] grp_fu_8237_p_din0;
output  [31:0] grp_fu_8237_p_din1;
output  [1:0] grp_fu_8237_p_opcode;
input  [31:0] grp_fu_8237_p_dout0;
output   grp_fu_8237_p_ce;
output  [31:0] grp_fu_8221_p_din0;
output  [31:0] grp_fu_8221_p_din1;
input  [31:0] grp_fu_8221_p_dout0;
output   grp_fu_8221_p_ce;
output  [31:0] grp_fu_8241_p_din0;
output  [31:0] grp_fu_8241_p_din1;
input  [31:0] grp_fu_8241_p_dout0;
output   grp_fu_8241_p_ce;
output  [31:0] grp_fu_8233_p_din0;
output  [31:0] grp_fu_8233_p_din1;
input  [31:0] grp_fu_8233_p_dout0;
output   grp_fu_8233_p_ce;

reg ap_idle;
reg[11:0] w3_address0;
reg w3_ce0;
reg[11:0] w3_address1;
reg w3_ce1;
reg b3_ce0;
reg l3_2_ce0;
reg l3_2_we0;
reg l3_ce0;
reg l3_we0;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage7_subdone;
reg   [0:0] icmp_ln262_reg_907;
reg    ap_condition_exit_pp0_iter0_stage7;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [31:0] reg_447;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_11001;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6_11001;
wire    ap_block_pp0_stage0_11001;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
reg   [31:0] reg_453;
reg   [31:0] reg_459;
reg   [31:0] reg_464;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5_11001;
wire    ap_block_pp0_stage7_11001;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire   [0:0] cond_read_reg_818;
reg   [3:0] i_3_reg_902;
reg   [3:0] i_3_reg_902_pp0_iter1_reg;
reg   [3:0] i_3_reg_902_pp0_iter2_reg;
reg   [3:0] i_3_reg_902_pp0_iter3_reg;
reg   [3:0] i_3_reg_902_pp0_iter4_reg;
reg   [3:0] i_3_reg_902_pp0_iter5_reg;
wire   [0:0] icmp_ln262_fu_477_p2;
reg   [0:0] icmp_ln262_reg_907_pp0_iter1_reg;
reg   [0:0] icmp_ln262_reg_907_pp0_iter2_reg;
reg   [0:0] icmp_ln262_reg_907_pp0_iter3_reg;
reg   [0:0] icmp_ln262_reg_907_pp0_iter4_reg;
wire   [11:0] tmp_7_fu_504_p3;
reg   [11:0] tmp_7_reg_911;
reg   [31:0] b3_load_reg_954;
wire   [31:0] bitcast_ln270_fu_553_p1;
wire   [31:0] bitcast_ln270_1_fu_558_p1;
reg   [31:0] mul4_reg_979;
reg   [31:0] mul176_s_reg_984;
wire   [31:0] bitcast_ln270_2_fu_583_p1;
wire   [31:0] bitcast_ln270_3_fu_588_p1;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_11001;
wire   [31:0] sum_fu_613_p1;
reg   [31:0] mul176_2_reg_1014;
reg   [31:0] mul176_3_reg_1019;
wire   [31:0] bitcast_ln270_4_fu_617_p1;
wire   [31:0] bitcast_ln270_5_fu_622_p1;
reg   [31:0] mul176_4_reg_1044;
reg   [31:0] mul176_5_reg_1049;
reg   [31:0] mul176_5_reg_1049_pp0_iter1_reg;
wire   [31:0] bitcast_ln270_6_fu_647_p1;
wire   [31:0] bitcast_ln270_7_fu_652_p1;
reg   [31:0] mul176_6_reg_1074;
reg   [31:0] mul176_6_reg_1074_pp0_iter1_reg;
reg   [31:0] mul176_7_reg_1079;
reg   [31:0] mul176_7_reg_1079_pp0_iter1_reg;
wire   [31:0] bitcast_ln270_8_fu_677_p1;
wire   [31:0] bitcast_ln270_9_fu_682_p1;
reg   [31:0] mul176_8_reg_1104;
reg   [31:0] mul176_8_reg_1104_pp0_iter1_reg;
reg   [31:0] mul176_9_reg_1109;
reg   [31:0] mul176_9_reg_1109_pp0_iter1_reg;
wire   [31:0] bitcast_ln270_10_fu_707_p1;
wire   [31:0] bitcast_ln270_11_fu_712_p1;
reg   [31:0] mul176_1_reg_1134;
reg   [31:0] mul176_1_reg_1134_pp0_iter1_reg;
reg   [31:0] mul176_10_reg_1139;
reg   [31:0] mul176_10_reg_1139_pp0_iter1_reg;
reg   [31:0] mul176_10_reg_1139_pp0_iter2_reg;
wire   [31:0] bitcast_ln270_12_fu_737_p1;
wire   [31:0] bitcast_ln270_13_fu_742_p1;
reg   [31:0] mul176_11_reg_1154;
reg   [31:0] mul176_11_reg_1154_pp0_iter2_reg;
reg   [31:0] mul176_11_reg_1154_pp0_iter3_reg;
reg   [31:0] mul176_12_reg_1159;
reg   [31:0] mul176_12_reg_1159_pp0_iter2_reg;
reg   [31:0] mul176_12_reg_1159_pp0_iter3_reg;
wire   [31:0] bitcast_ln270_14_fu_747_p1;
wire   [31:0] bitcast_ln270_15_fu_752_p1;
reg   [31:0] mul176_13_reg_1174;
reg   [31:0] mul176_13_reg_1174_pp0_iter2_reg;
reg   [31:0] mul176_13_reg_1174_pp0_iter3_reg;
reg   [31:0] mul176_14_reg_1179;
reg   [31:0] mul176_14_reg_1179_pp0_iter2_reg;
reg   [31:0] mul176_14_reg_1179_pp0_iter3_reg;
reg   [31:0] mul176_14_reg_1179_pp0_iter4_reg;
reg   [31:0] sum_33_reg_1184;
reg   [31:0] sum_37_reg_1189;
reg   [31:0] tmp_6_reg_1197;
wire   [0:0] tmp_5_fu_437_p2;
reg   [0:0] tmp_5_reg_1202;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage1_subdone;
wire   [63:0] zext_ln270_19_fu_512_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln270_20_fu_523_p1;
wire   [63:0] zext_ln270_18_fu_499_p1;
wire   [63:0] zext_ln270_21_fu_538_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln270_22_fu_548_p1;
wire   [63:0] zext_ln270_23_fu_568_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln270_24_fu_578_p1;
wire   [63:0] zext_ln270_25_fu_598_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] zext_ln270_26_fu_608_p1;
wire   [63:0] zext_ln270_27_fu_632_p1;
wire    ap_block_pp0_stage4;
wire   [63:0] zext_ln270_28_fu_642_p1;
wire   [63:0] zext_ln270_29_fu_662_p1;
wire    ap_block_pp0_stage5;
wire   [63:0] zext_ln270_30_fu_672_p1;
wire   [63:0] zext_ln270_31_fu_692_p1;
wire    ap_block_pp0_stage6;
wire   [63:0] zext_ln270_32_fu_702_p1;
wire   [63:0] zext_ln270_33_fu_722_p1;
wire    ap_block_pp0_stage7;
wire   [63:0] zext_ln270_34_fu_732_p1;
wire   [63:0] zext_ln262_fu_757_p1;
reg   [3:0] i_fu_128;
wire   [3:0] add_ln262_fu_483_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_i_3;
wire   [31:0] select_ln8_fu_802_p3;
reg   [31:0] grp_fu_416_p0;
reg   [31:0] grp_fu_416_p1;
reg   [31:0] grp_fu_420_p0;
reg   [31:0] grp_fu_420_p1;
reg   [31:0] grp_fu_424_p0;
reg   [31:0] grp_fu_424_p1;
reg   [31:0] grp_fu_429_p0;
reg   [31:0] grp_fu_429_p1;
reg   [31:0] grp_fu_433_p0;
reg   [31:0] grp_fu_433_p1;
wire   [7:0] zext_ln270_fu_489_p1;
wire   [7:0] add_ln270_fu_493_p2;
wire   [11:0] or_ln270_fu_517_p2;
wire   [11:0] or_ln270_1_fu_533_p2;
wire   [11:0] or_ln270_2_fu_543_p2;
wire   [11:0] or_ln270_3_fu_563_p2;
wire   [11:0] or_ln270_4_fu_573_p2;
wire   [11:0] or_ln270_5_fu_593_p2;
wire   [11:0] or_ln270_6_fu_603_p2;
wire   [11:0] or_ln270_7_fu_627_p2;
wire   [11:0] or_ln270_8_fu_637_p2;
wire   [11:0] or_ln270_9_fu_657_p2;
wire   [11:0] or_ln270_10_fu_667_p2;
wire   [11:0] or_ln270_11_fu_687_p2;
wire   [11:0] or_ln270_12_fu_697_p2;
wire   [11:0] or_ln270_13_fu_717_p2;
wire   [11:0] or_ln270_14_fu_727_p2;
wire   [31:0] bitcast_ln8_fu_762_p1;
wire   [7:0] tmp_s_fu_765_p4;
wire   [22:0] trunc_ln8_fu_775_p1;
wire   [0:0] icmp_ln8_2_fu_785_p2;
wire   [0:0] icmp_ln8_fu_779_p2;
wire   [0:0] or_ln8_fu_791_p2;
wire   [0:0] and_ln8_fu_797_p2;
wire    ap_block_pp0_stage3_00001;
wire    ap_block_pp0_stage5_00001;
wire    ap_block_pp0_stage7_00001;
wire    ap_block_pp0_stage1_00001;
wire    ap_block_pp0_stage4_00001;
wire    ap_block_pp0_stage6_00001;
wire    ap_block_pp0_stage0_00001;
wire    ap_block_pp0_stage2_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter4_stage1;
reg    ap_idle_pp0_0to3;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [7:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to5;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 i_fu_128 = 4'd0;
#0 ap_done_reg = 1'b0;
end

graph_moe_fcmp_32ns_32ns_1_1_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_1_no_dsp_1_U222(
    .din0(sum_37_reg_1189),
    .din1(32'd0),
    .opcode(5'd3),
    .dout(tmp_5_fu_437_p2)
);

graph_moe_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage7),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage7)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage1))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln262_fu_477_p2 == 1'd0))) begin
            i_fu_128 <= add_ln262_fu_483_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_128 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b3_load_reg_954 <= b3_q0;
        mul176_13_reg_1174_pp0_iter2_reg <= mul176_13_reg_1174;
        mul176_13_reg_1174_pp0_iter3_reg <= mul176_13_reg_1174_pp0_iter2_reg;
        mul176_14_reg_1179_pp0_iter2_reg <= mul176_14_reg_1179;
        mul176_14_reg_1179_pp0_iter3_reg <= mul176_14_reg_1179_pp0_iter2_reg;
        mul176_14_reg_1179_pp0_iter4_reg <= mul176_14_reg_1179_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_3_reg_902 <= ap_sig_allocacmp_i_3;
        i_3_reg_902_pp0_iter1_reg <= i_3_reg_902;
        i_3_reg_902_pp0_iter2_reg <= i_3_reg_902_pp0_iter1_reg;
        i_3_reg_902_pp0_iter3_reg <= i_3_reg_902_pp0_iter2_reg;
        i_3_reg_902_pp0_iter4_reg <= i_3_reg_902_pp0_iter3_reg;
        i_3_reg_902_pp0_iter5_reg <= i_3_reg_902_pp0_iter4_reg;
        icmp_ln262_reg_907 <= icmp_ln262_fu_477_p2;
        icmp_ln262_reg_907_pp0_iter1_reg <= icmp_ln262_reg_907;
        icmp_ln262_reg_907_pp0_iter2_reg <= icmp_ln262_reg_907_pp0_iter1_reg;
        icmp_ln262_reg_907_pp0_iter3_reg <= icmp_ln262_reg_907_pp0_iter2_reg;
        icmp_ln262_reg_907_pp0_iter4_reg <= icmp_ln262_reg_907_pp0_iter3_reg;
        mul176_11_reg_1154_pp0_iter2_reg <= mul176_11_reg_1154;
        mul176_11_reg_1154_pp0_iter3_reg <= mul176_11_reg_1154_pp0_iter2_reg;
        mul176_12_reg_1159_pp0_iter2_reg <= mul176_12_reg_1159;
        mul176_12_reg_1159_pp0_iter3_reg <= mul176_12_reg_1159_pp0_iter2_reg;
        tmp_5_reg_1202 <= tmp_5_fu_437_p2;
        tmp_7_reg_911[11 : 4] <= tmp_7_fu_504_p3[11 : 4];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        mul176_10_reg_1139 <= grp_fu_8241_p_dout0;
        mul176_1_reg_1134 <= grp_fu_8221_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        mul176_10_reg_1139_pp0_iter1_reg <= mul176_10_reg_1139;
        mul176_10_reg_1139_pp0_iter2_reg <= mul176_10_reg_1139_pp0_iter1_reg;
        mul176_1_reg_1134_pp0_iter1_reg <= mul176_1_reg_1134;
        tmp_6_reg_1197 <= grp_fu_8233_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul176_11_reg_1154 <= grp_fu_8221_p_dout0;
        mul176_12_reg_1159 <= grp_fu_8241_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        mul176_13_reg_1174 <= grp_fu_8221_p_dout0;
        mul176_14_reg_1179 <= grp_fu_8241_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        mul176_2_reg_1014 <= grp_fu_8221_p_dout0;
        mul176_3_reg_1019 <= grp_fu_8241_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        mul176_4_reg_1044 <= grp_fu_8221_p_dout0;
        mul176_5_reg_1049 <= grp_fu_8241_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        mul176_5_reg_1049_pp0_iter1_reg <= mul176_5_reg_1049;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        mul176_6_reg_1074 <= grp_fu_8221_p_dout0;
        mul176_7_reg_1079 <= grp_fu_8241_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        mul176_6_reg_1074_pp0_iter1_reg <= mul176_6_reg_1074;
        mul176_7_reg_1079_pp0_iter1_reg <= mul176_7_reg_1079;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        mul176_8_reg_1104 <= grp_fu_8221_p_dout0;
        mul176_9_reg_1109 <= grp_fu_8241_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        mul176_8_reg_1104_pp0_iter1_reg <= mul176_8_reg_1104;
        mul176_9_reg_1109_pp0_iter1_reg <= mul176_9_reg_1109;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mul176_s_reg_984 <= grp_fu_8241_p_dout0;
        mul4_reg_979 <= grp_fu_8221_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        reg_447 <= grp_fu_8225_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        reg_453 <= grp_fu_8229_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        reg_459 <= grp_fu_8237_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        reg_464 <= grp_fu_8225_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        sum_33_reg_1184 <= grp_fu_8237_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        sum_37_reg_1189 <= grp_fu_8225_p_dout0;
    end
end

always @ (*) begin
    if (((icmp_ln262_reg_907 == 1'd1) & (1'b0 == ap_block_pp0_stage7_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_condition_exit_pp0_iter0_stage7 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1) & (icmp_ln262_reg_907_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter4_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter4_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter4_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to3 = 1'b1;
    end else begin
        ap_idle_pp0_0to3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to5 = 1'b1;
    end else begin
        ap_idle_pp0_1to5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage7_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_3 = 4'd0;
    end else begin
        ap_sig_allocacmp_i_3 = i_fu_128;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b3_ce0 = 1'b1;
    end else begin
        b3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_416_p0 = reg_464;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_416_p0 = sum_33_reg_1184;
    end else if ((((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_416_p0 = reg_447;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_416_p0 = sum_fu_613_p1;
    end else begin
        grp_fu_416_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_416_p1 = mul176_14_reg_1179_pp0_iter4_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_416_p1 = mul176_13_reg_1174_pp0_iter3_reg;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_416_p1 = mul176_12_reg_1159_pp0_iter3_reg;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_416_p1 = mul176_11_reg_1154_pp0_iter3_reg;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_416_p1 = mul176_3_reg_1019;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_416_p1 = mul176_2_reg_1014;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_416_p1 = mul176_s_reg_984;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_416_p1 = mul4_reg_979;
    end else begin
        grp_fu_416_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_420_p0 = tmp_6_reg_1197;
    end else if ((((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_420_p0 = reg_453;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_420_p0 = reg_447;
    end else begin
        grp_fu_420_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_420_p1 = 32'd3212836864;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_420_p1 = mul176_7_reg_1079_pp0_iter1_reg;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_420_p1 = mul176_6_reg_1074_pp0_iter1_reg;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_420_p1 = mul176_5_reg_1049_pp0_iter1_reg;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_420_p1 = mul176_4_reg_1044;
    end else begin
        grp_fu_420_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_424_p0 = reg_459;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_424_p0 = reg_453;
    end else begin
        grp_fu_424_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_424_p1 = mul176_10_reg_1139_pp0_iter2_reg;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_424_p1 = mul176_1_reg_1134_pp0_iter1_reg;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_424_p1 = mul176_9_reg_1109_pp0_iter1_reg;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_424_p1 = mul176_8_reg_1104_pp0_iter1_reg;
    end else begin
        grp_fu_424_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_429_p0 = bitcast_ln270_14_fu_747_p1;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_429_p0 = bitcast_ln270_12_fu_737_p1;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_429_p0 = bitcast_ln270_10_fu_707_p1;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_429_p0 = bitcast_ln270_8_fu_677_p1;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_429_p0 = bitcast_ln270_6_fu_647_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_429_p0 = bitcast_ln270_4_fu_617_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_429_p0 = bitcast_ln270_2_fu_583_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_429_p0 = bitcast_ln270_fu_553_p1;
    end else begin
        grp_fu_429_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_429_p1 = tmp_80;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_429_p1 = tmp_78;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_429_p1 = tmp_76;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_429_p1 = tmp_74;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_429_p1 = tmp_72;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_429_p1 = tmp_70;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_429_p1 = tmp_68;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_429_p1 = tmp_66;
    end else begin
        grp_fu_429_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_433_p0 = bitcast_ln270_15_fu_752_p1;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_433_p0 = bitcast_ln270_13_fu_742_p1;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_433_p0 = bitcast_ln270_11_fu_712_p1;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_433_p0 = bitcast_ln270_9_fu_682_p1;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_433_p0 = bitcast_ln270_7_fu_652_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_433_p0 = bitcast_ln270_5_fu_622_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_433_p0 = bitcast_ln270_3_fu_588_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_433_p0 = bitcast_ln270_1_fu_558_p1;
    end else begin
        grp_fu_433_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_433_p1 = tmp_81;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_433_p1 = tmp_79;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_433_p1 = tmp_77;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_433_p1 = tmp_75;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_433_p1 = tmp_73;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_433_p1 = tmp_71;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_433_p1 = tmp_69;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_433_p1 = tmp_67;
    end else begin
        grp_fu_433_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        l3_2_ce0 = 1'b1;
    end else begin
        l3_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (cond_read_reg_818 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        l3_2_we0 = 1'b1;
    end else begin
        l3_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        l3_ce0 = 1'b1;
    end else begin
        l3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (cond_read_reg_818 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        l3_we0 = 1'b1;
    end else begin
        l3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            w3_address0 = zext_ln270_34_fu_732_p1;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            w3_address0 = zext_ln270_32_fu_702_p1;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            w3_address0 = zext_ln270_30_fu_672_p1;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            w3_address0 = zext_ln270_28_fu_642_p1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            w3_address0 = zext_ln270_26_fu_608_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            w3_address0 = zext_ln270_24_fu_578_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            w3_address0 = zext_ln270_22_fu_548_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            w3_address0 = zext_ln270_20_fu_523_p1;
        end else begin
            w3_address0 = 'bx;
        end
    end else begin
        w3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            w3_address1 = zext_ln270_33_fu_722_p1;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            w3_address1 = zext_ln270_31_fu_692_p1;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            w3_address1 = zext_ln270_29_fu_662_p1;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            w3_address1 = zext_ln270_27_fu_632_p1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            w3_address1 = zext_ln270_25_fu_598_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            w3_address1 = zext_ln270_23_fu_568_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            w3_address1 = zext_ln270_21_fu_538_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            w3_address1 = zext_ln270_19_fu_512_p1;
        end else begin
            w3_address1 = 'bx;
        end
    end else begin
        w3_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        w3_ce0 = 1'b1;
    end else begin
        w3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        w3_ce1 = 1'b1;
    end else begin
        w3_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to5 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if (((ap_idle_pp0_0to3 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter4_stage1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln262_fu_483_p2 = (ap_sig_allocacmp_i_3 + 4'd1);

assign add_ln270_fu_493_p2 = (empty + zext_ln270_fu_489_p1);

assign and_ln8_fu_797_p2 = (tmp_5_reg_1202 & or_ln8_fu_791_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage7;

assign b3_address0 = zext_ln270_18_fu_499_p1;

assign bitcast_ln270_10_fu_707_p1 = w3_q1;

assign bitcast_ln270_11_fu_712_p1 = w3_q0;

assign bitcast_ln270_12_fu_737_p1 = w3_q1;

assign bitcast_ln270_13_fu_742_p1 = w3_q0;

assign bitcast_ln270_14_fu_747_p1 = w3_q1;

assign bitcast_ln270_15_fu_752_p1 = w3_q0;

assign bitcast_ln270_1_fu_558_p1 = w3_q0;

assign bitcast_ln270_2_fu_583_p1 = w3_q1;

assign bitcast_ln270_3_fu_588_p1 = w3_q0;

assign bitcast_ln270_4_fu_617_p1 = w3_q1;

assign bitcast_ln270_5_fu_622_p1 = w3_q0;

assign bitcast_ln270_6_fu_647_p1 = w3_q1;

assign bitcast_ln270_7_fu_652_p1 = w3_q0;

assign bitcast_ln270_8_fu_677_p1 = w3_q1;

assign bitcast_ln270_9_fu_682_p1 = w3_q0;

assign bitcast_ln270_fu_553_p1 = w3_q1;

assign bitcast_ln8_fu_762_p1 = sum_37_reg_1189;

assign cond_read_reg_818 = cond;

assign grp_fu_8221_p_ce = 1'b1;

assign grp_fu_8221_p_din0 = grp_fu_429_p0;

assign grp_fu_8221_p_din1 = grp_fu_429_p1;

assign grp_fu_8225_p_ce = 1'b1;

assign grp_fu_8225_p_din0 = grp_fu_416_p0;

assign grp_fu_8225_p_din1 = grp_fu_416_p1;

assign grp_fu_8225_p_opcode = 2'd0;

assign grp_fu_8229_p_ce = 1'b1;

assign grp_fu_8229_p_din0 = grp_fu_420_p0;

assign grp_fu_8229_p_din1 = grp_fu_420_p1;

assign grp_fu_8229_p_opcode = 2'd0;

assign grp_fu_8233_p_ce = 1'b1;

assign grp_fu_8233_p_din0 = 32'd0;

assign grp_fu_8233_p_din1 = sum_37_reg_1189;

assign grp_fu_8237_p_ce = 1'b1;

assign grp_fu_8237_p_din0 = grp_fu_424_p0;

assign grp_fu_8237_p_din1 = grp_fu_424_p1;

assign grp_fu_8237_p_opcode = 2'd0;

assign grp_fu_8241_p_ce = 1'b1;

assign grp_fu_8241_p_din0 = grp_fu_433_p0;

assign grp_fu_8241_p_din1 = grp_fu_433_p1;

assign icmp_ln262_fu_477_p2 = ((ap_sig_allocacmp_i_3 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln8_2_fu_785_p2 = ((trunc_ln8_fu_775_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln8_fu_779_p2 = ((tmp_s_fu_765_p4 != 8'd255) ? 1'b1 : 1'b0);

assign l3_2_address0 = zext_ln262_fu_757_p1;

assign l3_2_d0 = select_ln8_fu_802_p3;

assign l3_address0 = zext_ln262_fu_757_p1;

assign l3_d0 = select_ln8_fu_802_p3;

assign or_ln270_10_fu_667_p2 = (tmp_7_reg_911 | 12'd11);

assign or_ln270_11_fu_687_p2 = (tmp_7_reg_911 | 12'd12);

assign or_ln270_12_fu_697_p2 = (tmp_7_reg_911 | 12'd13);

assign or_ln270_13_fu_717_p2 = (tmp_7_reg_911 | 12'd14);

assign or_ln270_14_fu_727_p2 = (tmp_7_reg_911 | 12'd15);

assign or_ln270_1_fu_533_p2 = (tmp_7_reg_911 | 12'd2);

assign or_ln270_2_fu_543_p2 = (tmp_7_reg_911 | 12'd3);

assign or_ln270_3_fu_563_p2 = (tmp_7_reg_911 | 12'd4);

assign or_ln270_4_fu_573_p2 = (tmp_7_reg_911 | 12'd5);

assign or_ln270_5_fu_593_p2 = (tmp_7_reg_911 | 12'd6);

assign or_ln270_6_fu_603_p2 = (tmp_7_reg_911 | 12'd7);

assign or_ln270_7_fu_627_p2 = (tmp_7_reg_911 | 12'd8);

assign or_ln270_8_fu_637_p2 = (tmp_7_reg_911 | 12'd9);

assign or_ln270_9_fu_657_p2 = (tmp_7_reg_911 | 12'd10);

assign or_ln270_fu_517_p2 = (tmp_7_fu_504_p3 | 12'd1);

assign or_ln8_fu_791_p2 = (icmp_ln8_fu_779_p2 | icmp_ln8_2_fu_785_p2);

assign select_ln8_fu_802_p3 = ((and_ln8_fu_797_p2[0:0] == 1'b1) ? sum_37_reg_1189 : grp_fu_8229_p_dout0);

assign sum_fu_613_p1 = b3_load_reg_954;

assign tmp_7_fu_504_p3 = {{add_ln270_fu_493_p2}, {4'd0}};

assign tmp_s_fu_765_p4 = {{bitcast_ln8_fu_762_p1[30:23]}};

assign trunc_ln8_fu_775_p1 = bitcast_ln8_fu_762_p1[22:0];

assign zext_ln262_fu_757_p1 = i_3_reg_902_pp0_iter5_reg;

assign zext_ln270_18_fu_499_p1 = add_ln270_fu_493_p2;

assign zext_ln270_19_fu_512_p1 = tmp_7_fu_504_p3;

assign zext_ln270_20_fu_523_p1 = or_ln270_fu_517_p2;

assign zext_ln270_21_fu_538_p1 = or_ln270_1_fu_533_p2;

assign zext_ln270_22_fu_548_p1 = or_ln270_2_fu_543_p2;

assign zext_ln270_23_fu_568_p1 = or_ln270_3_fu_563_p2;

assign zext_ln270_24_fu_578_p1 = or_ln270_4_fu_573_p2;

assign zext_ln270_25_fu_598_p1 = or_ln270_5_fu_593_p2;

assign zext_ln270_26_fu_608_p1 = or_ln270_6_fu_603_p2;

assign zext_ln270_27_fu_632_p1 = or_ln270_7_fu_627_p2;

assign zext_ln270_28_fu_642_p1 = or_ln270_8_fu_637_p2;

assign zext_ln270_29_fu_662_p1 = or_ln270_9_fu_657_p2;

assign zext_ln270_30_fu_672_p1 = or_ln270_10_fu_667_p2;

assign zext_ln270_31_fu_692_p1 = or_ln270_11_fu_687_p2;

assign zext_ln270_32_fu_702_p1 = or_ln270_12_fu_697_p2;

assign zext_ln270_33_fu_722_p1 = or_ln270_13_fu_717_p2;

assign zext_ln270_34_fu_732_p1 = or_ln270_14_fu_727_p2;

assign zext_ln270_fu_489_p1 = ap_sig_allocacmp_i_3;

always @ (posedge ap_clk) begin
    tmp_7_reg_911[3:0] <= 4'b0000;
end

endmodule //graph_moe_graph_moe_Pipeline_VITIS_LOOP_262_12
