-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity graph_moe_graph_moe_Pipeline_VITIS_LOOP_243_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    max_logit : IN STD_LOGIC_VECTOR (31 downto 0);
    max_logit_21850 : IN STD_LOGIC_VECTOR (31 downto 0);
    max_logit_22046 : IN STD_LOGIC_VECTOR (31 downto 0);
    max_logit_21954 : IN STD_LOGIC_VECTOR (31 downto 0);
    max_logit_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    max_logit_1_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of graph_moe_graph_moe_Pipeline_VITIS_LOOP_243_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln243_fu_106_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln243_reg_272 : STD_LOGIC_VECTOR (0 downto 0);
    signal max_logit_2_fu_136_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal max_logit_2_reg_276 : STD_LOGIC_VECTOR (31 downto 0);
    signal max_logit_3_fu_242_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal max_logit_3_reg_283 : STD_LOGIC_VECTOR (31 downto 0);
    signal max_logit_1_fu_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_max_logit_1_load_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_loop_init : STD_LOGIC;
    signal e_1_fu_54 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln243_fu_144_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_e : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal trunc_ln245_fu_112_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln245_fu_116_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln245_1_fu_130_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln245_fu_122_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln245_fu_159_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln245_1_fu_176_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_162_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln245_1_fu_172_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln245_3_fu_200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln245_2_fu_194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_180_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln245_2_fu_190_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln245_5_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln245_4_fu_212_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_89_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln245_fu_206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln245_fu_230_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln245_1_fu_224_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln245_1_fu_236_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component graph_moe_fcmp_32ns_32ns_1_1_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component graph_moe_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    fcmp_32ns_32ns_1_1_no_dsp_1_U8 : component graph_moe_fcmp_32ns_32ns_1_1_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        din0 => max_logit_2_reg_276,
        din1 => ap_sig_allocacmp_max_logit_1_load_1,
        opcode => ap_const_lv5_2,
        dout => tmp_6_fu_89_p2);

    flow_control_loop_pipe_sequential_init_U : component graph_moe_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    e_1_fu_54_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln243_fu_106_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    e_1_fu_54 <= add_ln243_fu_144_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    e_1_fu_54 <= ap_const_lv3_1;
                end if;
            end if; 
        end if;
    end process;

    max_logit_1_fu_50_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    max_logit_1_fu_50 <= max_logit;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    max_logit_1_fu_50 <= max_logit_3_reg_283;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln243_reg_272 <= icmp_ln243_fu_106_p2;
                max_logit_2_reg_276 <= max_logit_2_fu_136_p3;
                max_logit_3_reg_283 <= max_logit_3_fu_242_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln243_fu_144_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_e) + unsigned(ap_const_lv3_1));
    and_ln245_1_fu_236_p2 <= (or_ln245_1_fu_224_p2 and and_ln245_fu_230_p2);
    and_ln245_fu_230_p2 <= (tmp_6_fu_89_p2 and or_ln245_fu_206_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln243_fu_106_p2)
    begin
        if (((icmp_ln243_fu_106_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_e_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, e_1_fu_54)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_e <= ap_const_lv3_1;
        else 
            ap_sig_allocacmp_e <= e_1_fu_54;
        end if; 
    end process;


    ap_sig_allocacmp_max_logit_1_load_1_assign_proc : process(ap_enable_reg_pp0_iter2, max_logit_3_reg_283, max_logit_1_fu_50, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ap_sig_allocacmp_max_logit_1_load_1 <= max_logit_3_reg_283;
        else 
            ap_sig_allocacmp_max_logit_1_load_1 <= max_logit_1_fu_50;
        end if; 
    end process;

    bitcast_ln245_1_fu_176_p1 <= ap_sig_allocacmp_max_logit_1_load_1;
    bitcast_ln245_fu_159_p1 <= max_logit_2_reg_276;
    icmp_ln243_fu_106_p2 <= "1" when (ap_sig_allocacmp_e = ap_const_lv3_4) else "0";
    icmp_ln245_1_fu_130_p2 <= "1" when (trunc_ln245_fu_112_p1 = ap_const_lv2_2) else "0";
    icmp_ln245_2_fu_194_p2 <= "0" when (tmp_fu_162_p4 = ap_const_lv8_FF) else "1";
    icmp_ln245_3_fu_200_p2 <= "1" when (trunc_ln245_1_fu_172_p1 = ap_const_lv23_0) else "0";
    icmp_ln245_4_fu_212_p2 <= "0" when (tmp_5_fu_180_p4 = ap_const_lv8_FF) else "1";
    icmp_ln245_5_fu_218_p2 <= "1" when (trunc_ln245_2_fu_190_p1 = ap_const_lv23_0) else "0";
    icmp_ln245_fu_116_p2 <= "1" when (trunc_ln245_fu_112_p1 = ap_const_lv2_1) else "0";
    max_logit_1_out <= max_logit_1_fu_50;

    max_logit_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln243_reg_272)
    begin
        if (((icmp_ln243_reg_272 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            max_logit_1_out_ap_vld <= ap_const_logic_1;
        else 
            max_logit_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    max_logit_2_fu_136_p3 <= 
        max_logit_21954 when (icmp_ln245_1_fu_130_p2(0) = '1') else 
        select_ln245_fu_122_p3;
    max_logit_3_fu_242_p3 <= 
        max_logit_2_reg_276 when (and_ln245_1_fu_236_p2(0) = '1') else 
        ap_sig_allocacmp_max_logit_1_load_1;
    or_ln245_1_fu_224_p2 <= (icmp_ln245_5_fu_218_p2 or icmp_ln245_4_fu_212_p2);
    or_ln245_fu_206_p2 <= (icmp_ln245_3_fu_200_p2 or icmp_ln245_2_fu_194_p2);
    select_ln245_fu_122_p3 <= 
        max_logit_21850 when (icmp_ln245_fu_116_p2(0) = '1') else 
        max_logit_22046;
    tmp_5_fu_180_p4 <= bitcast_ln245_1_fu_176_p1(30 downto 23);
    tmp_fu_162_p4 <= bitcast_ln245_fu_159_p1(30 downto 23);
    trunc_ln245_1_fu_172_p1 <= bitcast_ln245_fu_159_p1(23 - 1 downto 0);
    trunc_ln245_2_fu_190_p1 <= bitcast_ln245_1_fu_176_p1(23 - 1 downto 0);
    trunc_ln245_fu_112_p1 <= ap_sig_allocacmp_e(2 - 1 downto 0);
end behav;
